/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChainSource,
  ChainType,
  ListBlockchainsResponse,
} from '../models/index';
import {
    ListBlockchainsResponseFromJSON,
} from '../models/index';

interface ListChainsApiV1BlockchainsGetRequest {
    page?: number;
    size?: number;
    skipCount?: boolean;
    chainTypes?: Array<ChainType>;
    sources?: Array<ChainSource>;
    includeMainnets?: boolean;
    includeTestnets?: boolean;
    includeExchanges?: boolean;
    showAll?: boolean;
}

/**
 * 
 */
export class BlockchainsApi extends runtime.BaseAPI {

    /**
     * Creates request options for listChainsApiV1BlockchainsGet without sending the request
     */
    async listChainsApiV1BlockchainsGetRequestOpts(requestParameters: ListChainsApiV1BlockchainsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['skipCount'] != null) {
            queryParameters['skip_count'] = requestParameters['skipCount'];
        }

        if (requestParameters['chainTypes'] != null) {
            queryParameters['chain_types'] = requestParameters['chainTypes'];
        }

        if (requestParameters['sources'] != null) {
            queryParameters['sources'] = requestParameters['sources'];
        }

        if (requestParameters['includeMainnets'] != null) {
            queryParameters['include_mainnets'] = requestParameters['includeMainnets'];
        }

        if (requestParameters['includeTestnets'] != null) {
            queryParameters['include_testnets'] = requestParameters['includeTestnets'];
        }

        if (requestParameters['includeExchanges'] != null) {
            queryParameters['include_exchanges'] = requestParameters['includeExchanges'];
        }

        if (requestParameters['showAll'] != null) {
            queryParameters['show_all'] = requestParameters['showAll'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/blockchains`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a list of supported blockchains.
     * List Chains
     */
    async listChainsApiV1BlockchainsGetRaw(requestParameters: ListChainsApiV1BlockchainsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListBlockchainsResponse>> {
        const requestOptions = await this.listChainsApiV1BlockchainsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListBlockchainsResponseFromJSON(jsonValue));
    }

    /**
     * Get a list of supported blockchains.
     * List Chains
     */
    async listChainsApiV1BlockchainsGet(requestParameters: ListChainsApiV1BlockchainsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListBlockchainsResponse> {
        const response = await this.listChainsApiV1BlockchainsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
