/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VaultRef } from './VaultRef';
import {
    VaultRefFromJSON,
    VaultRefFromJSONTyped,
    VaultRefToJSON,
    VaultRefToJSONTyped,
} from './VaultRef';

/**
 * 
 * @export
 * @interface AddVaultGroupChanges
 */
export interface AddVaultGroupChanges {
    /**
     * 
     * @type {string}
     * @memberof AddVaultGroupChanges
     */
    changeRequestId: string;
    /**
     * 
     * @type {Array<VaultRef>}
     * @memberof AddVaultGroupChanges
     */
    addedVaults: Array<VaultRef>;
    /**
     * 
     * @type {string}
     * @memberof AddVaultGroupChanges
     */
    type: AddVaultGroupChangesTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AddVaultGroupChanges
     */
    newName: string;
}


/**
 * @export
 */
export const AddVaultGroupChangesTypeEnum = {
    addGroup: 'add_group'
} as const;
export type AddVaultGroupChangesTypeEnum = typeof AddVaultGroupChangesTypeEnum[keyof typeof AddVaultGroupChangesTypeEnum];


/**
 * Check if a given object implements the AddVaultGroupChanges interface.
 */
export function instanceOfAddVaultGroupChanges(value: object): value is AddVaultGroupChanges {
    if (!('changeRequestId' in value) || value['changeRequestId'] === undefined) return false;
    if (!('addedVaults' in value) || value['addedVaults'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('newName' in value) || value['newName'] === undefined) return false;
    return true;
}

export function AddVaultGroupChangesFromJSON(json: any): AddVaultGroupChanges {
    return AddVaultGroupChangesFromJSONTyped(json, false);
}

export function AddVaultGroupChangesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddVaultGroupChanges {
    if (json == null) {
        return json;
    }
    return {
        
        'changeRequestId': json['change_request_id'],
        'addedVaults': ((json['added_vaults'] as Array<any>).map(VaultRefFromJSON)),
        'type': json['type'],
        'newName': json['new_name'],
    };
}

export function AddVaultGroupChangesToJSON(json: any): AddVaultGroupChanges {
    return AddVaultGroupChangesToJSONTyped(json, false);
}

export function AddVaultGroupChangesToJSONTyped(value?: AddVaultGroupChanges | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'change_request_id': value['changeRequestId'],
        'added_vaults': ((value['addedVaults'] as Array<any>).map(VaultRefToJSON)),
        'type': value['type'],
        'new_name': value['newName'],
    };
}

