/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EnrichedEvmAddress } from './EnrichedEvmAddress';
import {
    EnrichedEvmAddressFromJSON,
} from './EnrichedEvmAddress';

/**
 * 
 * @export
 * @interface AllowanceDetails
 */
export interface AllowanceDetails {
    /**
     * 
     * @type {string}
     * @memberof AllowanceDetails
     */
    type: AllowanceDetailsTypeEnum;
    /**
     * 
     * @type {EnrichedEvmAddress}
     * @memberof AllowanceDetails
     */
    spender: EnrichedEvmAddress;
}


/**
 * 
 */
const AllowanceDetailsTypeEnum = {
    allowance: 'allowance'
} as const;
type AllowanceDetailsTypeEnum = typeof AllowanceDetailsTypeEnum[keyof typeof AllowanceDetailsTypeEnum];

export function AllowanceDetailsFromJSONTyped(json: any, _ignoreDiscriminator: boolean): AllowanceDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'spender': EnrichedEvmAddressFromJSON(json['spender']),
    };
}
