/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AmlPolicyMatchIncomingActionType } from './AmlPolicyMatchIncomingActionType';
import {
    AmlPolicyMatchIncomingActionTypeFromJSON,
    AmlPolicyMatchIncomingActionTypeFromJSONTyped,
    AmlPolicyMatchIncomingActionTypeToJSON,
    AmlPolicyMatchIncomingActionTypeToJSONTyped,
} from './AmlPolicyMatchIncomingActionType';
import type { AmlUnfreezeApprovalRequest } from './AmlUnfreezeApprovalRequest';
import {
    AmlUnfreezeApprovalRequestFromJSON,
    AmlUnfreezeApprovalRequestFromJSONTyped,
    AmlUnfreezeApprovalRequestToJSON,
    AmlUnfreezeApprovalRequestToJSONTyped,
} from './AmlUnfreezeApprovalRequest';

/**
 * 
 * @export
 * @interface AmlPolicyMatchIncoming
 */
export interface AmlPolicyMatchIncoming {
    /**
     * 
     * @type {boolean}
     * @memberof AmlPolicyMatchIncoming
     */
    isDefault: boolean;
    /**
     * 
     * @type {string}
     * @memberof AmlPolicyMatchIncoming
     */
    ruleId: string;
    /**
     * 
     * @type {string}
     * @memberof AmlPolicyMatchIncoming
     */
    ruleName: string;
    /**
     * 
     * @type {AmlPolicyMatchIncomingActionType}
     * @memberof AmlPolicyMatchIncoming
     */
    actionType: AmlPolicyMatchIncomingActionType;
    /**
     * 
     * @type {AmlUnfreezeApprovalRequest}
     * @memberof AmlPolicyMatchIncoming
     */
    amlUnfreezeApprovalRequest?: AmlUnfreezeApprovalRequest;
}



/**
 * Check if a given object implements the AmlPolicyMatchIncoming interface.
 */
export function instanceOfAmlPolicyMatchIncoming(value: object): value is AmlPolicyMatchIncoming {
    if (!('isDefault' in value) || value['isDefault'] === undefined) return false;
    if (!('ruleId' in value) || value['ruleId'] === undefined) return false;
    if (!('ruleName' in value) || value['ruleName'] === undefined) return false;
    if (!('actionType' in value) || value['actionType'] === undefined) return false;
    return true;
}

export function AmlPolicyMatchIncomingFromJSON(json: any): AmlPolicyMatchIncoming {
    return AmlPolicyMatchIncomingFromJSONTyped(json, false);
}

export function AmlPolicyMatchIncomingFromJSONTyped(json: any, ignoreDiscriminator: boolean): AmlPolicyMatchIncoming {
    if (json == null) {
        return json;
    }
    return {
        
        'isDefault': json['is_default'],
        'ruleId': json['rule_id'],
        'ruleName': json['rule_name'],
        'actionType': AmlPolicyMatchIncomingActionTypeFromJSON(json['action_type']),
        'amlUnfreezeApprovalRequest': json['aml_unfreeze_approval_request'] == null ? undefined : AmlUnfreezeApprovalRequestFromJSON(json['aml_unfreeze_approval_request']),
    };
}

export function AmlPolicyMatchIncomingToJSON(json: any): AmlPolicyMatchIncoming {
    return AmlPolicyMatchIncomingToJSONTyped(json, false);
}

export function AmlPolicyMatchIncomingToJSONTyped(value?: AmlPolicyMatchIncoming | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_default': value['isDefault'],
        'rule_id': value['ruleId'],
        'rule_name': value['ruleName'],
        'action_type': AmlPolicyMatchIncomingActionTypeToJSON(value['actionType']),
        'aml_unfreeze_approval_request': AmlUnfreezeApprovalRequestToJSON(value['amlUnfreezeApprovalRequest']),
    };
}

