/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AmlScanStatus } from './AmlScanStatus';
import {
    AmlScanStatusFromJSON,
} from './AmlScanStatus';
import type { AmlResultsScanResults } from './AmlResultsScanResults';
import {
    AmlResultsScanResultsFromJSON,
} from './AmlResultsScanResults';

/**
 * 
 * @export
 * @interface AmlResults
 */
export interface AmlResults {
    /**
     * 
     * @type {AmlScanStatus}
     * @memberof AmlResults
     */
    scanStatus: AmlScanStatus;
    /**
     * 
     * @type {string}
     * @memberof AmlResults
     */
    errorMessage?: string;
    /**
     * 
     * @type {AmlResultsScanResults}
     * @memberof AmlResults
     */
    scanResults?: AmlResultsScanResults;
}

export function AmlResultsFromJSON(json: any): AmlResults {
    return AmlResultsFromJSONTyped(json, false);
}

function AmlResultsFromJSONTyped(json: any, _ignoreDiscriminator: boolean): AmlResults {
    if (json == null) {
        return json;
    }
    return {
        
        'scanStatus': AmlScanStatusFromJSON(json['scan_status']),
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'scanResults': json['scan_results'] == null ? undefined : AmlResultsScanResultsFromJSON(json['scan_results']),
    };
}

