/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApiKeyType = {
    standard: 'standard',
    test: 'test'
} as const;
export type ApiKeyType = typeof ApiKeyType[keyof typeof ApiKeyType];


export function instanceOfApiKeyType(value: any): boolean {
    for (const key in ApiKeyType) {
        if (Object.prototype.hasOwnProperty.call(ApiKeyType, key)) {
            if (ApiKeyType[key as keyof typeof ApiKeyType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApiKeyTypeFromJSON(json: any): ApiKeyType {
    return ApiKeyTypeFromJSONTyped(json, false);
}

export function ApiKeyTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyType {
    return json as ApiKeyType;
}

export function ApiKeyTypeToJSON(value?: ApiKeyType | null): any {
    return value as any;
}

export function ApiKeyTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ApiKeyType {
    return value as ApiKeyType;
}

