/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApprovalState = {
    pending: 'pending',
    approved: 'approved',
    unauthorized: 'unauthorized',
    notParticipated: 'not_participated'
} as const;
export type ApprovalState = typeof ApprovalState[keyof typeof ApprovalState];


export function instanceOfApprovalState(value: any): boolean {
    for (const key in ApprovalState) {
        if (Object.prototype.hasOwnProperty.call(ApprovalState, key)) {
            if (ApprovalState[key as keyof typeof ApprovalState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ApprovalStateFromJSON(json: any): ApprovalState {
    return ApprovalStateFromJSONTyped(json, false);
}

export function ApprovalStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApprovalState {
    return json as ApprovalState;
}

export function ApprovalStateToJSON(value?: ApprovalState | null): any {
    return value as any;
}

export function ApprovalStateToJSONTyped(value: any, ignoreDiscriminator: boolean): ApprovalState {
    return value as ApprovalState;
}

