/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ApproveTransactionErrorType = {
    invalidTransactionState: 'invalid_transaction_state',
    nonManagedTransaction: 'non_managed_transaction'
} as const;
export type ApproveTransactionErrorType = typeof ApproveTransactionErrorType[keyof typeof ApproveTransactionErrorType];


export function ApproveTransactionErrorTypeFromJSON(json: any): ApproveTransactionErrorType {
    return ApproveTransactionErrorTypeFromJSONTyped(json, false);
}

export function ApproveTransactionErrorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApproveTransactionErrorType {
    return json as ApproveTransactionErrorType;
}

export function ApproveTransactionErrorTypeToJSON(value?: ApproveTransactionErrorType | null): any {
    return value as any;
}

