/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EnrichedAptosChain } from './EnrichedAptosChain';
import {
    EnrichedAptosChainFromJSON,
} from './EnrichedAptosChain';
import type { ManagedTransactionData } from './ManagedTransactionData';
import {
    ManagedTransactionDataFromJSON,
} from './ManagedTransactionData';
import type { AptosGasData } from './AptosGasData';
import {
    AptosGasDataFromJSON,
} from './AptosGasData';
import type { AptosTransactionResult } from './AptosTransactionResult';
import {
    AptosTransactionResultFromJSON,
} from './AptosTransactionResult';
import type { AptosTransactionAptosTransactionTypeDetails } from './AptosTransactionAptosTransactionTypeDetails';
import {
    AptosTransactionAptosTransactionTypeDetailsFromJSON,
} from './AptosTransactionAptosTransactionTypeDetails';
import type { PushableTransactionStateChange } from './PushableTransactionStateChange';
import {
    PushableTransactionStateChangeFromJSON,
} from './PushableTransactionStateChange';
import type { EnrichedAptosAddress } from './EnrichedAptosAddress';
import {
    EnrichedAptosAddressFromJSON,
} from './EnrichedAptosAddress';
import type { PushableTransactionState } from './PushableTransactionState';
import {
    PushableTransactionStateFromJSON,
} from './PushableTransactionState';
import type { MinedResultStatus } from './MinedResultStatus';
import {
    MinedResultStatusFromJSON,
} from './MinedResultStatus';
import type { VaultRef } from './VaultRef';
import {
    VaultRefFromJSON,
} from './VaultRef';
import type { TransactionSpamState } from './TransactionSpamState';
import {
    TransactionSpamStateFromJSON,
} from './TransactionSpamState';
import type { AptosTransactionPayload } from './AptosTransactionPayload';
import {
    AptosTransactionPayloadFromJSON,
} from './AptosTransactionPayload';
import type { TransactionDirection } from './TransactionDirection';
import {
    TransactionDirectionFromJSON,
} from './TransactionDirection';
import type { AmlCheck } from './AmlCheck';
import {
    AmlCheckFromJSON,
} from './AmlCheck';
import type { Signature } from './Signature';
import {
    SignatureFromJSON,
} from './Signature';
import type { RelatedTransaction } from './RelatedTransaction';
import {
    RelatedTransactionFromJSON,
} from './RelatedTransaction';
import type { SimulationStatusResult } from './SimulationStatusResult';
import {
    SimulationStatusResultFromJSON,
} from './SimulationStatusResult';
import type { Block } from './Block';
import {
    BlockFromJSON,
} from './Block';

/**
 * 
 * @export
 * @interface AptosTransaction
 */
export interface AptosTransaction {
    /**
     * 
     * @type {string}
     * @memberof AptosTransaction
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof AptosTransaction
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AptosTransaction
     */
    modifiedAt: Date;
    /**
     * 
     * @type {ManagedTransactionData}
     * @memberof AptosTransaction
     */
    managedTransactionData?: ManagedTransactionData;
    /**
     * 
     * @type {Array<Signature>}
     * @memberof AptosTransaction
     */
    signatures: Array<Signature>;
    /**
     * 
     * @type {string}
     * @memberof AptosTransaction
     */
    note?: string;
    /**
     * 
     * @type {TransactionSpamState}
     * @memberof AptosTransaction
     */
    spamState?: TransactionSpamState;
    /**
     * 
     * @type {TransactionDirection}
     * @memberof AptosTransaction
     */
    direction: TransactionDirection;
    /**
     * 
     * @type {boolean}
     * @memberof AptosTransaction
     */
    signedExternally?: boolean;
    /**
     * 
     * @type {Array<VaultRef>}
     * @memberof AptosTransaction
     */
    interactedVaults: Array<VaultRef>;
    /**
     * 
     * @type {Array<RelatedTransaction>}
     * @memberof AptosTransaction
     */
    relatedTransactions?: Array<RelatedTransaction>;
    /**
     * 
     * @type {string}
     * @memberof AptosTransaction
     */
    organizationId: string;
    /**
     * 
     * @type {Block}
     * @memberof AptosTransaction
     */
    block?: Block;
    /**
     * 
     * @type {PushableTransactionState}
     * @memberof AptosTransaction
     */
    state: PushableTransactionState;
    /**
     * 
     * @type {Array<PushableTransactionStateChange>}
     * @memberof AptosTransaction
     */
    stateChanges: Array<PushableTransactionStateChange>;
    /**
     * 
     * @type {AmlCheck}
     * @memberof AptosTransaction
     */
    amlCheck?: AmlCheck;
    /**
     * 
     * @type {MinedResultStatus}
     * @memberof AptosTransaction
     */
    minedResultStatus?: MinedResultStatus;
    /**
     * 
     * @type {SimulationStatusResult}
     * @memberof AptosTransaction
     */
    simulationStatusResult?: SimulationStatusResult;
    /**
     * 
     * @type {string}
     * @memberof AptosTransaction
     */
    type: AptosTransactionTypeEnum;
    /**
     * 
     * @type {AptosTransactionAptosTransactionTypeDetails}
     * @memberof AptosTransaction
     */
    aptosTransactionTypeDetails: AptosTransactionAptosTransactionTypeDetails;
    /**
     * 
     * @type {EnrichedAptosChain}
     * @memberof AptosTransaction
     */
    chain: EnrichedAptosChain;
    /**
     * 
     * @type {number}
     * @memberof AptosTransaction
     */
    version?: number;
    /**
     * 
     * @type {number}
     * @memberof AptosTransaction
     */
    nonce?: number;
    /**
     * 
     * @type {EnrichedAptosAddress}
     * @memberof AptosTransaction
     */
    sender: EnrichedAptosAddress;
    /**
     * 
     * @type {AptosTransactionPayload}
     * @memberof AptosTransaction
     */
    payload: AptosTransactionPayload;
    /**
     * 
     * @type {string}
     * @memberof AptosTransaction
     */
    hash?: string;
    /**
     * 
     * @type {AptosGasData}
     * @memberof AptosTransaction
     */
    gasSubmitted: AptosGasData;
    /**
     * 
     * @type {boolean}
     * @memberof AptosTransaction
     */
    withExternalFeePayer?: boolean;
    /**
     * 
     * @type {EnrichedAptosAddress}
     * @memberof AptosTransaction
     */
    feePayer?: EnrichedAptosAddress;
    /**
     * 
     * @type {string}
     * @memberof AptosTransaction
     */
    serializedSignedTransaction?: string;
    /**
     * 
     * @type {AptosTransactionResult}
     * @memberof AptosTransaction
     */
    expectedResult?: AptosTransactionResult;
    /**
     * 
     * @type {AptosTransactionResult}
     * @memberof AptosTransaction
     */
    minedResult?: AptosTransactionResult;
    /**
     * 
     * @type {string}
     * @memberof AptosTransaction
     */
    explorerUrl?: string;
}


/**
 * 
 */
const AptosTransactionTypeEnum = {
    aptosTransaction: 'aptos_transaction'
} as const;
type AptosTransactionTypeEnum = typeof AptosTransactionTypeEnum[keyof typeof AptosTransactionTypeEnum];

export function AptosTransactionFromJSONTyped(json: any, _ignoreDiscriminator: boolean): AptosTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'modifiedAt': (new Date(json['modified_at'])),
        'managedTransactionData': json['managed_transaction_data'] == null ? undefined : ManagedTransactionDataFromJSON(json['managed_transaction_data']),
        'signatures': ((json['signatures'] as Array<any>).map(SignatureFromJSON)),
        'note': json['note'] == null ? undefined : json['note'],
        'spamState': json['spam_state'] == null ? undefined : TransactionSpamStateFromJSON(json['spam_state']),
        'direction': TransactionDirectionFromJSON(json['direction']),
        'signedExternally': json['signed_externally'] == null ? undefined : json['signed_externally'],
        'interactedVaults': ((json['interacted_vaults'] as Array<any>).map(VaultRefFromJSON)),
        'relatedTransactions': json['related_transactions'] == null ? undefined : ((json['related_transactions'] as Array<any>).map(RelatedTransactionFromJSON)),
        'organizationId': json['organization_id'],
        'block': json['block'] == null ? undefined : BlockFromJSON(json['block']),
        'state': PushableTransactionStateFromJSON(json['state']),
        'stateChanges': ((json['state_changes'] as Array<any>).map(PushableTransactionStateChangeFromJSON)),
        'amlCheck': json['aml_check'] == null ? undefined : AmlCheckFromJSON(json['aml_check']),
        'minedResultStatus': json['mined_result_status'] == null ? undefined : MinedResultStatusFromJSON(json['mined_result_status']),
        'simulationStatusResult': json['simulation_status_result'] == null ? undefined : SimulationStatusResultFromJSON(json['simulation_status_result']),
        'type': json['type'],
        'aptosTransactionTypeDetails': AptosTransactionAptosTransactionTypeDetailsFromJSON(json['aptos_transaction_type_details']),
        'chain': EnrichedAptosChainFromJSON(json['chain']),
        'version': json['version'] == null ? undefined : json['version'],
        'nonce': json['nonce'] == null ? undefined : json['nonce'],
        'sender': EnrichedAptosAddressFromJSON(json['sender']),
        'payload': AptosTransactionPayloadFromJSON(json['payload']),
        'hash': json['hash'] == null ? undefined : json['hash'],
        'gasSubmitted': AptosGasDataFromJSON(json['gas_submitted']),
        'withExternalFeePayer': json['with_external_fee_payer'] == null ? undefined : json['with_external_fee_payer'],
        'feePayer': json['fee_payer'] == null ? undefined : EnrichedAptosAddressFromJSON(json['fee_payer']),
        'serializedSignedTransaction': json['serialized_signed_transaction'] == null ? undefined : json['serialized_signed_transaction'],
        'expectedResult': json['expected_result'] == null ? undefined : AptosTransactionResultFromJSON(json['expected_result']),
        'minedResult': json['mined_result'] == null ? undefined : AptosTransactionResultFromJSON(json['mined_result']),
        'explorerUrl': json['explorer_url'] == null ? undefined : json['explorer_url'],
    };
}
