/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PricedAsset } from './PricedAsset';
import {
    PricedAssetFromJSON,
} from './PricedAsset';
import type { AptosTransferEffectType } from './AptosTransferEffectType';
import {
    AptosTransferEffectTypeFromJSON,
} from './AptosTransferEffectType';
import type { EnrichedAptosAddress } from './EnrichedAptosAddress';
import {
    EnrichedAptosAddressFromJSON,
} from './EnrichedAptosAddress';

/**
 * 
 * @export
 * @interface AptosTransferEffect
 */
export interface AptosTransferEffect {
    /**
     * 
     * @type {PricedAsset}
     * @memberof AptosTransferEffect
     */
    pricedAsset: PricedAsset;
    /**
     * 
     * @type {string}
     * @memberof AptosTransferEffect
     */
    amount: string;
    /**
     * 
     * @type {AptosTransferEffectType}
     * @memberof AptosTransferEffect
     */
    type: AptosTransferEffectType;
    /**
     * 
     * @type {EnrichedAptosAddress}
     * @memberof AptosTransferEffect
     */
    from: EnrichedAptosAddress;
    /**
     * 
     * @type {EnrichedAptosAddress}
     * @memberof AptosTransferEffect
     */
    to: EnrichedAptosAddress;
}

export function AptosTransferEffectFromJSON(json: any): AptosTransferEffect {
    return AptosTransferEffectFromJSONTyped(json, false);
}

function AptosTransferEffectFromJSONTyped(json: any, _ignoreDiscriminator: boolean): AptosTransferEffect {
    if (json == null) {
        return json;
    }
    return {
        
        'pricedAsset': PricedAssetFromJSON(json['priced_asset']),
        'amount': json['amount'],
        'type': AptosTransferEffectTypeFromJSON(json['type']),
        'from': EnrichedAptosAddressFromJSON(json['from']),
        'to': EnrichedAptosAddressFromJSON(json['to']),
    };
}

