/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ArchTransactionArchTransactionTypeDetails } from './ArchTransactionArchTransactionTypeDetails';
import {
    ArchTransactionArchTransactionTypeDetailsFromJSON,
} from './ArchTransactionArchTransactionTypeDetails';
import type { ManagedTransactionData } from './ManagedTransactionData';
import {
    ManagedTransactionDataFromJSON,
} from './ManagedTransactionData';
import type { ArchTransactionAccount } from './ArchTransactionAccount';
import {
    ArchTransactionAccountFromJSON,
} from './ArchTransactionAccount';
import type { PushableTransactionStateChange } from './PushableTransactionStateChange';
import {
    PushableTransactionStateChangeFromJSON,
} from './PushableTransactionStateChange';
import type { EnrichedArchChain } from './EnrichedArchChain';
import {
    EnrichedArchChainFromJSON,
} from './EnrichedArchChain';
import type { PushableTransactionState } from './PushableTransactionState';
import {
    PushableTransactionStateFromJSON,
} from './PushableTransactionState';
import type { ArchTransactionResult } from './ArchTransactionResult';
import {
    ArchTransactionResultFromJSON,
} from './ArchTransactionResult';
import type { MinedResultStatus } from './MinedResultStatus';
import {
    MinedResultStatusFromJSON,
} from './MinedResultStatus';
import type { VaultRef } from './VaultRef';
import {
    VaultRefFromJSON,
} from './VaultRef';
import type { TransactionSpamState } from './TransactionSpamState';
import {
    TransactionSpamStateFromJSON,
} from './TransactionSpamState';
import type { TransactionDirection } from './TransactionDirection';
import {
    TransactionDirectionFromJSON,
} from './TransactionDirection';
import type { AmlCheck } from './AmlCheck';
import {
    AmlCheckFromJSON,
} from './AmlCheck';
import type { ArchCompiledInstruction } from './ArchCompiledInstruction';
import {
    ArchCompiledInstructionFromJSON,
} from './ArchCompiledInstruction';
import type { Signature } from './Signature';
import {
    SignatureFromJSON,
} from './Signature';
import type { RelatedTransaction } from './RelatedTransaction';
import {
    RelatedTransactionFromJSON,
} from './RelatedTransaction';
import type { SimulationStatusResult } from './SimulationStatusResult';
import {
    SimulationStatusResultFromJSON,
} from './SimulationStatusResult';
import type { Block } from './Block';
import {
    BlockFromJSON,
} from './Block';
import type { EnrichedArchAddress } from './EnrichedArchAddress';
import {
    EnrichedArchAddressFromJSON,
} from './EnrichedArchAddress';

/**
 * 
 * @export
 * @interface ArchTransaction
 */
export interface ArchTransaction {
    /**
     * 
     * @type {string}
     * @memberof ArchTransaction
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof ArchTransaction
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ArchTransaction
     */
    modifiedAt: Date;
    /**
     * 
     * @type {ManagedTransactionData}
     * @memberof ArchTransaction
     */
    managedTransactionData?: ManagedTransactionData;
    /**
     * 
     * @type {Array<Signature>}
     * @memberof ArchTransaction
     */
    signatures: Array<Signature>;
    /**
     * 
     * @type {string}
     * @memberof ArchTransaction
     */
    note?: string;
    /**
     * 
     * @type {TransactionSpamState}
     * @memberof ArchTransaction
     */
    spamState?: TransactionSpamState;
    /**
     * 
     * @type {TransactionDirection}
     * @memberof ArchTransaction
     */
    direction: TransactionDirection;
    /**
     * 
     * @type {boolean}
     * @memberof ArchTransaction
     */
    signedExternally?: boolean;
    /**
     * 
     * @type {Array<VaultRef>}
     * @memberof ArchTransaction
     */
    interactedVaults: Array<VaultRef>;
    /**
     * 
     * @type {Array<RelatedTransaction>}
     * @memberof ArchTransaction
     */
    relatedTransactions?: Array<RelatedTransaction>;
    /**
     * 
     * @type {string}
     * @memberof ArchTransaction
     */
    organizationId: string;
    /**
     * 
     * @type {Block}
     * @memberof ArchTransaction
     */
    block?: Block;
    /**
     * 
     * @type {PushableTransactionState}
     * @memberof ArchTransaction
     */
    state: PushableTransactionState;
    /**
     * 
     * @type {Array<PushableTransactionStateChange>}
     * @memberof ArchTransaction
     */
    stateChanges: Array<PushableTransactionStateChange>;
    /**
     * 
     * @type {AmlCheck}
     * @memberof ArchTransaction
     */
    amlCheck?: AmlCheck;
    /**
     * 
     * @type {MinedResultStatus}
     * @memberof ArchTransaction
     */
    minedResultStatus?: MinedResultStatus;
    /**
     * 
     * @type {SimulationStatusResult}
     * @memberof ArchTransaction
     */
    simulationStatusResult?: SimulationStatusResult;
    /**
     * 
     * @type {string}
     * @memberof ArchTransaction
     */
    type: ArchTransactionTypeEnum;
    /**
     * 
     * @type {ArchTransactionArchTransactionTypeDetails}
     * @memberof ArchTransaction
     */
    archTransactionTypeDetails: ArchTransactionArchTransactionTypeDetails;
    /**
     * 
     * @type {EnrichedArchChain}
     * @memberof ArchTransaction
     */
    chain: EnrichedArchChain;
    /**
     * 
     * @type {Array<ArchCompiledInstruction>}
     * @memberof ArchTransaction
     */
    instructions: Array<ArchCompiledInstruction>;
    /**
     * 
     * @type {Array<ArchTransactionAccount>}
     * @memberof ArchTransaction
     */
    accounts: Array<ArchTransactionAccount>;
    /**
     * 
     * @type {EnrichedArchAddress}
     * @memberof ArchTransaction
     */
    sender: EnrichedArchAddress;
    /**
     * 
     * @type {string}
     * @memberof ArchTransaction
     */
    rawTransaction?: string;
    /**
     * 
     * @type {string}
     * @memberof ArchTransaction
     */
    hash?: string;
    /**
     * 
     * @type {string}
     * @memberof ArchTransaction
     */
    recentBlockhash?: string;
    /**
     * 
     * @type {ArchTransactionResult}
     * @memberof ArchTransaction
     */
    expectedResult?: ArchTransactionResult;
    /**
     * 
     * @type {ArchTransactionResult}
     * @memberof ArchTransaction
     */
    minedResult?: ArchTransactionResult;
    /**
     * 
     * @type {string}
     * @memberof ArchTransaction
     */
    explorerUrl?: string;
}


/**
 * 
 */
const ArchTransactionTypeEnum = {
    archTransaction: 'arch_transaction'
} as const;
type ArchTransactionTypeEnum = typeof ArchTransactionTypeEnum[keyof typeof ArchTransactionTypeEnum];

export function ArchTransactionFromJSONTyped(json: any, _ignoreDiscriminator: boolean): ArchTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'modifiedAt': (new Date(json['modified_at'])),
        'managedTransactionData': json['managed_transaction_data'] == null ? undefined : ManagedTransactionDataFromJSON(json['managed_transaction_data']),
        'signatures': ((json['signatures'] as Array<any>).map(SignatureFromJSON)),
        'note': json['note'] == null ? undefined : json['note'],
        'spamState': json['spam_state'] == null ? undefined : TransactionSpamStateFromJSON(json['spam_state']),
        'direction': TransactionDirectionFromJSON(json['direction']),
        'signedExternally': json['signed_externally'] == null ? undefined : json['signed_externally'],
        'interactedVaults': ((json['interacted_vaults'] as Array<any>).map(VaultRefFromJSON)),
        'relatedTransactions': json['related_transactions'] == null ? undefined : ((json['related_transactions'] as Array<any>).map(RelatedTransactionFromJSON)),
        'organizationId': json['organization_id'],
        'block': json['block'] == null ? undefined : BlockFromJSON(json['block']),
        'state': PushableTransactionStateFromJSON(json['state']),
        'stateChanges': ((json['state_changes'] as Array<any>).map(PushableTransactionStateChangeFromJSON)),
        'amlCheck': json['aml_check'] == null ? undefined : AmlCheckFromJSON(json['aml_check']),
        'minedResultStatus': json['mined_result_status'] == null ? undefined : MinedResultStatusFromJSON(json['mined_result_status']),
        'simulationStatusResult': json['simulation_status_result'] == null ? undefined : SimulationStatusResultFromJSON(json['simulation_status_result']),
        'type': json['type'],
        'archTransactionTypeDetails': ArchTransactionArchTransactionTypeDetailsFromJSON(json['arch_transaction_type_details']),
        'chain': EnrichedArchChainFromJSON(json['chain']),
        'instructions': ((json['instructions'] as Array<any>).map(ArchCompiledInstructionFromJSON)),
        'accounts': ((json['accounts'] as Array<any>).map(ArchTransactionAccountFromJSON)),
        'sender': EnrichedArchAddressFromJSON(json['sender']),
        'rawTransaction': json['raw_transaction'] == null ? undefined : json['raw_transaction'],
        'hash': json['hash'] == null ? undefined : json['hash'],
        'recentBlockhash': json['recent_blockhash'] == null ? undefined : json['recent_blockhash'],
        'expectedResult': json['expected_result'] == null ? undefined : ArchTransactionResultFromJSON(json['expected_result']),
        'minedResult': json['mined_result'] == null ? undefined : ArchTransactionResultFromJSON(json['mined_result']),
        'explorerUrl': json['explorer_url'] == null ? undefined : json['explorer_url'],
    };
}
