/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AlertProviderType } from './AlertProviderType';
import {
    AlertProviderTypeFromJSON,
    AlertProviderTypeFromJSONTyped,
    AlertProviderTypeToJSON,
} from './AlertProviderType';
import type { UserRef } from './UserRef';
import {
    UserRefFromJSON,
    UserRefFromJSONTyped,
    UserRefToJSON,
} from './UserRef';

/**
 * 
 * @export
 * @interface AutoRevokeProtectionSettingsResponse
 */
export interface AutoRevokeProtectionSettingsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AutoRevokeProtectionSettingsResponse
     */
    isActive: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AutoRevokeProtectionSettingsResponse
     */
    shouldSendToApiSigner: boolean;
    /**
     * 
     * @type {Array<AlertProviderType>}
     * @memberof AutoRevokeProtectionSettingsResponse
     */
    alertProviders: Array<AlertProviderType>;
    /**
     * 
     * @type {Array<UserRef>}
     * @memberof AutoRevokeProtectionSettingsResponse
     */
    signers: Array<UserRef>;
}

/**
 * Check if a given object implements the AutoRevokeProtectionSettingsResponse interface.
 */
export function instanceOfAutoRevokeProtectionSettingsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isActive" in value;
    isInstance = isInstance && "shouldSendToApiSigner" in value;
    isInstance = isInstance && "alertProviders" in value;
    isInstance = isInstance && "signers" in value;

    return isInstance;
}

export function AutoRevokeProtectionSettingsResponseFromJSON(json: any): AutoRevokeProtectionSettingsResponse {
    return AutoRevokeProtectionSettingsResponseFromJSONTyped(json, false);
}

export function AutoRevokeProtectionSettingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutoRevokeProtectionSettingsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isActive': json['is_active'],
        'shouldSendToApiSigner': json['should_send_to_api_signer'],
        'alertProviders': ((json['alert_providers'] as Array<any>).map(AlertProviderTypeFromJSON)),
        'signers': ((json['signers'] as Array<any>).map(UserRefFromJSON)),
    };
}

export function AutoRevokeProtectionSettingsResponseToJSON(value?: AutoRevokeProtectionSettingsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'is_active': value.isActive,
        'should_send_to_api_signer': value.shouldSendToApiSigner,
        'alert_providers': ((value.alertProviders as Array<any>).map(AlertProviderTypeToJSON)),
        'signers': ((value.signers as Array<any>).map(UserRefToJSON)),
    };
}

