/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    SuiPureBoolInput,
    instanceOfSuiPureBoolInput,
    SuiPureBoolInputFromJSON,
    SuiPureBoolInputFromJSONTyped,
    SuiPureBoolInputToJSON,
} from './SuiPureBoolInput';
import {
    SuiPureByteArrayInput,
    instanceOfSuiPureByteArrayInput,
    SuiPureByteArrayInputFromJSON,
    SuiPureByteArrayInputFromJSONTyped,
    SuiPureByteArrayInputToJSON,
} from './SuiPureByteArrayInput';
import {
    SuiPureNumberInput,
    instanceOfSuiPureNumberInput,
    SuiPureNumberInputFromJSON,
    SuiPureNumberInputFromJSONTyped,
    SuiPureNumberInputToJSON,
} from './SuiPureNumberInput';
import {
    SuiPureStringInput,
    instanceOfSuiPureStringInput,
    SuiPureStringInputFromJSON,
    SuiPureStringInputFromJSONTyped,
    SuiPureStringInputToJSON,
} from './SuiPureStringInput';

/**
 * @type BaseSuiPureInputValue
 * 
 * @export
 */
export type BaseSuiPureInputValue = { type: 'bool_pure_input' } & SuiPureBoolInput | { type: 'byte_array_pure_input' } & SuiPureByteArrayInput | { type: 'number_pure_input' } & SuiPureNumberInput | { type: 'string_pure_input' } & SuiPureStringInput;

export function BaseSuiPureInputValueFromJSON(json: any): BaseSuiPureInputValue {
    return BaseSuiPureInputValueFromJSONTyped(json, false);
}

export function BaseSuiPureInputValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseSuiPureInputValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'bool_pure_input':
            return {...SuiPureBoolInputFromJSONTyped(json, true), type: 'bool_pure_input'};
        case 'byte_array_pure_input':
            return {...SuiPureByteArrayInputFromJSONTyped(json, true), type: 'byte_array_pure_input'};
        case 'number_pure_input':
            return {...SuiPureNumberInputFromJSONTyped(json, true), type: 'number_pure_input'};
        case 'string_pure_input':
            return {...SuiPureStringInputFromJSONTyped(json, true), type: 'string_pure_input'};
        default:
            throw new Error(`No variant of BaseSuiPureInputValue exists with 'type=${json['type']}'`);
    }
}

export function BaseSuiPureInputValueToJSON(value?: BaseSuiPureInputValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'bool_pure_input':
            return SuiPureBoolInputToJSON(value);
        case 'byte_array_pure_input':
            return SuiPureByteArrayInputToJSON(value);
        case 'number_pure_input':
            return SuiPureNumberInputToJSON(value);
        case 'string_pure_input':
            return SuiPureStringInputToJSON(value);
        default:
            throw new Error(`No variant of BaseSuiPureInputValue exists with 'type=${value['type']}'`);
    }

}

