/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EcdsaSignature } from './EcdsaSignature';
import {
    EcdsaSignatureFromJSON,
} from './EcdsaSignature';

/**
 * 
 * @export
 * @interface BlackBoxSignatureEcdsaStarkDetails
 */
export interface BlackBoxSignatureEcdsaStarkDetails {
    /**
     * ECDSA over the Stark curve signature.
     * @type {BlackBoxSignatureEcdsaStarkDetailsTypeEnum}
     * @memberof BlackBoxSignatureEcdsaStarkDetails
     */
    type: BlackBoxSignatureEcdsaStarkDetailsTypeEnum;
    /**
     * The ECDSA signature over the Stark curve.
     * @type {EcdsaSignature}
     * @memberof BlackBoxSignatureEcdsaStarkDetails
     */
    signature?: EcdsaSignature;
    /**
     * The payload to sign, encoded in base64 format. 
     * @type {string}
     * @memberof BlackBoxSignatureEcdsaStarkDetails
     */
    hashBinary: string;
    /**
     * The payload to sign, as a big-endian integer.
     * @type {string}
     * @memberof BlackBoxSignatureEcdsaStarkDetails
     * @deprecated
     */
    hashInteger: string;
}


/**
 * @export
 */
const BlackBoxSignatureEcdsaStarkDetailsTypeEnum = {
    ecdsaStark: 'ecdsa_stark'
} as const;
type BlackBoxSignatureEcdsaStarkDetailsTypeEnum = typeof BlackBoxSignatureEcdsaStarkDetailsTypeEnum[keyof typeof BlackBoxSignatureEcdsaStarkDetailsTypeEnum];

export function BlackBoxSignatureEcdsaStarkDetailsFromJSONTyped(json: any, _ignoreDiscriminator: boolean): BlackBoxSignatureEcdsaStarkDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'signature': json['signature'] == null ? undefined : EcdsaSignatureFromJSON(json['signature']),
        'hashBinary': json['hash_binary'],
        'hashInteger': json['hash_integer'],
    };
}
