/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SolanaCompiledInstruction } from './SolanaCompiledInstruction';
import {
    SolanaCompiledInstructionFromJSON,
    SolanaCompiledInstructionFromJSONTyped,
    SolanaCompiledInstructionToJSON,
} from './SolanaCompiledInstruction';
import type { SolanaMessageAddressTableLookupRequest } from './SolanaMessageAddressTableLookupRequest';
import {
    SolanaMessageAddressTableLookupRequestFromJSON,
    SolanaMessageAddressTableLookupRequestFromJSONTyped,
    SolanaMessageAddressTableLookupRequestToJSON,
} from './SolanaMessageAddressTableLookupRequest';
import type { SolanaMessageVersion } from './SolanaMessageVersion';
import {
    SolanaMessageVersionFromJSON,
    SolanaMessageVersionFromJSONTyped,
    SolanaMessageVersionToJSON,
} from './SolanaMessageVersion';
import type { SolanaTransactionAccountRequest } from './SolanaTransactionAccountRequest';
import {
    SolanaTransactionAccountRequestFromJSON,
    SolanaTransactionAccountRequestFromJSONTyped,
    SolanaTransactionAccountRequestToJSON,
} from './SolanaTransactionAccountRequest';
import type { SolanaTransactionSignaturesRequest } from './SolanaTransactionSignaturesRequest';
import {
    SolanaTransactionSignaturesRequestFromJSON,
    SolanaTransactionSignaturesRequestFromJSONTyped,
    SolanaTransactionSignaturesRequestToJSON,
} from './SolanaTransactionSignaturesRequest';

/**
 * 
 * @export
 * @interface BulkCreateTransactionInstanceDetails
 */
export interface BulkCreateTransactionInstanceDetails {
    /**
     * 
     * @type {SolanaMessageVersion}
     * @memberof BulkCreateTransactionInstanceDetails
     */
    version: SolanaMessageVersion;
    /**
     * 
     * @type {Array<SolanaCompiledInstruction>}
     * @memberof BulkCreateTransactionInstanceDetails
     */
    instructions: Array<SolanaCompiledInstruction>;
    /**
     * 
     * @type {Array<SolanaTransactionAccountRequest>}
     * @memberof BulkCreateTransactionInstanceDetails
     */
    accounts: Array<SolanaTransactionAccountRequest>;
    /**
     * 
     * @type {Array<SolanaMessageAddressTableLookupRequest>}
     * @memberof BulkCreateTransactionInstanceDetails
     */
    addressTableLookups: Array<SolanaMessageAddressTableLookupRequest>;
    /**
     * 
     * @type {Array<SolanaTransactionSignaturesRequest>}
     * @memberof BulkCreateTransactionInstanceDetails
     */
    signatures?: Array<SolanaTransactionSignaturesRequest>;
    /**
     * 
     * @type {string}
     * @memberof BulkCreateTransactionInstanceDetails
     */
    recentBlockhash?: string;
}

/**
 * Check if a given object implements the BulkCreateTransactionInstanceDetails interface.
 */
export function instanceOfBulkCreateTransactionInstanceDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "version" in value;
    isInstance = isInstance && "instructions" in value;
    isInstance = isInstance && "accounts" in value;
    isInstance = isInstance && "addressTableLookups" in value;

    return isInstance;
}

export function BulkCreateTransactionInstanceDetailsFromJSON(json: any): BulkCreateTransactionInstanceDetails {
    return BulkCreateTransactionInstanceDetailsFromJSONTyped(json, false);
}

export function BulkCreateTransactionInstanceDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkCreateTransactionInstanceDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': SolanaMessageVersionFromJSON(json['version']),
        'instructions': ((json['instructions'] as Array<any>).map(SolanaCompiledInstructionFromJSON)),
        'accounts': ((json['accounts'] as Array<any>).map(SolanaTransactionAccountRequestFromJSON)),
        'addressTableLookups': ((json['address_table_lookups'] as Array<any>).map(SolanaMessageAddressTableLookupRequestFromJSON)),
        'signatures': !exists(json, 'signatures') ? undefined : ((json['signatures'] as Array<any>).map(SolanaTransactionSignaturesRequestFromJSON)),
        'recentBlockhash': !exists(json, 'recent_blockhash') ? undefined : json['recent_blockhash'],
    };
}

export function BulkCreateTransactionInstanceDetailsToJSON(value?: BulkCreateTransactionInstanceDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': SolanaMessageVersionToJSON(value.version),
        'instructions': ((value.instructions as Array<any>).map(SolanaCompiledInstructionToJSON)),
        'accounts': ((value.accounts as Array<any>).map(SolanaTransactionAccountRequestToJSON)),
        'address_table_lookups': ((value.addressTableLookups as Array<any>).map(SolanaMessageAddressTableLookupRequestToJSON)),
        'signatures': value.signatures === undefined ? undefined : ((value.signatures as Array<any>).map(SolanaTransactionSignaturesRequestToJSON)),
        'recent_blockhash': value.recentBlockhash,
    };
}

