/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ChainalysisAlert } from './ChainalysisAlert';
import {
    ChainalysisAlertFromJSON,
} from './ChainalysisAlert';

/**
 * 
 * @export
 * @interface ChainalysisScanResult
 */
export interface ChainalysisScanResult {
    /**
     * The type of the policy.
     * @type {ChainalysisScanResultTypeEnum}
     * @memberof ChainalysisScanResult
     */
    type: ChainalysisScanResultTypeEnum;
    /**
     * The list of alerts.
     * @type {Array<ChainalysisAlert>}
     * @memberof ChainalysisScanResult
     */
    alerts: Array<ChainalysisAlert>;
    /**
     * A unique identifier of the scan.
     * @type {string}
     * @memberof ChainalysisScanResult
     */
    externalId: string;
}


/**
 * 
 */
const ChainalysisScanResultTypeEnum = {
    Chainalysis: 'chainalysis'
} as const;
type ChainalysisScanResultTypeEnum = typeof ChainalysisScanResultTypeEnum[keyof typeof ChainalysisScanResultTypeEnum];

export function ChainalysisScanResultFromJSON(json: any): ChainalysisScanResult {
    return ChainalysisScanResultFromJSONTyped(json, false);
}

function ChainalysisScanResultFromJSONTyped(json: any, _ignoreDiscriminator: boolean): ChainalysisScanResult {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'alerts': ((json['alerts'] as Array<any>).map(ChainalysisAlertFromJSON)),
        'externalId': json['external_id'],
    };
}
