/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CosmosToken } from './CosmosToken';
import {
    CosmosTokenFromJSON,
    CosmosTokenFromJSONTyped,
    CosmosTokenToJSON,
} from './CosmosToken';

/**
 * 
 * @export
 * @interface CosmosTokenInfo
 */
export interface CosmosTokenInfo {
    /**
     * 
     * @type {boolean}
     * @memberof CosmosTokenInfo
     */
    isVerified: boolean;
    /**
     * 
     * @type {CosmosToken}
     * @memberof CosmosTokenInfo
     */
    coin: CosmosToken;
}

/**
 * Check if a given object implements the CosmosTokenInfo interface.
 */
export function instanceOfCosmosTokenInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isVerified" in value;
    isInstance = isInstance && "coin" in value;

    return isInstance;
}

export function CosmosTokenInfoFromJSON(json: any): CosmosTokenInfo {
    return CosmosTokenInfoFromJSONTyped(json, false);
}

export function CosmosTokenInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CosmosTokenInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isVerified': json['is_verified'],
        'coin': CosmosTokenFromJSON(json['coin']),
    };
}

export function CosmosTokenInfoToJSON(value?: CosmosTokenInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'is_verified': value.isVerified,
        'coin': CosmosTokenToJSON(value.coin),
    };
}

