/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CosmosNativeCoin } from './CosmosNativeCoin';
import {
    CosmosNativeCoinFromJSON,
    CosmosNativeCoinFromJSONTyped,
    CosmosNativeCoinToJSON,
} from './CosmosNativeCoin';

/**
 * 
 * @export
 * @interface CosmosNativeCoinWithAmount
 */
export interface CosmosNativeCoinWithAmount {
    /**
     * 
     * @type {string}
     * @memberof CosmosNativeCoinWithAmount
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof CosmosNativeCoinWithAmount
     */
    type: CosmosNativeCoinWithAmountTypeEnum;
    /**
     * 
     * @type {CosmosNativeCoin}
     * @memberof CosmosNativeCoinWithAmount
     */
    coin: CosmosNativeCoin;
}


/**
 * @export
 */
export const CosmosNativeCoinWithAmountTypeEnum = {
    native: 'native'
} as const;
export type CosmosNativeCoinWithAmountTypeEnum = typeof CosmosNativeCoinWithAmountTypeEnum[keyof typeof CosmosNativeCoinWithAmountTypeEnum];


/**
 * Check if a given object implements the CosmosNativeCoinWithAmount interface.
 */
export function instanceOfCosmosNativeCoinWithAmount(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "coin" in value;

    return isInstance;
}

export function CosmosNativeCoinWithAmountFromJSON(json: any): CosmosNativeCoinWithAmount {
    return CosmosNativeCoinWithAmountFromJSONTyped(json, false);
}

export function CosmosNativeCoinWithAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): CosmosNativeCoinWithAmount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'type': json['type'],
        'coin': CosmosNativeCoinFromJSON(json['coin']),
    };
}

export function CosmosNativeCoinWithAmountToJSON(value?: CosmosNativeCoinWithAmount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'type': value.type,
        'coin': CosmosNativeCoinToJSON(value.coin),
    };
}

