/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CosmosCoinWithAmountCoinWithAmount } from './CosmosCoinWithAmountCoinWithAmount';
import {
    CosmosCoinWithAmountCoinWithAmountFromJSON,
    CosmosCoinWithAmountCoinWithAmountFromJSONTyped,
    CosmosCoinWithAmountCoinWithAmountToJSON,
    CosmosCoinWithAmountCoinWithAmountToJSONTyped,
} from './CosmosCoinWithAmountCoinWithAmount';

/**
 * 
 * @export
 * @interface CosmosCoinWithAmount
 */
export interface CosmosCoinWithAmount {
    /**
     * 
     * @type {CosmosCoinWithAmountCoinWithAmount}
     * @memberof CosmosCoinWithAmount
     */
    coinWithAmount: CosmosCoinWithAmountCoinWithAmount;
}

/**
 * Check if a given object implements the CosmosCoinWithAmount interface.
 */
export function instanceOfCosmosCoinWithAmount(value: object): value is CosmosCoinWithAmount {
    if (!('coinWithAmount' in value) || value['coinWithAmount'] === undefined) return false;
    return true;
}

export function CosmosCoinWithAmountFromJSON(json: any): CosmosCoinWithAmount {
    return CosmosCoinWithAmountFromJSONTyped(json, false);
}

export function CosmosCoinWithAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): CosmosCoinWithAmount {
    if (json == null) {
        return json;
    }
    return {
        
        'coinWithAmount': CosmosCoinWithAmountCoinWithAmountFromJSON(json['coin_with_amount']),
    };
}

export function CosmosCoinWithAmountToJSON(json: any): CosmosCoinWithAmount {
    return CosmosCoinWithAmountToJSONTyped(json, false);
}

export function CosmosCoinWithAmountToJSONTyped(value?: CosmosCoinWithAmount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coin_with_amount': CosmosCoinWithAmountCoinWithAmountToJSON(value['coinWithAmount']),
    };
}

