/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CosmosBechAddress } from './CosmosBechAddress';
import {
    CosmosBechAddressFromJSON,
    CosmosBechAddressFromJSONTyped,
    CosmosBechAddressToJSON,
    CosmosBechAddressToJSONTyped,
} from './CosmosBechAddress';

/**
 * 
 * @export
 * @interface CosmosTransferToAddressRequest
 */
export interface CosmosTransferToAddressRequest {
    /**
     * 
     * @type {string}
     * @memberof CosmosTransferToAddressRequest
     */
    type: CosmosTransferToAddressRequestTypeEnum;
    /**
     * 
     * @type {CosmosBechAddress}
     * @memberof CosmosTransferToAddressRequest
     */
    address: CosmosBechAddress;
}


/**
 * @export
 */
export const CosmosTransferToAddressRequestTypeEnum = {
    address: 'address'
} as const;
export type CosmosTransferToAddressRequestTypeEnum = typeof CosmosTransferToAddressRequestTypeEnum[keyof typeof CosmosTransferToAddressRequestTypeEnum];


/**
 * Check if a given object implements the CosmosTransferToAddressRequest interface.
 */
export function instanceOfCosmosTransferToAddressRequest(value: object): value is CosmosTransferToAddressRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function CosmosTransferToAddressRequestFromJSON(json: any): CosmosTransferToAddressRequest {
    return CosmosTransferToAddressRequestFromJSONTyped(json, false);
}

export function CosmosTransferToAddressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CosmosTransferToAddressRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'address': CosmosBechAddressFromJSON(json['address']),
    };
}

export function CosmosTransferToAddressRequestToJSON(json: any): CosmosTransferToAddressRequest {
    return CosmosTransferToAddressRequestToJSONTyped(json, false);
}

export function CosmosTransferToAddressRequestToJSONTyped(value?: CosmosTransferToAddressRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'address': CosmosBechAddressToJSON(value['address']),
    };
}

