/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DappInfo } from './DappInfo';
import {
    DappInfoToJSON,
} from './DappInfo';
import type { SignMode } from './SignMode';
import {
    SignModeToJSON,
} from './SignMode';
import type { SignerType } from './SignerType';
import {
    SignerTypeToJSON,
} from './SignerType';
import type { CreateSuiTransactionRequestDetails } from './CreateSuiTransactionRequestDetails';
import {
    CreateSuiTransactionRequestDetailsToJSON,
} from './CreateSuiTransactionRequestDetails';

/**
 * 
 * @export
 * @interface CreateSuiTransactionRequest
 */
export interface CreateSuiTransactionRequest {
    /**
     * The unique identifier of the vault.
     * @type {string}
     * @memberof CreateSuiTransactionRequest
     */
    vaultId: string;
    /**
     * An optional transaction note.
     * @type {string}
     * @memberof CreateSuiTransactionRequest
     */
    note?: string;
    /**
     * The signer of the transaction. Can be: <ul><li>`initiator`: The creator of the transaction (default).<li>`api_signer`: A service that you run on your own network or cloud environment. <li>`end_user`: A mobile device using Fordefi's SDK.</ul>
     * @type {SignerType}
     * @memberof CreateSuiTransactionRequest
     */
    signerType?: SignerType;
    /**
     * The sign mode of the transaction determines when the transaction will transition to the signing phase. It can be one of the following:<ul><li>`auto`: The transaction will move to signing automatically after approval.<li>`triggered`: The transaction will be in the `waiting_for_signing_trigger` state until "Trigger Transaction Signing" is called. Currently supported only for API Signer signer type.</ul>
     * @type {SignMode}
     * @memberof CreateSuiTransactionRequest
     */
    signMode?: SignMode;
    /**
     * The DApp information.
     * @type {DappInfo}
     * @memberof CreateSuiTransactionRequest
     */
    dappInfo?: DappInfo;
    /**
     * Sui transaction type.
     * @type {CreateSuiTransactionRequestTypeEnum}
     * @memberof CreateSuiTransactionRequest
     */
    type: CreateSuiTransactionRequestTypeEnum;
    /**
     * 
     * @type {CreateSuiTransactionRequestDetails}
     * @memberof CreateSuiTransactionRequest
     */
    details: CreateSuiTransactionRequestDetails;
}


/**
 * 
 */
const CreateSuiTransactionRequestTypeEnum = {
    suiTransaction: 'sui_transaction'
} as const;
type CreateSuiTransactionRequestTypeEnum = typeof CreateSuiTransactionRequestTypeEnum[keyof typeof CreateSuiTransactionRequestTypeEnum];

export function CreateSuiTransactionRequestToJSON(json: any): CreateSuiTransactionRequest {
    return CreateSuiTransactionRequestToJSONTyped(json, false);
}

function CreateSuiTransactionRequestToJSONTyped(value?: CreateSuiTransactionRequest | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vault_id': value['vaultId'],
        'note': value['note'],
        'signer_type': SignerTypeToJSON(value['signerType']),
        'sign_mode': SignModeToJSON(value['signMode']),
        'dapp_info': DappInfoToJSON(value['dappInfo']),
        'type': value['type'],
        'details': CreateSuiTransactionRequestDetailsToJSON(value['details']),
    };
}
