/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    TransactionDetailsUtxoPsbtRequest,
    instanceOfTransactionDetailsUtxoPsbtRequest,
    TransactionDetailsUtxoPsbtRequestFromJSON,
    TransactionDetailsUtxoPsbtRequestFromJSONTyped,
    TransactionDetailsUtxoPsbtRequestToJSON,
} from './TransactionDetailsUtxoPsbtRequest';
import {
    TransactionDetailsUtxoTransferRequest,
    instanceOfTransactionDetailsUtxoTransferRequest,
    TransactionDetailsUtxoTransferRequestFromJSON,
    TransactionDetailsUtxoTransferRequestFromJSONTyped,
    TransactionDetailsUtxoTransferRequestToJSON,
} from './TransactionDetailsUtxoTransferRequest';

/**
 * @type CreateUtxoTransactionRequestDetails
 * 
 * @export
 */
export type CreateUtxoTransactionRequestDetails = { type: 'utxo_partially_signed_bitcoin_transaction' } & TransactionDetailsUtxoPsbtRequest | { type: 'utxo_transfer' } & TransactionDetailsUtxoTransferRequest;

export function CreateUtxoTransactionRequestDetailsFromJSON(json: any): CreateUtxoTransactionRequestDetails {
    return CreateUtxoTransactionRequestDetailsFromJSONTyped(json, false);
}

export function CreateUtxoTransactionRequestDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUtxoTransactionRequestDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'utxo_partially_signed_bitcoin_transaction':
            return {...TransactionDetailsUtxoPsbtRequestFromJSONTyped(json, true), type: 'utxo_partially_signed_bitcoin_transaction'};
        case 'utxo_transfer':
            return {...TransactionDetailsUtxoTransferRequestFromJSONTyped(json, true), type: 'utxo_transfer'};
        default:
            throw new Error(`No variant of CreateUtxoTransactionRequestDetails exists with 'type=${json['type']}'`);
    }
}

export function CreateUtxoTransactionRequestDetailsToJSON(value?: CreateUtxoTransactionRequestDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'utxo_partially_signed_bitcoin_transaction':
            return TransactionDetailsUtxoPsbtRequestToJSON(value);
        case 'utxo_transfer':
            return TransactionDetailsUtxoTransferRequestToJSON(value);
        default:
            throw new Error(`No variant of CreateUtxoTransactionRequestDetails exists with 'type=${value['type']}'`);
    }

}

