/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TransactionDetailsUtxoPsbtRequest } from './TransactionDetailsUtxoPsbtRequest';
import {
    TransactionDetailsUtxoPsbtRequestToJSON,
} from './TransactionDetailsUtxoPsbtRequest';
import type { TransactionDetailsUtxoTransferRequest } from './TransactionDetailsUtxoTransferRequest';
import {
    TransactionDetailsUtxoTransferRequestToJSON,
} from './TransactionDetailsUtxoTransferRequest';

/**
 * 
 * @export
 * @type CreateUtxoTransactionRequestDetails
 */
export type CreateUtxoTransactionRequestDetails = { type: 'utxo_partially_signed_bitcoin_transaction' } & TransactionDetailsUtxoPsbtRequest | { type: 'utxo_transfer' } & TransactionDetailsUtxoTransferRequest;

export function CreateUtxoTransactionRequestDetailsToJSON(json: any): any {
    return CreateUtxoTransactionRequestDetailsToJSONTyped(json, false);
}

function CreateUtxoTransactionRequestDetailsToJSONTyped(value?: CreateUtxoTransactionRequestDetails | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'utxo_partially_signed_bitcoin_transaction':
            return Object.assign({}, TransactionDetailsUtxoPsbtRequestToJSON(value), { type: 'utxo_partially_signed_bitcoin_transaction' } as const);
        case 'utxo_transfer':
            return Object.assign({}, TransactionDetailsUtxoTransferRequestToJSON(value), { type: 'utxo_transfer' } as const);
        default:
            throw new Error(`No variant of CreateUtxoTransactionRequestDetails exists with 'type=${value['type']}'`);
    }

}

