/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DappInfo } from './DappInfo';
import {
    DappInfoFromJSON,
    DappInfoFromJSONTyped,
    DappInfoToJSON,
    DappInfoToJSONTyped,
} from './DappInfo';
import type { SignMode } from './SignMode';
import {
    SignModeFromJSON,
    SignModeFromJSONTyped,
    SignModeToJSON,
    SignModeToJSONTyped,
} from './SignMode';
import type { CreateSolanaTransactionRequestDetails } from './CreateSolanaTransactionRequestDetails';
import {
    CreateSolanaTransactionRequestDetailsFromJSON,
    CreateSolanaTransactionRequestDetailsFromJSONTyped,
    CreateSolanaTransactionRequestDetailsToJSON,
    CreateSolanaTransactionRequestDetailsToJSONTyped,
} from './CreateSolanaTransactionRequestDetails';
import type { SignerType } from './SignerType';
import {
    SignerTypeFromJSON,
    SignerTypeFromJSONTyped,
    SignerTypeToJSON,
    SignerTypeToJSONTyped,
} from './SignerType';

/**
 * 
 * @export
 * @interface CreateSolanaTransactionRequest
 */
export interface CreateSolanaTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSolanaTransactionRequest
     */
    vaultId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSolanaTransactionRequest
     */
    note?: string;
    /**
     * 
     * @type {SignerType}
     * @memberof CreateSolanaTransactionRequest
     */
    signerType?: SignerType;
    /**
     * 
     * @type {SignMode}
     * @memberof CreateSolanaTransactionRequest
     */
    signMode?: SignMode;
    /**
     * 
     * @type {DappInfo}
     * @memberof CreateSolanaTransactionRequest
     */
    dappInfo?: DappInfo;
    /**
     * 
     * @type {string}
     * @memberof CreateSolanaTransactionRequest
     */
    type: CreateSolanaTransactionRequestTypeEnum;
    /**
     * 
     * @type {CreateSolanaTransactionRequestDetails}
     * @memberof CreateSolanaTransactionRequest
     */
    details: CreateSolanaTransactionRequestDetails;
}


/**
 * @export
 */
export const CreateSolanaTransactionRequestTypeEnum = {
    solanaTransaction: 'solana_transaction'
} as const;
export type CreateSolanaTransactionRequestTypeEnum = typeof CreateSolanaTransactionRequestTypeEnum[keyof typeof CreateSolanaTransactionRequestTypeEnum];


/**
 * Check if a given object implements the CreateSolanaTransactionRequest interface.
 */
export function instanceOfCreateSolanaTransactionRequest(value: object): value is CreateSolanaTransactionRequest {
    if (!('vaultId' in value) || value['vaultId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function CreateSolanaTransactionRequestFromJSON(json: any): CreateSolanaTransactionRequest {
    return CreateSolanaTransactionRequestFromJSONTyped(json, false);
}

export function CreateSolanaTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSolanaTransactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'vaultId': json['vault_id'],
        'note': json['note'] == null ? undefined : json['note'],
        'signerType': json['signer_type'] == null ? undefined : SignerTypeFromJSON(json['signer_type']),
        'signMode': json['sign_mode'] == null ? undefined : SignModeFromJSON(json['sign_mode']),
        'dappInfo': json['dapp_info'] == null ? undefined : DappInfoFromJSON(json['dapp_info']),
        'type': json['type'],
        'details': CreateSolanaTransactionRequestDetailsFromJSON(json['details']),
    };
}

export function CreateSolanaTransactionRequestToJSON(json: any): CreateSolanaTransactionRequest {
    return CreateSolanaTransactionRequestToJSONTyped(json, false);
}

export function CreateSolanaTransactionRequestToJSONTyped(value?: CreateSolanaTransactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vault_id': value['vaultId'],
        'note': value['note'],
        'signer_type': SignerTypeToJSON(value['signerType']),
        'sign_mode': SignModeToJSON(value['signMode']),
        'dapp_info': DappInfoToJSON(value['dappInfo']),
        'type': value['type'],
        'details': CreateSolanaTransactionRequestDetailsToJSON(value['details']),
    };
}

