/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DappInfo } from './DappInfo';
import {
    DappInfoToJSON,
} from './DappInfo';
import type { CosmosArbitraryMessageRequest } from './CosmosArbitraryMessageRequest';
import {
    CosmosArbitraryMessageRequestToJSON,
} from './CosmosArbitraryMessageRequest';
import type { SignMode } from './SignMode';
import {
    SignModeToJSON,
} from './SignMode';
import type { SignerType } from './SignerType';
import {
    SignerTypeToJSON,
} from './SignerType';

/**
 * 
 * @export
 * @interface CreateCosmosMessageRequest
 */
export interface CreateCosmosMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCosmosMessageRequest
     */
    vaultId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCosmosMessageRequest
     */
    note?: string;
    /**
     * 
     * @type {SignerType}
     * @memberof CreateCosmosMessageRequest
     */
    signerType?: SignerType;
    /**
     * 
     * @type {SignMode}
     * @memberof CreateCosmosMessageRequest
     */
    signMode?: SignMode;
    /**
     * 
     * @type {DappInfo}
     * @memberof CreateCosmosMessageRequest
     */
    dappInfo?: DappInfo;
    /**
     * 
     * @type {string}
     * @memberof CreateCosmosMessageRequest
     */
    type: CreateCosmosMessageRequestTypeEnum;
    /**
     * 
     * @type {CosmosArbitraryMessageRequest}
     * @memberof CreateCosmosMessageRequest
     */
    details: CosmosArbitraryMessageRequest;
}


/**
 * 
 */
const CreateCosmosMessageRequestTypeEnum = {
    cosmosMessage: 'cosmos_message'
} as const;
type CreateCosmosMessageRequestTypeEnum = typeof CreateCosmosMessageRequestTypeEnum[keyof typeof CreateCosmosMessageRequestTypeEnum];

export function CreateCosmosMessageRequestToJSON(json: any): CreateCosmosMessageRequest {
    return CreateCosmosMessageRequestToJSONTyped(json, false);
}

function CreateCosmosMessageRequestToJSONTyped(value?: CreateCosmosMessageRequest | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vault_id': value['vaultId'],
        'note': value['note'],
        'signer_type': SignerTypeToJSON(value['signerType']),
        'sign_mode': SignModeToJSON(value['signMode']),
        'dapp_info': DappInfoToJSON(value['dappInfo']),
        'type': value['type'],
        'details': CosmosArbitraryMessageRequestToJSON(value['details']),
    };
}
