/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DappInfo } from './DappInfo';
import {
    DappInfoFromJSON,
    DappInfoFromJSONTyped,
    DappInfoToJSON,
    DappInfoToJSONTyped,
} from './DappInfo';
import type { CosmosArbitraryMessageRequest } from './CosmosArbitraryMessageRequest';
import {
    CosmosArbitraryMessageRequestFromJSON,
    CosmosArbitraryMessageRequestFromJSONTyped,
    CosmosArbitraryMessageRequestToJSON,
    CosmosArbitraryMessageRequestToJSONTyped,
} from './CosmosArbitraryMessageRequest';
import type { SignMode } from './SignMode';
import {
    SignModeFromJSON,
    SignModeFromJSONTyped,
    SignModeToJSON,
    SignModeToJSONTyped,
} from './SignMode';
import type { SignerType } from './SignerType';
import {
    SignerTypeFromJSON,
    SignerTypeFromJSONTyped,
    SignerTypeToJSON,
    SignerTypeToJSONTyped,
} from './SignerType';

/**
 * 
 * @export
 * @interface CreateCosmosMessageRequest
 */
export interface CreateCosmosMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCosmosMessageRequest
     */
    vaultId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCosmosMessageRequest
     */
    note?: string;
    /**
     * 
     * @type {SignerType}
     * @memberof CreateCosmosMessageRequest
     */
    signerType?: SignerType;
    /**
     * 
     * @type {SignMode}
     * @memberof CreateCosmosMessageRequest
     */
    signMode?: SignMode;
    /**
     * 
     * @type {DappInfo}
     * @memberof CreateCosmosMessageRequest
     */
    dappInfo?: DappInfo;
    /**
     * 
     * @type {string}
     * @memberof CreateCosmosMessageRequest
     */
    type: CreateCosmosMessageRequestTypeEnum;
    /**
     * 
     * @type {CosmosArbitraryMessageRequest}
     * @memberof CreateCosmosMessageRequest
     */
    details: CosmosArbitraryMessageRequest;
}


/**
 * @export
 */
export const CreateCosmosMessageRequestTypeEnum = {
    cosmosMessage: 'cosmos_message'
} as const;
export type CreateCosmosMessageRequestTypeEnum = typeof CreateCosmosMessageRequestTypeEnum[keyof typeof CreateCosmosMessageRequestTypeEnum];


/**
 * Check if a given object implements the CreateCosmosMessageRequest interface.
 */
export function instanceOfCreateCosmosMessageRequest(value: object): value is CreateCosmosMessageRequest {
    if (!('vaultId' in value) || value['vaultId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function CreateCosmosMessageRequestFromJSON(json: any): CreateCosmosMessageRequest {
    return CreateCosmosMessageRequestFromJSONTyped(json, false);
}

export function CreateCosmosMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCosmosMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'vaultId': json['vault_id'],
        'note': json['note'] == null ? undefined : json['note'],
        'signerType': json['signer_type'] == null ? undefined : SignerTypeFromJSON(json['signer_type']),
        'signMode': json['sign_mode'] == null ? undefined : SignModeFromJSON(json['sign_mode']),
        'dappInfo': json['dapp_info'] == null ? undefined : DappInfoFromJSON(json['dapp_info']),
        'type': json['type'],
        'details': CosmosArbitraryMessageRequestFromJSON(json['details']),
    };
}

export function CreateCosmosMessageRequestToJSON(json: any): CreateCosmosMessageRequest {
    return CreateCosmosMessageRequestToJSONTyped(json, false);
}

export function CreateCosmosMessageRequestToJSONTyped(value?: CreateCosmosMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vault_id': value['vaultId'],
        'note': value['note'],
        'signer_type': SignerTypeToJSON(value['signerType']),
        'sign_mode': SignModeToJSON(value['signMode']),
        'dapp_info': DappInfoToJSON(value['dappInfo']),
        'type': value['type'],
        'details': CosmosArbitraryMessageRequestToJSON(value['details']),
    };
}

