/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DappInfo } from './DappInfo';
import {
    DappInfoFromJSON,
    DappInfoFromJSONTyped,
    DappInfoToJSON,
    DappInfoToJSONTyped,
} from './DappInfo';
import type { SignMode } from './SignMode';
import {
    SignModeFromJSON,
    SignModeFromJSONTyped,
    SignModeToJSON,
    SignModeToJSONTyped,
} from './SignMode';
import type { CreateStacksTransactionRequestDetails } from './CreateStacksTransactionRequestDetails';
import {
    CreateStacksTransactionRequestDetailsFromJSON,
    CreateStacksTransactionRequestDetailsFromJSONTyped,
    CreateStacksTransactionRequestDetailsToJSON,
    CreateStacksTransactionRequestDetailsToJSONTyped,
} from './CreateStacksTransactionRequestDetails';
import type { SignerType } from './SignerType';
import {
    SignerTypeFromJSON,
    SignerTypeFromJSONTyped,
    SignerTypeToJSON,
    SignerTypeToJSONTyped,
} from './SignerType';

/**
 * 
 * @export
 * @interface CreateStacksTransactionRequest
 */
export interface CreateStacksTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateStacksTransactionRequest
     */
    vaultId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStacksTransactionRequest
     */
    note?: string;
    /**
     * 
     * @type {SignerType}
     * @memberof CreateStacksTransactionRequest
     */
    signerType?: SignerType;
    /**
     * 
     * @type {SignMode}
     * @memberof CreateStacksTransactionRequest
     */
    signMode?: SignMode;
    /**
     * 
     * @type {DappInfo}
     * @memberof CreateStacksTransactionRequest
     */
    dappInfo?: DappInfo;
    /**
     * 
     * @type {string}
     * @memberof CreateStacksTransactionRequest
     */
    type: CreateStacksTransactionRequestTypeEnum;
    /**
     * 
     * @type {CreateStacksTransactionRequestDetails}
     * @memberof CreateStacksTransactionRequest
     */
    details: CreateStacksTransactionRequestDetails;
}


/**
 * @export
 */
export const CreateStacksTransactionRequestTypeEnum = {
    stacksTransaction: 'stacks_transaction'
} as const;
export type CreateStacksTransactionRequestTypeEnum = typeof CreateStacksTransactionRequestTypeEnum[keyof typeof CreateStacksTransactionRequestTypeEnum];


/**
 * Check if a given object implements the CreateStacksTransactionRequest interface.
 */
export function instanceOfCreateStacksTransactionRequest(value: object): value is CreateStacksTransactionRequest {
    if (!('vaultId' in value) || value['vaultId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function CreateStacksTransactionRequestFromJSON(json: any): CreateStacksTransactionRequest {
    return CreateStacksTransactionRequestFromJSONTyped(json, false);
}

export function CreateStacksTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStacksTransactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'vaultId': json['vault_id'],
        'note': json['note'] == null ? undefined : json['note'],
        'signerType': json['signer_type'] == null ? undefined : SignerTypeFromJSON(json['signer_type']),
        'signMode': json['sign_mode'] == null ? undefined : SignModeFromJSON(json['sign_mode']),
        'dappInfo': json['dapp_info'] == null ? undefined : DappInfoFromJSON(json['dapp_info']),
        'type': json['type'],
        'details': CreateStacksTransactionRequestDetailsFromJSON(json['details']),
    };
}

export function CreateStacksTransactionRequestToJSON(json: any): CreateStacksTransactionRequest {
    return CreateStacksTransactionRequestToJSONTyped(json, false);
}

export function CreateStacksTransactionRequestToJSONTyped(value?: CreateStacksTransactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vault_id': value['vaultId'],
        'note': value['note'],
        'signer_type': SignerTypeToJSON(value['signerType']),
        'sign_mode': SignModeToJSON(value['signMode']),
        'dapp_info': DappInfoToJSON(value['dappInfo']),
        'type': value['type'],
        'details': CreateStacksTransactionRequestDetailsToJSON(value['details']),
    };
}

