/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateSuiTransactionRequestDetails } from './CreateSuiTransactionRequestDetails';
import {
    CreateSuiTransactionRequestDetailsFromJSON,
    CreateSuiTransactionRequestDetailsFromJSONTyped,
    CreateSuiTransactionRequestDetailsToJSON,
} from './CreateSuiTransactionRequestDetails';
import type { SignMode } from './SignMode';
import {
    SignModeFromJSON,
    SignModeFromJSONTyped,
    SignModeToJSON,
} from './SignMode';
import type { SignerType } from './SignerType';
import {
    SignerTypeFromJSON,
    SignerTypeFromJSONTyped,
    SignerTypeToJSON,
} from './SignerType';
import type { SuiTransactionState } from './SuiTransactionState';
import {
    SuiTransactionStateFromJSON,
    SuiTransactionStateFromJSONTyped,
    SuiTransactionStateToJSON,
} from './SuiTransactionState';

/**
 * 
 * @export
 * @interface CreateSuiTransactionWithWaitRequest
 */
export interface CreateSuiTransactionWithWaitRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSuiTransactionWithWaitRequest
     */
    vaultId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSuiTransactionWithWaitRequest
     */
    note?: string;
    /**
     * 
     * @type {SignerType}
     * @memberof CreateSuiTransactionWithWaitRequest
     */
    signerType?: SignerType;
    /**
     * 
     * @type {SignMode}
     * @memberof CreateSuiTransactionWithWaitRequest
     */
    signMode?: SignMode;
    /**
     * 
     * @type {string}
     * @memberof CreateSuiTransactionWithWaitRequest
     */
    type: CreateSuiTransactionWithWaitRequestTypeEnum;
    /**
     * 
     * @type {CreateSuiTransactionRequestDetails}
     * @memberof CreateSuiTransactionWithWaitRequest
     */
    details: CreateSuiTransactionRequestDetails;
    /**
     * 
     * @type {number}
     * @memberof CreateSuiTransactionWithWaitRequest
     */
    timeout?: number;
    /**
     * 
     * @type {SuiTransactionState}
     * @memberof CreateSuiTransactionWithWaitRequest
     */
    waitForState: SuiTransactionState;
}


/**
 * @export
 */
export const CreateSuiTransactionWithWaitRequestTypeEnum = {
    suiTransaction: 'sui_transaction'
} as const;
export type CreateSuiTransactionWithWaitRequestTypeEnum = typeof CreateSuiTransactionWithWaitRequestTypeEnum[keyof typeof CreateSuiTransactionWithWaitRequestTypeEnum];


/**
 * Check if a given object implements the CreateSuiTransactionWithWaitRequest interface.
 */
export function instanceOfCreateSuiTransactionWithWaitRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "vaultId" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "details" in value;
    isInstance = isInstance && "waitForState" in value;

    return isInstance;
}

export function CreateSuiTransactionWithWaitRequestFromJSON(json: any): CreateSuiTransactionWithWaitRequest {
    return CreateSuiTransactionWithWaitRequestFromJSONTyped(json, false);
}

export function CreateSuiTransactionWithWaitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSuiTransactionWithWaitRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'vaultId': json['vault_id'],
        'note': !exists(json, 'note') ? undefined : json['note'],
        'signerType': !exists(json, 'signer_type') ? undefined : SignerTypeFromJSON(json['signer_type']),
        'signMode': !exists(json, 'sign_mode') ? undefined : SignModeFromJSON(json['sign_mode']),
        'type': json['type'],
        'details': CreateSuiTransactionRequestDetailsFromJSON(json['details']),
        'timeout': !exists(json, 'timeout') ? undefined : json['timeout'],
        'waitForState': SuiTransactionStateFromJSON(json['wait_for_state']),
    };
}

export function CreateSuiTransactionWithWaitRequestToJSON(value?: CreateSuiTransactionWithWaitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vault_id': value.vaultId,
        'note': value.note,
        'signer_type': SignerTypeToJSON(value.signerType),
        'sign_mode': SignModeToJSON(value.signMode),
        'type': value.type,
        'details': CreateSuiTransactionRequestDetailsToJSON(value.details),
        'timeout': value.timeout,
        'wait_for_state': SuiTransactionStateToJSON(value.waitForState),
    };
}

