/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TypedCosmosRawTransactionRequest } from './TypedCosmosRawTransactionRequest';
import {
    TypedCosmosRawTransactionRequestToJSON,
} from './TypedCosmosRawTransactionRequest';
import type { TypedCosmosTransferRequest } from './TypedCosmosTransferRequest';
import {
    TypedCosmosTransferRequestToJSON,
} from './TypedCosmosTransferRequest';

/**
 * 
 * @export
 * @type CreateCosmosTransactionRequestDetails
 */
export type CreateCosmosTransactionRequestDetails = { type: 'cosmos_raw_transaction' } & TypedCosmosRawTransactionRequest | { type: 'cosmos_transfer' } & TypedCosmosTransferRequest;

export function CreateCosmosTransactionRequestDetailsToJSON(json: any): any {
    return CreateCosmosTransactionRequestDetailsToJSONTyped(json, false);
}

function CreateCosmosTransactionRequestDetailsToJSONTyped(value?: CreateCosmosTransactionRequestDetails | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'cosmos_raw_transaction':
            return Object.assign({}, TypedCosmosRawTransactionRequestToJSON(value), { type: 'cosmos_raw_transaction' } as const);
        case 'cosmos_transfer':
            return Object.assign({}, TypedCosmosTransferRequestToJSON(value), { type: 'cosmos_transfer' } as const);
        default:
            throw new Error(`No variant of CreateCosmosTransactionRequestDetails exists with 'type=${value['type']}'`);
    }

}

