/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface CreateStacksVaultRequest
 */
export interface CreateStacksVaultRequest {
    /**
     * The name of the vault.
     * @type {string}
     * @memberof CreateStacksVaultRequest
     */
    name: string;
    /**
     * The end user id to create a vault for.This field is required for end-user vault creation, otherwise, it's optional. If not provided, the organization's default keyset will be used.
     * @type {string}
     * @memberof CreateStacksVaultRequest
     */
    endUserId?: string;
    /**
     * The group to add this vault to. If not provided, the vault will be created in the Default vault group.
     * @type {string}
     * @memberof CreateStacksVaultRequest
     */
    vaultGroupId?: string;
    /**
     * Stacks vault type.
     * @type {CreateStacksVaultRequestTypeEnum}
     * @memberof CreateStacksVaultRequest
     */
    type: CreateStacksVaultRequestTypeEnum;
}


/**
 * @export
 */
const CreateStacksVaultRequestTypeEnum = {
    stacks: 'stacks'
} as const;
type CreateStacksVaultRequestTypeEnum = typeof CreateStacksVaultRequestTypeEnum[keyof typeof CreateStacksVaultRequestTypeEnum];

export function CreateStacksVaultRequestToJSON(json: any): CreateStacksVaultRequest {
    return CreateStacksVaultRequestToJSONTyped(json, false);
}

function CreateStacksVaultRequestToJSONTyped(value?: CreateStacksVaultRequest | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'end_user_id': value['endUserId'],
        'vault_group_id': value['vaultGroupId'],
        'type': value['type'],
    };
}
