/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DappInfo } from './DappInfo';
import {
    DappInfoToJSON,
} from './DappInfo';
import type { SignMode } from './SignMode';
import {
    SignModeToJSON,
} from './SignMode';
import type { CreateCosmosTransactionRequestDetails } from './CreateCosmosTransactionRequestDetails';
import {
    CreateCosmosTransactionRequestDetailsToJSON,
} from './CreateCosmosTransactionRequestDetails';
import type { SignerType } from './SignerType';
import {
    SignerTypeToJSON,
} from './SignerType';

/**
 * 
 * @export
 * @interface CreateCosmosTransactionRequest
 */
export interface CreateCosmosTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCosmosTransactionRequest
     */
    vaultId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCosmosTransactionRequest
     */
    note?: string;
    /**
     * 
     * @type {SignerType}
     * @memberof CreateCosmosTransactionRequest
     */
    signerType?: SignerType;
    /**
     * 
     * @type {SignMode}
     * @memberof CreateCosmosTransactionRequest
     */
    signMode?: SignMode;
    /**
     * 
     * @type {DappInfo}
     * @memberof CreateCosmosTransactionRequest
     */
    dappInfo?: DappInfo;
    /**
     * 
     * @type {string}
     * @memberof CreateCosmosTransactionRequest
     */
    type: CreateCosmosTransactionRequestTypeEnum;
    /**
     * 
     * @type {CreateCosmosTransactionRequestDetails}
     * @memberof CreateCosmosTransactionRequest
     */
    details: CreateCosmosTransactionRequestDetails;
}


/**
 * 
 */
const CreateCosmosTransactionRequestTypeEnum = {
    cosmosTransaction: 'cosmos_transaction'
} as const;
type CreateCosmosTransactionRequestTypeEnum = typeof CreateCosmosTransactionRequestTypeEnum[keyof typeof CreateCosmosTransactionRequestTypeEnum];

export function CreateCosmosTransactionRequestToJSON(json: any): CreateCosmosTransactionRequest {
    return CreateCosmosTransactionRequestToJSONTyped(json, false);
}

function CreateCosmosTransactionRequestToJSONTyped(value?: CreateCosmosTransactionRequest | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vault_id': value['vaultId'],
        'note': value['note'],
        'signer_type': SignerTypeToJSON(value['signerType']),
        'sign_mode': SignModeToJSON(value['signMode']),
        'dapp_info': DappInfoToJSON(value['dappInfo']),
        'type': value['type'],
        'details': CreateCosmosTransactionRequestDetailsToJSON(value['details']),
    };
}
