/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EvmChainRequest } from './EvmChainRequest';
import {
    EvmChainRequestToJSON,
} from './EvmChainRequest';

/**
 * 
 * @export
 * @interface CreateEvmTypedV1MessageRequest
 */
export interface CreateEvmTypedV1MessageRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateEvmTypedV1MessageRequest
     */
    type: CreateEvmTypedV1MessageRequestTypeEnum;
    /**
     * 
     * @type {EvmChainRequest}
     * @memberof CreateEvmTypedV1MessageRequest
     */
    chain: EvmChainRequest;
    /**
     * 
     * @type {string}
     * @memberof CreateEvmTypedV1MessageRequest
     */
    rawData: string;
}


/**
 * 
 */
const CreateEvmTypedV1MessageRequestTypeEnum = {
    typedMessageTypeV1: 'typed_message_type_v1'
} as const;
type CreateEvmTypedV1MessageRequestTypeEnum = typeof CreateEvmTypedV1MessageRequestTypeEnum[keyof typeof CreateEvmTypedV1MessageRequestTypeEnum];

export function CreateEvmTypedV1MessageRequestToJSON(json: any): CreateEvmTypedV1MessageRequest {
    return CreateEvmTypedV1MessageRequestToJSONTyped(json, false);
}

function CreateEvmTypedV1MessageRequestToJSONTyped(value?: CreateEvmTypedV1MessageRequest | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'chain': EvmChainRequestToJSON(value['chain']),
        'raw_data': value['rawData'],
    };
}
