/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateEvmTransactionRequestDetails } from './CreateEvmTransactionRequestDetails';
import {
    CreateEvmTransactionRequestDetailsFromJSON,
    CreateEvmTransactionRequestDetailsFromJSONTyped,
    CreateEvmTransactionRequestDetailsToJSON,
    CreateEvmTransactionRequestDetailsToJSONTyped,
} from './CreateEvmTransactionRequestDetails';
import type { DappInfo } from './DappInfo';
import {
    DappInfoFromJSON,
    DappInfoFromJSONTyped,
    DappInfoToJSON,
    DappInfoToJSONTyped,
} from './DappInfo';
import type { SignMode } from './SignMode';
import {
    SignModeFromJSON,
    SignModeFromJSONTyped,
    SignModeToJSON,
    SignModeToJSONTyped,
} from './SignMode';
import type { PushableTransactionState } from './PushableTransactionState';
import {
    PushableTransactionStateFromJSON,
    PushableTransactionStateFromJSONTyped,
    PushableTransactionStateToJSON,
    PushableTransactionStateToJSONTyped,
} from './PushableTransactionState';
import type { SignerType } from './SignerType';
import {
    SignerTypeFromJSON,
    SignerTypeFromJSONTyped,
    SignerTypeToJSON,
    SignerTypeToJSONTyped,
} from './SignerType';

/**
 * 
 * @export
 * @interface CreateEvmTransactionWithWaitRequest
 */
export interface CreateEvmTransactionWithWaitRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateEvmTransactionWithWaitRequest
     */
    vaultId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEvmTransactionWithWaitRequest
     */
    note?: string;
    /**
     * 
     * @type {SignerType}
     * @memberof CreateEvmTransactionWithWaitRequest
     */
    signerType?: SignerType;
    /**
     * 
     * @type {SignMode}
     * @memberof CreateEvmTransactionWithWaitRequest
     */
    signMode?: SignMode;
    /**
     * 
     * @type {DappInfo}
     * @memberof CreateEvmTransactionWithWaitRequest
     */
    dappInfo?: DappInfo;
    /**
     * 
     * @type {string}
     * @memberof CreateEvmTransactionWithWaitRequest
     */
    type: CreateEvmTransactionWithWaitRequestTypeEnum;
    /**
     * 
     * @type {CreateEvmTransactionRequestDetails}
     * @memberof CreateEvmTransactionWithWaitRequest
     */
    details: CreateEvmTransactionRequestDetails;
    /**
     * 
     * @type {number}
     * @memberof CreateEvmTransactionWithWaitRequest
     */
    timeout?: number;
    /**
     * 
     * @type {PushableTransactionState}
     * @memberof CreateEvmTransactionWithWaitRequest
     */
    waitForState: PushableTransactionState;
}


/**
 * @export
 */
export const CreateEvmTransactionWithWaitRequestTypeEnum = {
    evmTransaction: 'evm_transaction'
} as const;
export type CreateEvmTransactionWithWaitRequestTypeEnum = typeof CreateEvmTransactionWithWaitRequestTypeEnum[keyof typeof CreateEvmTransactionWithWaitRequestTypeEnum];


/**
 * Check if a given object implements the CreateEvmTransactionWithWaitRequest interface.
 */
export function instanceOfCreateEvmTransactionWithWaitRequest(value: object): value is CreateEvmTransactionWithWaitRequest {
    if (!('vaultId' in value) || value['vaultId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    if (!('waitForState' in value) || value['waitForState'] === undefined) return false;
    return true;
}

export function CreateEvmTransactionWithWaitRequestFromJSON(json: any): CreateEvmTransactionWithWaitRequest {
    return CreateEvmTransactionWithWaitRequestFromJSONTyped(json, false);
}

export function CreateEvmTransactionWithWaitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEvmTransactionWithWaitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'vaultId': json['vault_id'],
        'note': json['note'] == null ? undefined : json['note'],
        'signerType': json['signer_type'] == null ? undefined : SignerTypeFromJSON(json['signer_type']),
        'signMode': json['sign_mode'] == null ? undefined : SignModeFromJSON(json['sign_mode']),
        'dappInfo': json['dapp_info'] == null ? undefined : DappInfoFromJSON(json['dapp_info']),
        'type': json['type'],
        'details': CreateEvmTransactionRequestDetailsFromJSON(json['details']),
        'timeout': json['timeout'] == null ? undefined : json['timeout'],
        'waitForState': PushableTransactionStateFromJSON(json['wait_for_state']),
    };
}

export function CreateEvmTransactionWithWaitRequestToJSON(json: any): CreateEvmTransactionWithWaitRequest {
    return CreateEvmTransactionWithWaitRequestToJSONTyped(json, false);
}

export function CreateEvmTransactionWithWaitRequestToJSONTyped(value?: CreateEvmTransactionWithWaitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vault_id': value['vaultId'],
        'note': value['note'],
        'signer_type': SignerTypeToJSON(value['signerType']),
        'sign_mode': SignModeToJSON(value['signMode']),
        'dapp_info': DappInfoToJSON(value['dappInfo']),
        'type': value['type'],
        'details': CreateEvmTransactionRequestDetailsToJSON(value['details']),
        'timeout': value['timeout'],
        'wait_for_state': PushableTransactionStateToJSON(value['waitForState']),
    };
}

