/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ArchRecipientBase58Repr } from './ArchRecipientBase58Repr';
import {
    ArchRecipientBase58ReprToJSON,
} from './ArchRecipientBase58Repr';
import type { RecipientContactId } from './RecipientContactId';
import {
    RecipientContactIdToJSON,
} from './RecipientContactId';
import type { RecipientVaultId } from './RecipientVaultId';
import {
    RecipientVaultIdToJSON,
} from './RecipientVaultId';

/**
 * 
 * @export
 * @type CreateArchTransferRequestTo
 */
export type CreateArchTransferRequestTo = { type: 'address' } & ArchRecipientBase58Repr | { type: 'contact_id' } & RecipientContactId | { type: 'vault_id' } & RecipientVaultId;

export function CreateArchTransferRequestToToJSON(json: any): any {
    return CreateArchTransferRequestToToJSONTyped(json, false);
}

function CreateArchTransferRequestToToJSONTyped(value?: CreateArchTransferRequestTo | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'address':
            return Object.assign({}, ArchRecipientBase58ReprToJSON(value), { type: 'address' } as const);
        case 'contact_id':
            return Object.assign({}, RecipientContactIdToJSON(value), { type: 'contact_id' } as const);
        case 'vault_id':
            return Object.assign({}, RecipientVaultIdToJSON(value), { type: 'vault_id' } as const);
        default:
            throw new Error(`No variant of CreateArchTransferRequestTo exists with 'type=${value['type']}'`);
    }

}

