/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBackupEmailChangeRequest
 */
export interface CreateBackupEmailChangeRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateBackupEmailChangeRequest
     */
    backupEmail: string;
}

/**
 * Check if a given object implements the CreateBackupEmailChangeRequest interface.
 */
export function instanceOfCreateBackupEmailChangeRequest(value: object): value is CreateBackupEmailChangeRequest {
    if (!('backupEmail' in value) || value['backupEmail'] === undefined) return false;
    return true;
}

export function CreateBackupEmailChangeRequestFromJSON(json: any): CreateBackupEmailChangeRequest {
    return CreateBackupEmailChangeRequestFromJSONTyped(json, false);
}

export function CreateBackupEmailChangeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBackupEmailChangeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'backupEmail': json['backup_email'],
    };
}

export function CreateBackupEmailChangeRequestToJSON(json: any): CreateBackupEmailChangeRequest {
    return CreateBackupEmailChangeRequestToJSONTyped(json, false);
}

export function CreateBackupEmailChangeRequestToJSONTyped(value?: CreateBackupEmailChangeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'backup_email': value['backupEmail'],
    };
}

