/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EvmChainRequest } from './EvmChainRequest';
import {
    EvmChainRequestFromJSON,
    EvmChainRequestFromJSONTyped,
    EvmChainRequestToJSON,
} from './EvmChainRequest';

/**
 * 
 * @export
 * @interface CreateEvmPersonalMessageRequest
 */
export interface CreateEvmPersonalMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateEvmPersonalMessageRequest
     */
    type: CreateEvmPersonalMessageRequestTypeEnum;
    /**
     * 
     * @type {EvmChainRequest}
     * @memberof CreateEvmPersonalMessageRequest
     */
    chain: EvmChainRequest;
    /**
     * 
     * @type {string}
     * @memberof CreateEvmPersonalMessageRequest
     */
    rawData: string;
}


/**
 * @export
 */
export const CreateEvmPersonalMessageRequestTypeEnum = {
    personalMessageType: 'personal_message_type'
} as const;
export type CreateEvmPersonalMessageRequestTypeEnum = typeof CreateEvmPersonalMessageRequestTypeEnum[keyof typeof CreateEvmPersonalMessageRequestTypeEnum];


/**
 * Check if a given object implements the CreateEvmPersonalMessageRequest interface.
 */
export function instanceOfCreateEvmPersonalMessageRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "chain" in value;
    isInstance = isInstance && "rawData" in value;

    return isInstance;
}

export function CreateEvmPersonalMessageRequestFromJSON(json: any): CreateEvmPersonalMessageRequest {
    return CreateEvmPersonalMessageRequestFromJSONTyped(json, false);
}

export function CreateEvmPersonalMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEvmPersonalMessageRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'chain': EvmChainRequestFromJSON(json['chain']),
        'rawData': json['raw_data'],
    };
}

export function CreateEvmPersonalMessageRequestToJSON(value?: CreateEvmPersonalMessageRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'chain': EvmChainRequestToJSON(value.chain),
        'raw_data': value.rawData,
    };
}

