/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TronTypedMessageV1Request } from './TronTypedMessageV1Request';
import {
    TronTypedMessageV1RequestToJSON,
} from './TronTypedMessageV1Request';
import type { TronTypedMessageV2Request } from './TronTypedMessageV2Request';
import {
    TronTypedMessageV2RequestToJSON,
} from './TronTypedMessageV2Request';

/**
 * 
 * @export
 * @type CreateTronMessageRequestDetails
 */
export type CreateTronMessageRequestDetails = { type: 'typed_message_type_v1' } & TronTypedMessageV1Request | { type: 'typed_message_type_v2' } & TronTypedMessageV2Request;

export function CreateTronMessageRequestDetailsToJSON(json: any): any {
    return CreateTronMessageRequestDetailsToJSONTyped(json, false);
}

function CreateTronMessageRequestDetailsToJSONTyped(value?: CreateTronMessageRequestDetails | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'typed_message_type_v1':
            return Object.assign({}, TronTypedMessageV1RequestToJSON(value), { type: 'typed_message_type_v1' } as const);
        case 'typed_message_type_v2':
            return Object.assign({}, TronTypedMessageV2RequestToJSON(value), { type: 'typed_message_type_v2' } as const);
        default:
            return value;
    }
}

