/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DappInfo } from './DappInfo';
import {
    DappInfoFromJSON,
    DappInfoFromJSONTyped,
    DappInfoToJSON,
    DappInfoToJSONTyped,
} from './DappInfo';
import type { SignMode } from './SignMode';
import {
    SignModeFromJSON,
    SignModeFromJSONTyped,
    SignModeToJSON,
    SignModeToJSONTyped,
} from './SignMode';
import type { SignerType } from './SignerType';
import {
    SignerTypeFromJSON,
    SignerTypeFromJSONTyped,
    SignerTypeToJSON,
    SignerTypeToJSONTyped,
} from './SignerType';
import type { CreateTronTransactionRequestDetails } from './CreateTronTransactionRequestDetails';
import {
    CreateTronTransactionRequestDetailsFromJSON,
    CreateTronTransactionRequestDetailsFromJSONTyped,
    CreateTronTransactionRequestDetailsToJSON,
    CreateTronTransactionRequestDetailsToJSONTyped,
} from './CreateTronTransactionRequestDetails';

/**
 * 
 * @export
 * @interface CreateTronTransactionRequest
 */
export interface CreateTronTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTronTransactionRequest
     */
    vaultId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTronTransactionRequest
     */
    note?: string;
    /**
     * 
     * @type {SignerType}
     * @memberof CreateTronTransactionRequest
     */
    signerType?: SignerType;
    /**
     * 
     * @type {SignMode}
     * @memberof CreateTronTransactionRequest
     */
    signMode?: SignMode;
    /**
     * 
     * @type {DappInfo}
     * @memberof CreateTronTransactionRequest
     */
    dappInfo?: DappInfo;
    /**
     * 
     * @type {string}
     * @memberof CreateTronTransactionRequest
     */
    type: CreateTronTransactionRequestTypeEnum;
    /**
     * 
     * @type {CreateTronTransactionRequestDetails}
     * @memberof CreateTronTransactionRequest
     */
    details: CreateTronTransactionRequestDetails;
}


/**
 * @export
 */
export const CreateTronTransactionRequestTypeEnum = {
    tronTransaction: 'tron_transaction'
} as const;
export type CreateTronTransactionRequestTypeEnum = typeof CreateTronTransactionRequestTypeEnum[keyof typeof CreateTronTransactionRequestTypeEnum];


/**
 * Check if a given object implements the CreateTronTransactionRequest interface.
 */
export function instanceOfCreateTronTransactionRequest(value: object): value is CreateTronTransactionRequest {
    if (!('vaultId' in value) || value['vaultId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function CreateTronTransactionRequestFromJSON(json: any): CreateTronTransactionRequest {
    return CreateTronTransactionRequestFromJSONTyped(json, false);
}

export function CreateTronTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTronTransactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'vaultId': json['vault_id'],
        'note': json['note'] == null ? undefined : json['note'],
        'signerType': json['signer_type'] == null ? undefined : SignerTypeFromJSON(json['signer_type']),
        'signMode': json['sign_mode'] == null ? undefined : SignModeFromJSON(json['sign_mode']),
        'dappInfo': json['dapp_info'] == null ? undefined : DappInfoFromJSON(json['dapp_info']),
        'type': json['type'],
        'details': CreateTronTransactionRequestDetailsFromJSON(json['details']),
    };
}

export function CreateTronTransactionRequestToJSON(json: any): CreateTronTransactionRequest {
    return CreateTronTransactionRequestToJSONTyped(json, false);
}

export function CreateTronTransactionRequestToJSONTyped(value?: CreateTronTransactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vault_id': value['vaultId'],
        'note': value['note'],
        'signer_type': SignerTypeToJSON(value['signerType']),
        'sign_mode': SignModeToJSON(value['signMode']),
        'dapp_info': DappInfoToJSON(value['dappInfo']),
        'type': value['type'],
        'details': CreateTronTransactionRequestDetailsToJSON(value['details']),
    };
}

