/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BackupPublicKey } from './BackupPublicKey';
import {
    BackupPublicKeyFromJSON,
    BackupPublicKeyFromJSONTyped,
    BackupPublicKeyToJSON,
    BackupPublicKeyToJSONTyped,
} from './BackupPublicKey';

/**
 * 
 * @export
 * @interface CreatePublicKeyBackupRequest
 */
export interface CreatePublicKeyBackupRequest {
    /**
     * 
     * @type {string}
     * @memberof CreatePublicKeyBackupRequest
     */
    backupEmail: string;
    /**
     * 
     * @type {BackupPublicKey}
     * @memberof CreatePublicKeyBackupRequest
     */
    publicKey: BackupPublicKey;
}

/**
 * Check if a given object implements the CreatePublicKeyBackupRequest interface.
 */
export function instanceOfCreatePublicKeyBackupRequest(value: object): value is CreatePublicKeyBackupRequest {
    if (!('backupEmail' in value) || value['backupEmail'] === undefined) return false;
    if (!('publicKey' in value) || value['publicKey'] === undefined) return false;
    return true;
}

export function CreatePublicKeyBackupRequestFromJSON(json: any): CreatePublicKeyBackupRequest {
    return CreatePublicKeyBackupRequestFromJSONTyped(json, false);
}

export function CreatePublicKeyBackupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePublicKeyBackupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'backupEmail': json['backup_email'],
        'publicKey': BackupPublicKeyFromJSON(json['public_key']),
    };
}

export function CreatePublicKeyBackupRequestToJSON(json: any): CreatePublicKeyBackupRequest {
    return CreatePublicKeyBackupRequestToJSONTyped(json, false);
}

export function CreatePublicKeyBackupRequestToJSONTyped(value?: CreatePublicKeyBackupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'backup_email': value['backupEmail'],
        'public_key': BackupPublicKeyToJSON(value['publicKey']),
    };
}

