/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The user-specified nonce for the transaction.<br> If not provided, the transaction's nonce will be automatically determined upon signing. <br> If provided, it must equal the nonce of an existing transaction that has already been signed but not yet mined, on the same vault.<br> Alternatively, it may equal the next nonce of the vault.
 * @export
 * @interface CustomNonce
 */
export interface CustomNonce {
}

export function CustomNonceToJSON(json: any): CustomNonce {
    return CustomNonceToJSONTyped(json, false);
}

function CustomNonceToJSONTyped(value?: CustomNonce | null, _ignoreDiscriminator: boolean = false): any {
    return value;
}
