/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubmitChangeProposalErrorType } from './SubmitChangeProposalErrorType';
import {
    SubmitChangeProposalErrorTypeFromJSON,
    SubmitChangeProposalErrorTypeFromJSONTyped,
    SubmitChangeProposalErrorTypeToJSON,
    SubmitChangeProposalErrorTypeToJSONTyped,
} from './SubmitChangeProposalErrorType';

/**
 * 
 * @export
 * @interface DefinedPreconditionErrorSubmitChangeProposalErrorType
 */
export interface DefinedPreconditionErrorSubmitChangeProposalErrorType {
    /**
     * 
     * @type {string}
     * @memberof DefinedPreconditionErrorSubmitChangeProposalErrorType
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof DefinedPreconditionErrorSubmitChangeProposalErrorType
     */
    detail: string;
    /**
     * 
     * @type {string}
     * @memberof DefinedPreconditionErrorSubmitChangeProposalErrorType
     */
    requestId?: string;
    /**
     * 
     * @type {string}
     * @memberof DefinedPreconditionErrorSubmitChangeProposalErrorType
     */
    systemErrorCode?: string;
    /**
     * 
     * @type {SubmitChangeProposalErrorType}
     * @memberof DefinedPreconditionErrorSubmitChangeProposalErrorType
     */
    errorType?: SubmitChangeProposalErrorType;
}



/**
 * Check if a given object implements the DefinedPreconditionErrorSubmitChangeProposalErrorType interface.
 */
export function instanceOfDefinedPreconditionErrorSubmitChangeProposalErrorType(value: object): value is DefinedPreconditionErrorSubmitChangeProposalErrorType {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function DefinedPreconditionErrorSubmitChangeProposalErrorTypeFromJSON(json: any): DefinedPreconditionErrorSubmitChangeProposalErrorType {
    return DefinedPreconditionErrorSubmitChangeProposalErrorTypeFromJSONTyped(json, false);
}

export function DefinedPreconditionErrorSubmitChangeProposalErrorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinedPreconditionErrorSubmitChangeProposalErrorType {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'detail': json['detail'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'systemErrorCode': json['system_error_code'] == null ? undefined : json['system_error_code'],
        'errorType': json['error_type'] == null ? undefined : SubmitChangeProposalErrorTypeFromJSON(json['error_type']),
    };
}

export function DefinedPreconditionErrorSubmitChangeProposalErrorTypeToJSON(json: any): DefinedPreconditionErrorSubmitChangeProposalErrorType {
    return DefinedPreconditionErrorSubmitChangeProposalErrorTypeToJSONTyped(json, false);
}

export function DefinedPreconditionErrorSubmitChangeProposalErrorTypeToJSONTyped(value?: DefinedPreconditionErrorSubmitChangeProposalErrorType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'detail': value['detail'],
        'request_id': value['requestId'],
        'system_error_code': value['systemErrorCode'],
        'error_type': SubmitChangeProposalErrorTypeToJSON(value['errorType']),
    };
}

