/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AbortTransactionErrorType } from './AbortTransactionErrorType';
import {
    AbortTransactionErrorTypeFromJSON,
    AbortTransactionErrorTypeFromJSONTyped,
    AbortTransactionErrorTypeToJSON,
} from './AbortTransactionErrorType';

/**
 * 
 * @export
 * @interface DefinedPreconditionErrorAbortTransactionErrorType
 */
export interface DefinedPreconditionErrorAbortTransactionErrorType {
    /**
     * 
     * @type {string}
     * @memberof DefinedPreconditionErrorAbortTransactionErrorType
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof DefinedPreconditionErrorAbortTransactionErrorType
     */
    detail: string;
    /**
     * 
     * @type {string}
     * @memberof DefinedPreconditionErrorAbortTransactionErrorType
     */
    requestId?: string;
    /**
     * 
     * @type {string}
     * @memberof DefinedPreconditionErrorAbortTransactionErrorType
     */
    systemErrorCode?: string;
    /**
     * 
     * @type {AbortTransactionErrorType}
     * @memberof DefinedPreconditionErrorAbortTransactionErrorType
     */
    errorType?: AbortTransactionErrorType;
}

/**
 * Check if a given object implements the DefinedPreconditionErrorAbortTransactionErrorType interface.
 */
export function instanceOfDefinedPreconditionErrorAbortTransactionErrorType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "detail" in value;

    return isInstance;
}

export function DefinedPreconditionErrorAbortTransactionErrorTypeFromJSON(json: any): DefinedPreconditionErrorAbortTransactionErrorType {
    return DefinedPreconditionErrorAbortTransactionErrorTypeFromJSONTyped(json, false);
}

export function DefinedPreconditionErrorAbortTransactionErrorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinedPreconditionErrorAbortTransactionErrorType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'detail': json['detail'],
        'requestId': !exists(json, 'request_id') ? undefined : json['request_id'],
        'systemErrorCode': !exists(json, 'system_error_code') ? undefined : json['system_error_code'],
        'errorType': !exists(json, 'error_type') ? undefined : AbortTransactionErrorTypeFromJSON(json['error_type']),
    };
}

export function DefinedPreconditionErrorAbortTransactionErrorTypeToJSON(value?: DefinedPreconditionErrorAbortTransactionErrorType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'detail': value.detail,
        'request_id': value.requestId,
        'system_error_code': value.systemErrorCode,
        'error_type': AbortTransactionErrorTypeToJSON(value.errorType),
    };
}

