/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AptosAssetIdentifierRequest } from './AptosAssetIdentifierRequest';
import {
    AptosAssetIdentifierRequestFromJSON,
    AptosAssetIdentifierRequestFromJSONTyped,
    AptosAssetIdentifierRequestToJSON,
    AptosAssetIdentifierRequestToJSONTyped,
} from './AptosAssetIdentifierRequest';
import type { AptosChainUniqueId } from './AptosChainUniqueId';
import {
    AptosChainUniqueIdFromJSON,
    AptosChainUniqueIdFromJSONTyped,
    AptosChainUniqueIdToJSON,
    AptosChainUniqueIdToJSONTyped,
} from './AptosChainUniqueId';

/**
 * 
 * @export
 * @interface EditAptosContactRequest
 */
export interface EditAptosContactRequest {
    /**
     * 
     * @type {string}
     * @memberof EditAptosContactRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EditAptosContactRequest
     */
    type: EditAptosContactRequestTypeEnum;
    /**
     * 
     * @type {Array<AptosChainUniqueId>}
     * @memberof EditAptosContactRequest
     */
    chains?: Array<AptosChainUniqueId>;
    /**
     * 
     * @type {Array<AptosAssetIdentifierRequest>}
     * @memberof EditAptosContactRequest
     */
    assetsIdentifiers?: Array<AptosAssetIdentifierRequest>;
}


/**
 * @export
 */
export const EditAptosContactRequestTypeEnum = {
    aptos: 'aptos'
} as const;
export type EditAptosContactRequestTypeEnum = typeof EditAptosContactRequestTypeEnum[keyof typeof EditAptosContactRequestTypeEnum];


/**
 * Check if a given object implements the EditAptosContactRequest interface.
 */
export function instanceOfEditAptosContactRequest(value: object): value is EditAptosContactRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function EditAptosContactRequestFromJSON(json: any): EditAptosContactRequest {
    return EditAptosContactRequestFromJSONTyped(json, false);
}

export function EditAptosContactRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditAptosContactRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'chains': json['chains'] == null ? undefined : ((json['chains'] as Array<any>).map(AptosChainUniqueIdFromJSON)),
        'assetsIdentifiers': json['assets_identifiers'] == null ? undefined : ((json['assets_identifiers'] as Array<any>).map(AptosAssetIdentifierRequestFromJSON)),
    };
}

export function EditAptosContactRequestToJSON(json: any): EditAptosContactRequest {
    return EditAptosContactRequestToJSONTyped(json, false);
}

export function EditAptosContactRequestToJSONTyped(value?: EditAptosContactRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'chains': value['chains'] == null ? undefined : ((value['chains'] as Array<any>).map(AptosChainUniqueIdToJSON)),
        'assets_identifiers': value['assetsIdentifiers'] == null ? undefined : ((value['assetsIdentifiers'] as Array<any>).map(AptosAssetIdentifierRequestToJSON)),
    };
}

