/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnrichedEvmChain } from './EnrichedEvmChain';
import {
    EnrichedEvmChainFromJSON,
    EnrichedEvmChainFromJSONTyped,
    EnrichedEvmChainToJSON,
    EnrichedEvmChainToJSONTyped,
} from './EnrichedEvmChain';
import type { EnrichedEvmAddress } from './EnrichedEvmAddress';
import {
    EnrichedEvmAddressFromJSON,
    EnrichedEvmAddressFromJSONTyped,
    EnrichedEvmAddressToJSON,
    EnrichedEvmAddressToJSONTyped,
} from './EnrichedEvmAddress';

/**
 * 
 * @export
 * @interface EnrichedEvmErc1155AssetIdentifier
 */
export interface EnrichedEvmErc1155AssetIdentifier {
    /**
     * 
     * @type {EnrichedEvmChain}
     * @memberof EnrichedEvmErc1155AssetIdentifier
     */
    chain: EnrichedEvmChain;
    /**
     * 
     * @type {string}
     * @memberof EnrichedEvmErc1155AssetIdentifier
     */
    type: EnrichedEvmErc1155AssetIdentifierTypeEnum;
    /**
     * 
     * @type {EnrichedEvmAddress}
     * @memberof EnrichedEvmErc1155AssetIdentifier
     */
    token: EnrichedEvmAddress;
    /**
     * 
     * @type {string}
     * @memberof EnrichedEvmErc1155AssetIdentifier
     */
    tokenId: string;
}


/**
 * @export
 */
export const EnrichedEvmErc1155AssetIdentifierTypeEnum = {
    erc1155: 'erc1155'
} as const;
export type EnrichedEvmErc1155AssetIdentifierTypeEnum = typeof EnrichedEvmErc1155AssetIdentifierTypeEnum[keyof typeof EnrichedEvmErc1155AssetIdentifierTypeEnum];


/**
 * Check if a given object implements the EnrichedEvmErc1155AssetIdentifier interface.
 */
export function instanceOfEnrichedEvmErc1155AssetIdentifier(value: object): value is EnrichedEvmErc1155AssetIdentifier {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('tokenId' in value) || value['tokenId'] === undefined) return false;
    return true;
}

export function EnrichedEvmErc1155AssetIdentifierFromJSON(json: any): EnrichedEvmErc1155AssetIdentifier {
    return EnrichedEvmErc1155AssetIdentifierFromJSONTyped(json, false);
}

export function EnrichedEvmErc1155AssetIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrichedEvmErc1155AssetIdentifier {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': EnrichedEvmChainFromJSON(json['chain']),
        'type': json['type'],
        'token': EnrichedEvmAddressFromJSON(json['token']),
        'tokenId': json['token_id'],
    };
}

export function EnrichedEvmErc1155AssetIdentifierToJSON(json: any): EnrichedEvmErc1155AssetIdentifier {
    return EnrichedEvmErc1155AssetIdentifierToJSONTyped(json, false);
}

export function EnrichedEvmErc1155AssetIdentifierToJSONTyped(value?: EnrichedEvmErc1155AssetIdentifier | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': EnrichedEvmChainToJSON(value['chain']),
        'type': value['type'],
        'token': EnrichedEvmAddressToJSON(value['token']),
        'token_id': value['tokenId'],
    };
}

