/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EnrichedAptosChain } from './EnrichedAptosChain';
import {
    instanceOfEnrichedAptosChain,
    EnrichedAptosChainFromJSON,
    EnrichedAptosChainFromJSONTyped,
    EnrichedAptosChainToJSON,
} from './EnrichedAptosChain';
import type { EnrichedCosmosChain } from './EnrichedCosmosChain';
import {
    instanceOfEnrichedCosmosChain,
    EnrichedCosmosChainFromJSON,
    EnrichedCosmosChainFromJSONTyped,
    EnrichedCosmosChainToJSON,
} from './EnrichedCosmosChain';
import type { EnrichedEvmChain } from './EnrichedEvmChain';
import {
    instanceOfEnrichedEvmChain,
    EnrichedEvmChainFromJSON,
    EnrichedEvmChainFromJSONTyped,
    EnrichedEvmChainToJSON,
} from './EnrichedEvmChain';
import type { EnrichedExchangeChain } from './EnrichedExchangeChain';
import {
    instanceOfEnrichedExchangeChain,
    EnrichedExchangeChainFromJSON,
    EnrichedExchangeChainFromJSONTyped,
    EnrichedExchangeChainToJSON,
} from './EnrichedExchangeChain';
import type { EnrichedSolanaChain } from './EnrichedSolanaChain';
import {
    instanceOfEnrichedSolanaChain,
    EnrichedSolanaChainFromJSON,
    EnrichedSolanaChainFromJSONTyped,
    EnrichedSolanaChainToJSON,
} from './EnrichedSolanaChain';
import type { EnrichedStacksChain } from './EnrichedStacksChain';
import {
    instanceOfEnrichedStacksChain,
    EnrichedStacksChainFromJSON,
    EnrichedStacksChainFromJSONTyped,
    EnrichedStacksChainToJSON,
} from './EnrichedStacksChain';
import type { EnrichedStarknetChain } from './EnrichedStarknetChain';
import {
    instanceOfEnrichedStarknetChain,
    EnrichedStarknetChainFromJSON,
    EnrichedStarknetChainFromJSONTyped,
    EnrichedStarknetChainToJSON,
} from './EnrichedStarknetChain';
import type { EnrichedSuiChain } from './EnrichedSuiChain';
import {
    instanceOfEnrichedSuiChain,
    EnrichedSuiChainFromJSON,
    EnrichedSuiChainFromJSONTyped,
    EnrichedSuiChainToJSON,
} from './EnrichedSuiChain';
import type { EnrichedTonChain } from './EnrichedTonChain';
import {
    instanceOfEnrichedTonChain,
    EnrichedTonChainFromJSON,
    EnrichedTonChainFromJSONTyped,
    EnrichedTonChainToJSON,
} from './EnrichedTonChain';
import type { EnrichedTronChain } from './EnrichedTronChain';
import {
    instanceOfEnrichedTronChain,
    EnrichedTronChainFromJSON,
    EnrichedTronChainFromJSONTyped,
    EnrichedTronChainToJSON,
} from './EnrichedTronChain';
import type { EnrichedUtxoChain } from './EnrichedUtxoChain';
import {
    instanceOfEnrichedUtxoChain,
    EnrichedUtxoChainFromJSON,
    EnrichedUtxoChainFromJSONTyped,
    EnrichedUtxoChainToJSON,
} from './EnrichedUtxoChain';

/**
 * @type EnrichedChain
 * 
 * @export
 */
export type EnrichedChain = { chainType: 'aptos' } & EnrichedAptosChain | { chainType: 'cosmos' } & EnrichedCosmosChain | { chainType: 'evm' } & EnrichedEvmChain | { chainType: 'exchange' } & EnrichedExchangeChain | { chainType: 'solana' } & EnrichedSolanaChain | { chainType: 'stacks' } & EnrichedStacksChain | { chainType: 'starknet' } & EnrichedStarknetChain | { chainType: 'sui' } & EnrichedSuiChain | { chainType: 'ton' } & EnrichedTonChain | { chainType: 'tron' } & EnrichedTronChain | { chainType: 'utxo' } & EnrichedUtxoChain;

export function EnrichedChainFromJSON(json: any): EnrichedChain {
    return EnrichedChainFromJSONTyped(json, false);
}

export function EnrichedChainFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrichedChain {
    if (json == null) {
        return json;
    }
    switch (json['chain_type']) {
        case 'aptos':
            return Object.assign({}, EnrichedAptosChainFromJSONTyped(json, true), { chainType: 'aptos' } as const);
        case 'cosmos':
            return Object.assign({}, EnrichedCosmosChainFromJSONTyped(json, true), { chainType: 'cosmos' } as const);
        case 'evm':
            return Object.assign({}, EnrichedEvmChainFromJSONTyped(json, true), { chainType: 'evm' } as const);
        case 'exchange':
            return Object.assign({}, EnrichedExchangeChainFromJSONTyped(json, true), { chainType: 'exchange' } as const);
        case 'solana':
            return Object.assign({}, EnrichedSolanaChainFromJSONTyped(json, true), { chainType: 'solana' } as const);
        case 'stacks':
            return Object.assign({}, EnrichedStacksChainFromJSONTyped(json, true), { chainType: 'stacks' } as const);
        case 'starknet':
            return Object.assign({}, EnrichedStarknetChainFromJSONTyped(json, true), { chainType: 'starknet' } as const);
        case 'sui':
            return Object.assign({}, EnrichedSuiChainFromJSONTyped(json, true), { chainType: 'sui' } as const);
        case 'ton':
            return Object.assign({}, EnrichedTonChainFromJSONTyped(json, true), { chainType: 'ton' } as const);
        case 'tron':
            return Object.assign({}, EnrichedTronChainFromJSONTyped(json, true), { chainType: 'tron' } as const);
        case 'utxo':
            return Object.assign({}, EnrichedUtxoChainFromJSONTyped(json, true), { chainType: 'utxo' } as const);
        default:
            throw new Error(`No variant of EnrichedChain exists with 'chainType=${json['chainType']}'`);
    }
}

export function EnrichedChainToJSON(json: any): any {
    return EnrichedChainToJSONTyped(json, false);
}

export function EnrichedChainToJSONTyped(value?: EnrichedChain | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['chainType']) {
        case 'aptos':
            return Object.assign({}, EnrichedAptosChainToJSON(value), { chainType: 'aptos' } as const);
        case 'cosmos':
            return Object.assign({}, EnrichedCosmosChainToJSON(value), { chainType: 'cosmos' } as const);
        case 'evm':
            return Object.assign({}, EnrichedEvmChainToJSON(value), { chainType: 'evm' } as const);
        case 'exchange':
            return Object.assign({}, EnrichedExchangeChainToJSON(value), { chainType: 'exchange' } as const);
        case 'solana':
            return Object.assign({}, EnrichedSolanaChainToJSON(value), { chainType: 'solana' } as const);
        case 'stacks':
            return Object.assign({}, EnrichedStacksChainToJSON(value), { chainType: 'stacks' } as const);
        case 'starknet':
            return Object.assign({}, EnrichedStarknetChainToJSON(value), { chainType: 'starknet' } as const);
        case 'sui':
            return Object.assign({}, EnrichedSuiChainToJSON(value), { chainType: 'sui' } as const);
        case 'ton':
            return Object.assign({}, EnrichedTonChainToJSON(value), { chainType: 'ton' } as const);
        case 'tron':
            return Object.assign({}, EnrichedTronChainToJSON(value), { chainType: 'tron' } as const);
        case 'utxo':
            return Object.assign({}, EnrichedUtxoChainToJSON(value), { chainType: 'utxo' } as const);
        default:
            throw new Error(`No variant of EnrichedChain exists with 'chainType=${value['chainType']}'`);
    }

}

