/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { StarknetChainUniqueId } from './StarknetChainUniqueId';
import {
    StarknetChainUniqueIdFromJSON,
} from './StarknetChainUniqueId';
import type { BlockchainExplorer } from './BlockchainExplorer';
import {
    BlockchainExplorerFromJSON,
} from './BlockchainExplorer';

/**
 * 
 * @export
 * @interface EnrichedStarknetChain
 */
export interface EnrichedStarknetChain {
    /**
     * The type of the chain.
     * @type {EnrichedStarknetChainChainTypeEnum}
     * @memberof EnrichedStarknetChain
     */
    chainType: EnrichedStarknetChainChainTypeEnum;
    /**
     * The type of the Starknet-based chain.
     * @type {StarknetChainUniqueId}
     * @memberof EnrichedStarknetChain
     */
    uniqueId: StarknetChainUniqueId;
    /**
     * The full blockchain name.
     * @type {string}
     * @memberof EnrichedStarknetChain
     */
    name: string;
    /**
     * The native currency symbol.
     * @type {string}
     * @memberof EnrichedStarknetChain
     */
    nativeCurrencySymbol: string;
    /**
     * The native currency name.
     * @type {string}
     * @memberof EnrichedStarknetChain
     */
    nativeCurrencyName: string;
    /**
     * 
     * @type {BlockchainExplorer}
     * @memberof EnrichedStarknetChain
     */
    blockchainExplorer?: BlockchainExplorer;
    /**
     * The logo URL of the chain.
     * @type {string}
     * @memberof EnrichedStarknetChain
     */
    logoUrl: string;
    /**
     * Whether the chain is on a testnet.
     * @type {boolean}
     * @memberof EnrichedStarknetChain
     */
    isTestnet: boolean;
    /**
     * Whether the chain is enabled.
     * @type {boolean}
     * @memberof EnrichedStarknetChain
     */
    isEnabled: boolean;
}


/**
 * 
 */
const EnrichedStarknetChainChainTypeEnum = {
    starknet: 'starknet'
} as const;
type EnrichedStarknetChainChainTypeEnum = typeof EnrichedStarknetChainChainTypeEnum[keyof typeof EnrichedStarknetChainChainTypeEnum];

export function EnrichedStarknetChainFromJSON(json: any): EnrichedStarknetChain {
    return EnrichedStarknetChainFromJSONTyped(json, false);
}

export function EnrichedStarknetChainFromJSONTyped(json: any, _ignoreDiscriminator: boolean): EnrichedStarknetChain {
    if (json == null) {
        return json;
    }
    return {
        
        'chainType': json['chain_type'],
        'uniqueId': StarknetChainUniqueIdFromJSON(json['unique_id']),
        'name': json['name'],
        'nativeCurrencySymbol': json['native_currency_symbol'],
        'nativeCurrencyName': json['native_currency_name'],
        'blockchainExplorer': json['blockchain_explorer'] == null ? undefined : BlockchainExplorerFromJSON(json['blockchain_explorer']),
        'logoUrl': json['logo_url'],
        'isTestnet': json['is_testnet'],
        'isEnabled': json['is_enabled'],
    };
}
