/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EnrichedEvmChain } from './EnrichedEvmChain';
import {
    EnrichedEvmChainFromJSON,
} from './EnrichedEvmChain';
import type { EnrichedEvmAddress } from './EnrichedEvmAddress';
import {
    EnrichedEvmAddressFromJSON,
} from './EnrichedEvmAddress';

/**
 * 
 * @export
 * @interface EnrichedEvmErc20AssetIdentifier
 */
export interface EnrichedEvmErc20AssetIdentifier {
    /**
     * 
     * @type {EnrichedEvmChain}
     * @memberof EnrichedEvmErc20AssetIdentifier
     */
    chain: EnrichedEvmChain;
    /**
     * 
     * @type {string}
     * @memberof EnrichedEvmErc20AssetIdentifier
     */
    type: EnrichedEvmErc20AssetIdentifierTypeEnum;
    /**
     * 
     * @type {EnrichedEvmAddress}
     * @memberof EnrichedEvmErc20AssetIdentifier
     */
    token: EnrichedEvmAddress;
}


/**
 * 
 */
const EnrichedEvmErc20AssetIdentifierTypeEnum = {
    erc20: 'erc20'
} as const;
type EnrichedEvmErc20AssetIdentifierTypeEnum = typeof EnrichedEvmErc20AssetIdentifierTypeEnum[keyof typeof EnrichedEvmErc20AssetIdentifierTypeEnum];

export function EnrichedEvmErc20AssetIdentifierFromJSONTyped(json: any, _ignoreDiscriminator: boolean): EnrichedEvmErc20AssetIdentifier {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': EnrichedEvmChainFromJSON(json['chain']),
        'type': json['type'],
        'token': EnrichedEvmAddressFromJSON(json['token']),
    };
}
