/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { VaultRef } from './VaultRef';
import {
    VaultRefFromJSON,
} from './VaultRef';
import type { SolanaContractMetadata } from './SolanaContractMetadata';
import {
    SolanaContractMetadataFromJSON,
} from './SolanaContractMetadata';
import type { ContactRef } from './ContactRef';
import {
    ContactRefFromJSON,
} from './ContactRef';

/**
 * 
 * @export
 * @interface EnrichedSolanaAddress
 */
export interface EnrichedSolanaAddress {
    /**
     * The vault corresponding to this address.
     * @type {VaultRef}
     * @memberof EnrichedSolanaAddress
     */
    vault?: VaultRef;
    /**
     * The URL of a blockchain explorer that provides real-time information about the address.
     * @type {string}
     * @memberof EnrichedSolanaAddress
     */
    explorerUrl?: string;
    /**
     * The contact details of this address.
     * @type {ContactRef}
     * @memberof EnrichedSolanaAddress
     */
    contact?: ContactRef;
    /**
     * 
     * @type {EnrichedSolanaAddressTypeEnum}
     * @memberof EnrichedSolanaAddress
     */
    type: EnrichedSolanaAddressTypeEnum;
    /**
     * The Solana address represented in Base58 format.
     * @type {string}
     * @memberof EnrichedSolanaAddress
     */
    address: string;
    /**
     * The details of the contract corresponding to this address.
     * @type {SolanaContractMetadata}
     * @memberof EnrichedSolanaAddress
     */
    contract?: SolanaContractMetadata;
}


/**
 * 
 */
const EnrichedSolanaAddressTypeEnum = {
    Solana: 'solana'
} as const;
type EnrichedSolanaAddressTypeEnum = typeof EnrichedSolanaAddressTypeEnum[keyof typeof EnrichedSolanaAddressTypeEnum];

export function EnrichedSolanaAddressFromJSON(json: any): EnrichedSolanaAddress {
    return EnrichedSolanaAddressFromJSONTyped(json, false);
}

export function EnrichedSolanaAddressFromJSONTyped(json: any, _ignoreDiscriminator: boolean): EnrichedSolanaAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'vault': json['vault'] == null ? undefined : VaultRefFromJSON(json['vault']),
        'explorerUrl': json['explorer_url'] == null ? undefined : json['explorer_url'],
        'contact': json['contact'] == null ? undefined : ContactRefFromJSON(json['contact']),
        'type': json['type'],
        'address': json['address'],
        'contract': json['contract'] == null ? undefined : SolanaContractMetadataFromJSON(json['contract']),
    };
}
