/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Erc20 } from './Erc20';
import {
    Erc20FromJSON,
    Erc20FromJSONTyped,
    Erc20ToJSON,
    Erc20ToJSONTyped,
} from './Erc20';
import type { Dapp } from './Dapp';
import {
    DappFromJSON,
    DappFromJSONTyped,
    DappToJSON,
    DappToJSONTyped,
} from './Dapp';

/**
 * 
 * @export
 * @interface Erc20Contract
 */
export interface Erc20Contract {
    /**
     * 
     * @type {string}
     * @memberof Erc20Contract
     */
    name?: string;
    /**
     * 
     * @type {Dapp}
     * @memberof Erc20Contract
     */
    dapp?: Dapp;
    /**
     * 
     * @type {boolean}
     * @memberof Erc20Contract
     */
    isVerified: boolean;
    /**
     * 
     * @type {Erc20}
     * @memberof Erc20Contract
     */
    token: Erc20;
}

/**
 * Check if a given object implements the Erc20Contract interface.
 */
export function instanceOfErc20Contract(value: object): value is Erc20Contract {
    if (!('isVerified' in value) || value['isVerified'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function Erc20ContractFromJSON(json: any): Erc20Contract {
    return Erc20ContractFromJSONTyped(json, false);
}

export function Erc20ContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): Erc20Contract {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'dapp': json['dapp'] == null ? undefined : DappFromJSON(json['dapp']),
        'isVerified': json['is_verified'],
        'token': Erc20FromJSON(json['token']),
    };
}

export function Erc20ContractToJSON(json: any): Erc20Contract {
    return Erc20ContractToJSONTyped(json, false);
}

export function Erc20ContractToJSONTyped(value?: Erc20Contract | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'dapp': DappToJSON(value['dapp']),
        'is_verified': value['isVerified'],
        'token': Erc20ToJSON(value['token']),
    };
}

