/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EvmAddress } from './EvmAddress';
import {
    EvmAddressFromJSON,
    EvmAddressFromJSONTyped,
    EvmAddressToJSON,
    EvmAddressToJSONTyped,
} from './EvmAddress';

/**
 * 
 * @export
 * @interface Erc20
 */
export interface Erc20 {
    /**
     * 
     * @type {EvmAddress}
     * @memberof Erc20
     */
    address: EvmAddress;
    /**
     * 
     * @type {string}
     * @memberof Erc20
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Erc20
     */
    symbol: string;
    /**
     * 
     * @type {string}
     * @memberof Erc20
     */
    type: Erc20TypeEnum;
    /**
     * 
     * @type {number}
     * @memberof Erc20
     */
    decimals: number;
    /**
     * 
     * @type {string}
     * @memberof Erc20
     */
    logoUrl?: string;
}


/**
 * @export
 */
export const Erc20TypeEnum = {
    erc20: 'erc20'
} as const;
export type Erc20TypeEnum = typeof Erc20TypeEnum[keyof typeof Erc20TypeEnum];


/**
 * Check if a given object implements the Erc20 interface.
 */
export function instanceOfErc20(value: object): value is Erc20 {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    return true;
}

export function Erc20FromJSON(json: any): Erc20 {
    return Erc20FromJSONTyped(json, false);
}

export function Erc20FromJSONTyped(json: any, ignoreDiscriminator: boolean): Erc20 {
    if (json == null) {
        return json;
    }
    return {
        
        'address': EvmAddressFromJSON(json['address']),
        'name': json['name'],
        'symbol': json['symbol'],
        'type': json['type'],
        'decimals': json['decimals'],
        'logoUrl': json['logo_url'] == null ? undefined : json['logo_url'],
    };
}

export function Erc20ToJSON(json: any): Erc20 {
    return Erc20ToJSONTyped(json, false);
}

export function Erc20ToJSONTyped(value?: Erc20 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': EvmAddressToJSON(value['address']),
        'name': value['name'],
        'symbol': value['symbol'],
        'type': value['type'],
        'decimals': value['decimals'],
        'logo_url': value['logoUrl'],
    };
}

