/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EvmChain } from './EvmChain';
import {
    EvmChainFromJSON,
    EvmChainFromJSONTyped,
    EvmChainToJSON,
} from './EvmChain';

/**
 * 
 * @export
 * @interface EvmAddress
 */
export interface EvmAddress {
    /**
     * 
     * @type {EvmChain}
     * @memberof EvmAddress
     */
    chain: EvmChain;
    /**
     * 
     * @type {string}
     * @memberof EvmAddress
     */
    hexRepr: string;
}

/**
 * Check if a given object implements the EvmAddress interface.
 */
export function instanceOfEvmAddress(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chain" in value;
    isInstance = isInstance && "hexRepr" in value;

    return isInstance;
}

export function EvmAddressFromJSON(json: any): EvmAddress {
    return EvmAddressFromJSONTyped(json, false);
}

export function EvmAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chain': EvmChainFromJSON(json['chain']),
        'hexRepr': json['hex_repr'],
    };
}

export function EvmAddressToJSON(value?: EvmAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chain': EvmChainToJSON(value.chain),
        'hex_repr': value.hexRepr,
    };
}

