/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EvmAssetIdentifierDetails } from './EvmAssetIdentifierDetails';
import {
    EvmAssetIdentifierDetailsFromJSON,
    EvmAssetIdentifierDetailsFromJSONTyped,
    EvmAssetIdentifierDetailsToJSON,
    EvmAssetIdentifierDetailsToJSONTyped,
} from './EvmAssetIdentifierDetails';

/**
 * 
 * @export
 * @interface EvmAssetIdentifierRequest
 */
export interface EvmAssetIdentifierRequest {
    /**
     * 
     * @type {string}
     * @memberof EvmAssetIdentifierRequest
     */
    type: EvmAssetIdentifierRequestTypeEnum;
    /**
     * 
     * @type {EvmAssetIdentifierDetails}
     * @memberof EvmAssetIdentifierRequest
     */
    details: EvmAssetIdentifierDetails;
}


/**
 * @export
 */
export const EvmAssetIdentifierRequestTypeEnum = {
    evm: 'evm'
} as const;
export type EvmAssetIdentifierRequestTypeEnum = typeof EvmAssetIdentifierRequestTypeEnum[keyof typeof EvmAssetIdentifierRequestTypeEnum];


/**
 * Check if a given object implements the EvmAssetIdentifierRequest interface.
 */
export function instanceOfEvmAssetIdentifierRequest(value: object): value is EvmAssetIdentifierRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function EvmAssetIdentifierRequestFromJSON(json: any): EvmAssetIdentifierRequest {
    return EvmAssetIdentifierRequestFromJSONTyped(json, false);
}

export function EvmAssetIdentifierRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvmAssetIdentifierRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'details': EvmAssetIdentifierDetailsFromJSON(json['details']),
    };
}

export function EvmAssetIdentifierRequestToJSON(json: any): EvmAssetIdentifierRequest {
    return EvmAssetIdentifierRequestToJSONTyped(json, false);
}

export function EvmAssetIdentifierRequestToJSONTyped(value?: EvmAssetIdentifierRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'details': EvmAssetIdentifierDetailsToJSON(value['details']),
    };
}

