/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EnrichedEvmChain } from './EnrichedEvmChain';
import {
    EnrichedEvmChainFromJSON,
    EnrichedEvmChainFromJSONTyped,
    EnrichedEvmChainToJSON,
} from './EnrichedEvmChain';

/**
 * 
 * @export
 * @interface EVMAddressBookContactAddress
 */
export interface EVMAddressBookContactAddress {
    /**
     * 
     * @type {string}
     * @memberof EVMAddressBookContactAddress
     */
    chainType: EVMAddressBookContactAddressChainTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EVMAddressBookContactAddress
     */
    address: string;
    /**
     * 
     * @type {Array<EnrichedEvmChain>}
     * @memberof EVMAddressBookContactAddress
     */
    chains: Array<EnrichedEvmChain>;
}


/**
 * @export
 */
export const EVMAddressBookContactAddressChainTypeEnum = {
    evm: 'evm'
} as const;
export type EVMAddressBookContactAddressChainTypeEnum = typeof EVMAddressBookContactAddressChainTypeEnum[keyof typeof EVMAddressBookContactAddressChainTypeEnum];


/**
 * Check if a given object implements the EVMAddressBookContactAddress interface.
 */
export function instanceOfEVMAddressBookContactAddress(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chainType" in value;
    isInstance = isInstance && "address" in value;
    isInstance = isInstance && "chains" in value;

    return isInstance;
}

export function EVMAddressBookContactAddressFromJSON(json: any): EVMAddressBookContactAddress {
    return EVMAddressBookContactAddressFromJSONTyped(json, false);
}

export function EVMAddressBookContactAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): EVMAddressBookContactAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chainType': json['chain_type'],
        'address': json['address'],
        'chains': ((json['chains'] as Array<any>).map(EnrichedEvmChainFromJSON)),
    };
}

export function EVMAddressBookContactAddressToJSON(value?: EVMAddressBookContactAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chain_type': value.chainType,
        'address': value.address,
        'chains': ((value.chains as Array<any>).map(EnrichedEvmChainToJSON)),
    };
}

