/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EvmContractMetadataToken } from './EvmContractMetadataToken';
import {
    EvmContractMetadataTokenFromJSON,
} from './EvmContractMetadataToken';
import type { Dapp } from './Dapp';
import {
    DappFromJSON,
} from './Dapp';

/**
 * 
 * @export
 * @interface EvmContractMetadata
 */
export interface EvmContractMetadata {
    /**
     * 
     * @type {string}
     * @memberof EvmContractMetadata
     */
    name?: string;
    /**
     * 
     * @type {Dapp}
     * @memberof EvmContractMetadata
     */
    dapp?: Dapp;
    /**
     * 
     * @type {boolean}
     * @memberof EvmContractMetadata
     */
    isVerified: boolean;
    /**
     * 
     * @type {EvmContractMetadataToken}
     * @memberof EvmContractMetadata
     */
    token?: EvmContractMetadataToken;
}

export function EvmContractMetadataFromJSON(json: any): EvmContractMetadata {
    return EvmContractMetadataFromJSONTyped(json, false);
}

function EvmContractMetadataFromJSONTyped(json: any, _ignoreDiscriminator: boolean): EvmContractMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'dapp': json['dapp'] == null ? undefined : DappFromJSON(json['dapp']),
        'isVerified': json['is_verified'],
        'token': json['token'] == null ? undefined : EvmContractMetadataTokenFromJSON(json['token']),
    };
}

