/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EvmAllowanceEffect } from './EvmAllowanceEffect';
import {
    EvmAllowanceEffectFromJSON,
} from './EvmAllowanceEffect';
import type { EvmBalanceChangeEffect } from './EvmBalanceChangeEffect';
import {
    EvmBalanceChangeEffectFromJSON,
} from './EvmBalanceChangeEffect';
import type { EvmBridgesEffect } from './EvmBridgesEffect';
import {
    EvmBridgesEffectFromJSON,
} from './EvmBridgesEffect';
import type { EvmTransferEffect } from './EvmTransferEffect';
import {
    EvmTransferEffectFromJSON,
} from './EvmTransferEffect';

/**
 * 
 * @export
 * @interface EvmEffectsBase
 */
export interface EvmEffectsBase {
    /**
     * 
     * @type {Array<EvmBalanceChangeEffect>}
     * @memberof EvmEffectsBase
     */
    balanceChanges: Array<EvmBalanceChangeEffect>;
    /**
     * 
     * @type {Array<EvmTransferEffect>}
     * @memberof EvmEffectsBase
     */
    transfers: Array<EvmTransferEffect>;
    /**
     * 
     * @type {Array<EvmAllowanceEffect>}
     * @memberof EvmEffectsBase
     */
    allowances?: Array<EvmAllowanceEffect>;
    /**
     * 
     * @type {Array<EvmBridgesEffect>}
     * @memberof EvmEffectsBase
     */
    bridges?: Array<EvmBridgesEffect>;
}

export function EvmEffectsBaseFromJSON(json: any): EvmEffectsBase {
    return EvmEffectsBaseFromJSONTyped(json, false);
}

function EvmEffectsBaseFromJSONTyped(json: any, _ignoreDiscriminator: boolean): EvmEffectsBase {
    if (json == null) {
        return json;
    }
    return {
        
        'balanceChanges': ((json['balance_changes'] as Array<any>).map(EvmBalanceChangeEffectFromJSON)),
        'transfers': ((json['transfers'] as Array<any>).map(EvmTransferEffectFromJSON)),
        'allowances': json['allowances'] == null ? undefined : ((json['allowances'] as Array<any>).map(EvmAllowanceEffectFromJSON)),
        'bridges': json['bridges'] == null ? undefined : ((json['bridges'] as Array<any>).map(EvmBridgesEffectFromJSON)),
    };
}

