/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExposureType = {
    direct: 'direct',
    indirect: 'indirect'
} as const;
export type ExposureType = typeof ExposureType[keyof typeof ExposureType];


export function instanceOfExposureType(value: any): boolean {
    for (const key in ExposureType) {
        if (Object.prototype.hasOwnProperty.call(ExposureType, key)) {
            if (ExposureType[key as keyof typeof ExposureType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ExposureTypeFromJSON(json: any): ExposureType {
    return ExposureTypeFromJSONTyped(json, false);
}

export function ExposureTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExposureType {
    return json as ExposureType;
}

export function ExposureTypeToJSON(value?: ExposureType | null): any {
    return value as any;
}

export function ExposureTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ExposureType {
    return value as ExposureType;
}

