/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FiatCurrencySymbol = {
    usd: 'usd'
} as const;
export type FiatCurrencySymbol = typeof FiatCurrencySymbol[keyof typeof FiatCurrencySymbol];


export function instanceOfFiatCurrencySymbol(value: any): boolean {
    for (const key in FiatCurrencySymbol) {
        if (Object.prototype.hasOwnProperty.call(FiatCurrencySymbol, key)) {
            if (FiatCurrencySymbol[key as keyof typeof FiatCurrencySymbol] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FiatCurrencySymbolFromJSON(json: any): FiatCurrencySymbol {
    return FiatCurrencySymbolFromJSONTyped(json, false);
}

export function FiatCurrencySymbolFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiatCurrencySymbol {
    return json as FiatCurrencySymbol;
}

export function FiatCurrencySymbolToJSON(value?: FiatCurrencySymbol | null): any {
    return value as any;
}

export function FiatCurrencySymbolToJSONTyped(value: any, ignoreDiscriminator: boolean): FiatCurrencySymbol {
    return value as FiatCurrencySymbol;
}

