/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMembershipOrganizationsResponse
 */
export interface GetMembershipOrganizationsResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetMembershipOrganizationsResponse
     */
    authzeroIds: Array<string>;
}

/**
 * Check if a given object implements the GetMembershipOrganizationsResponse interface.
 */
export function instanceOfGetMembershipOrganizationsResponse(value: object): value is GetMembershipOrganizationsResponse {
    if (!('authzeroIds' in value) || value['authzeroIds'] === undefined) return false;
    return true;
}

export function GetMembershipOrganizationsResponseFromJSON(json: any): GetMembershipOrganizationsResponse {
    return GetMembershipOrganizationsResponseFromJSONTyped(json, false);
}

export function GetMembershipOrganizationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMembershipOrganizationsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'authzeroIds': json['authzero_ids'],
    };
}

export function GetMembershipOrganizationsResponseToJSON(json: any): GetMembershipOrganizationsResponse {
    return GetMembershipOrganizationsResponseToJSONTyped(json, false);
}

export function GetMembershipOrganizationsResponseToJSONTyped(value?: GetMembershipOrganizationsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authzero_ids': value['authzeroIds'],
    };
}

