/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetNextApiSignerTransactionResponseV2Body } from './GetNextApiSignerTransactionResponseV2Body';
import {
    GetNextApiSignerTransactionResponseV2BodyFromJSON,
    GetNextApiSignerTransactionResponseV2BodyFromJSONTyped,
    GetNextApiSignerTransactionResponseV2BodyToJSON,
} from './GetNextApiSignerTransactionResponseV2Body';

/**
 * 
 * @export
 * @interface GetNextApiSignerTransactionResponseV2
 */
export interface GetNextApiSignerTransactionResponseV2 {
    /**
     * 
     * @type {GetNextApiSignerTransactionResponseV2Body}
     * @memberof GetNextApiSignerTransactionResponseV2
     */
    body?: GetNextApiSignerTransactionResponseV2Body;
}

/**
 * Check if a given object implements the GetNextApiSignerTransactionResponseV2 interface.
 */
export function instanceOfGetNextApiSignerTransactionResponseV2(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetNextApiSignerTransactionResponseV2FromJSON(json: any): GetNextApiSignerTransactionResponseV2 {
    return GetNextApiSignerTransactionResponseV2FromJSONTyped(json, false);
}

export function GetNextApiSignerTransactionResponseV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNextApiSignerTransactionResponseV2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': !exists(json, 'body') ? undefined : GetNextApiSignerTransactionResponseV2BodyFromJSON(json['body']),
    };
}

export function GetNextApiSignerTransactionResponseV2ToJSON(value?: GetNextApiSignerTransactionResponseV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': GetNextApiSignerTransactionResponseV2BodyToJSON(value.body),
    };
}

