/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GasPriorityLevel } from './GasPriorityLevel';
import {
    GasPriorityLevelFromJSON,
} from './GasPriorityLevel';

/**
 * 
 * @export
 * @interface LegacyGas
 */
export interface LegacyGas {
    /**
     * 
     * @type {string}
     * @memberof LegacyGas
     */
    price: string;
    /**
     * 
     * @type {GasPriorityLevel}
     * @memberof LegacyGas
     */
    priority: GasPriorityLevel;
    /**
     * 
     * @type {string}
     * @memberof LegacyGas
     */
    limit: string;
    /**
     * 
     * @type {string}
     * @memberof LegacyGas
     */
    type: LegacyGasTypeEnum;
}


/**
 * @export
 */
export const LegacyGasTypeEnum = {
    legacy: 'legacy'
} as const;
export type LegacyGasTypeEnum = typeof LegacyGasTypeEnum[keyof typeof LegacyGasTypeEnum];

export function LegacyGasFromJSONTyped(json: any, _ignoreDiscriminator: boolean): LegacyGas {
    if (json == null) {
        return json;
    }
    return {
        
        'price': json['price'],
        'priority': GasPriorityLevelFromJSON(json['priority']),
        'limit': json['limit'],
        'type': json['type'],
    };
}

