/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartialErrorResponse } from './PartialErrorResponse';
import {
    PartialErrorResponseFromJSON,
    PartialErrorResponseFromJSONTyped,
    PartialErrorResponseToJSON,
    PartialErrorResponseToJSONTyped,
} from './PartialErrorResponse';
import type { OrganizationInfo } from './OrganizationInfo';
import {
    OrganizationInfoFromJSON,
    OrganizationInfoFromJSONTyped,
    OrganizationInfoToJSON,
    OrganizationInfoToJSONTyped,
} from './OrganizationInfo';

/**
 * 
 * @export
 * @interface ListOrganizationsResponse
 */
export interface ListOrganizationsResponse {
    /**
     * 
     * @type {PartialErrorResponse}
     * @memberof ListOrganizationsResponse
     */
    partialError?: PartialErrorResponse;
    /**
     * 
     * @type {number}
     * @memberof ListOrganizationsResponse
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof ListOrganizationsResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ListOrganizationsResponse
     */
    size: number;
    /**
     * 
     * @type {Array<OrganizationInfo>}
     * @memberof ListOrganizationsResponse
     */
    organizations: Array<OrganizationInfo>;
}

/**
 * Check if a given object implements the ListOrganizationsResponse interface.
 */
export function instanceOfListOrganizationsResponse(value: object): value is ListOrganizationsResponse {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('organizations' in value) || value['organizations'] === undefined) return false;
    return true;
}

export function ListOrganizationsResponseFromJSON(json: any): ListOrganizationsResponse {
    return ListOrganizationsResponseFromJSONTyped(json, false);
}

export function ListOrganizationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrganizationsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'partialError': json['partial_error'] == null ? undefined : PartialErrorResponseFromJSON(json['partial_error']),
        'total': json['total'],
        'page': json['page'],
        'size': json['size'],
        'organizations': ((json['organizations'] as Array<any>).map(OrganizationInfoFromJSON)),
    };
}

export function ListOrganizationsResponseToJSON(json: any): ListOrganizationsResponse {
    return ListOrganizationsResponseToJSONTyped(json, false);
}

export function ListOrganizationsResponseToJSONTyped(value?: ListOrganizationsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'partial_error': PartialErrorResponseToJSON(value['partialError']),
        'total': value['total'],
        'page': value['page'],
        'size': value['size'],
        'organizations': ((value['organizations'] as Array<any>).map(OrganizationInfoToJSON)),
    };
}

