/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NextApiSignerTransactionResponseV3Body } from './NextApiSignerTransactionResponseV3Body';
import {
    NextApiSignerTransactionResponseV3BodyFromJSON,
    NextApiSignerTransactionResponseV3BodyFromJSONTyped,
    NextApiSignerTransactionResponseV3BodyToJSON,
    NextApiSignerTransactionResponseV3BodyToJSONTyped,
} from './NextApiSignerTransactionResponseV3Body';

/**
 * 
 * @export
 * @interface NextApiSignerTransactionResponseV3
 */
export interface NextApiSignerTransactionResponseV3 {
    /**
     * 
     * @type {NextApiSignerTransactionResponseV3Body}
     * @memberof NextApiSignerTransactionResponseV3
     */
    body?: NextApiSignerTransactionResponseV3Body;
}

/**
 * Check if a given object implements the NextApiSignerTransactionResponseV3 interface.
 */
export function instanceOfNextApiSignerTransactionResponseV3(value: object): value is NextApiSignerTransactionResponseV3 {
    return true;
}

export function NextApiSignerTransactionResponseV3FromJSON(json: any): NextApiSignerTransactionResponseV3 {
    return NextApiSignerTransactionResponseV3FromJSONTyped(json, false);
}

export function NextApiSignerTransactionResponseV3FromJSONTyped(json: any, ignoreDiscriminator: boolean): NextApiSignerTransactionResponseV3 {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'] == null ? undefined : NextApiSignerTransactionResponseV3BodyFromJSON(json['body']),
    };
}

export function NextApiSignerTransactionResponseV3ToJSON(json: any): NextApiSignerTransactionResponseV3 {
    return NextApiSignerTransactionResponseV3ToJSONTyped(json, false);
}

export function NextApiSignerTransactionResponseV3ToJSONTyped(value?: NextApiSignerTransactionResponseV3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': NextApiSignerTransactionResponseV3BodyToJSON(value['body']),
    };
}

