/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OnboardingType = {
    user: 'user',
    organization: 'organization',
    device: 'device',
    userPendingPinGeneration: 'user_pending_pin_generation',
    devicePendingPinGeneration: 'device_pending_pin_generation'
} as const;
export type OnboardingType = typeof OnboardingType[keyof typeof OnboardingType];


export function OnboardingTypeFromJSON(json: any): OnboardingType {
    return OnboardingTypeFromJSONTyped(json, false);
}

export function OnboardingTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingType {
    return json as OnboardingType;
}

export function OnboardingTypeToJSON(value?: OnboardingType | null): any {
    return value as any;
}

