/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PendingUserChange
 */
export interface PendingUserChange {
    /**
     * 
     * @type {string}
     * @memberof PendingUserChange
     */
    newRole: PendingUserChangeNewRoleEnum;
}


/**
 * @export
 */
export const PendingUserChangeNewRoleEnum = {
    admin: 'admin',
    trader: 'trader'
} as const;
export type PendingUserChangeNewRoleEnum = typeof PendingUserChangeNewRoleEnum[keyof typeof PendingUserChangeNewRoleEnum];


/**
 * Check if a given object implements the PendingUserChange interface.
 */
export function instanceOfPendingUserChange(value: object): value is PendingUserChange {
    if (!('newRole' in value) || value['newRole'] === undefined) return false;
    return true;
}

export function PendingUserChangeFromJSON(json: any): PendingUserChange {
    return PendingUserChangeFromJSONTyped(json, false);
}

export function PendingUserChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingUserChange {
    if (json == null) {
        return json;
    }
    return {
        
        'newRole': json['new_role'],
    };
}

export function PendingUserChangeToJSON(json: any): PendingUserChange {
    return PendingUserChangeToJSONTyped(json, false);
}

export function PendingUserChangeToJSONTyped(value?: PendingUserChange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'new_role': value['newRole'],
    };
}

