/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TransactionRisk } from './TransactionRisk';
import {
    TransactionRiskFromJSON,
} from './TransactionRisk';
import type { SolanaMessageType } from './SolanaMessageType';
import {
    SolanaMessageTypeFromJSON,
} from './SolanaMessageType';
import type { EnrichedSolanaAddress } from './EnrichedSolanaAddress';
import {
    EnrichedSolanaAddressFromJSON,
} from './EnrichedSolanaAddress';
import type { SolanaMessageResult } from './SolanaMessageResult';
import {
    SolanaMessageResultFromJSON,
} from './SolanaMessageResult';
import type { ApprovalRequest } from './ApprovalRequest';
import {
    ApprovalRequestFromJSON,
} from './ApprovalRequest';
import type { EnrichedSolanaChain } from './EnrichedSolanaChain';
import {
    EnrichedSolanaChainFromJSON,
} from './EnrichedSolanaChain';
import type { PredictedSolanaMessageSolanaMessageTypeDetails } from './PredictedSolanaMessageSolanaMessageTypeDetails';
import {
    PredictedSolanaMessageSolanaMessageTypeDetailsFromJSON,
} from './PredictedSolanaMessageSolanaMessageTypeDetails';
import type { PolicyMatch } from './PolicyMatch';
import {
    PolicyMatchFromJSON,
} from './PolicyMatch';

/**
 * 
 * @export
 * @interface PredictedSolanaMessage
 */
export interface PredictedSolanaMessage {
    /**
     * The policy match.
     * @type {PolicyMatch}
     * @memberof PredictedSolanaMessage
     */
    policyMatch?: PolicyMatch;
    /**
     * List of policies matched by the transactions in the batch.
     * @type {Array<PolicyMatch>}
     * @memberof PredictedSolanaMessage
     */
    matchedPolicies: Array<PolicyMatch>;
    /**
     * The approval request.
     * @type {ApprovalRequest}
     * @memberof PredictedSolanaMessage
     */
    approvalRequest?: ApprovalRequest;
    /**
     * The list of risks associated with this transaction.
     * @type {Array<TransactionRisk>}
     * @memberof PredictedSolanaMessage
     */
    risks: Array<TransactionRisk>;
    /**
     * An optional transaction note.
     * @type {string}
     * @memberof PredictedSolanaMessage
     */
    note?: string;
    /**
     * The type of the transaction.
     * @type {PredictedSolanaMessageTypeEnum}
     * @memberof PredictedSolanaMessage
     */
    type: PredictedSolanaMessageTypeEnum;
    /**
     * The details of the chain that this message is on.
     * @type {EnrichedSolanaChain}
     * @memberof PredictedSolanaMessage
     */
    chain: EnrichedSolanaChain;
    /**
     * The sender of the message.
     * @type {EnrichedSolanaAddress}
     * @memberof PredictedSolanaMessage
     */
    sender: EnrichedSolanaAddress;
    /**
     * The type of the Solana message.
     * @type {SolanaMessageType}
     * @memberof PredictedSolanaMessage
     */
    solanaMessageType: SolanaMessageType;
    /**
     * 
     * @type {PredictedSolanaMessageSolanaMessageTypeDetails}
     * @memberof PredictedSolanaMessage
     */
    solanaMessageTypeDetails: PredictedSolanaMessageSolanaMessageTypeDetails;
    /**
     * Simulation is supported only for Fogo session intent messages. Is empty when simulation is not available for the intent type.
     * @type {SolanaMessageResult}
     * @memberof PredictedSolanaMessage
     */
    expectedResult: SolanaMessageResult;
    /**
     * User-friendly formatting of the message to be signed.
     * @type {string}
     * @memberof PredictedSolanaMessage
     */
    messageToDisplay: string;
}


/**
 * 
 */
const PredictedSolanaMessageTypeEnum = {
    solanaMessage: 'solana_message'
} as const;
type PredictedSolanaMessageTypeEnum = typeof PredictedSolanaMessageTypeEnum[keyof typeof PredictedSolanaMessageTypeEnum];

export function PredictedSolanaMessageFromJSONTyped(json: any, _ignoreDiscriminator: boolean): PredictedSolanaMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'policyMatch': json['policy_match'] == null ? undefined : PolicyMatchFromJSON(json['policy_match']),
        'matchedPolicies': ((json['matched_policies'] as Array<any>).map(PolicyMatchFromJSON)),
        'approvalRequest': json['approval_request'] == null ? undefined : ApprovalRequestFromJSON(json['approval_request']),
        'risks': ((json['risks'] as Array<any>).map(TransactionRiskFromJSON)),
        'note': json['note'] == null ? undefined : json['note'],
        'type': json['type'],
        'chain': EnrichedSolanaChainFromJSON(json['chain']),
        'sender': EnrichedSolanaAddressFromJSON(json['sender']),
        'solanaMessageType': SolanaMessageTypeFromJSON(json['solana_message_type']),
        'solanaMessageTypeDetails': PredictedSolanaMessageSolanaMessageTypeDetailsFromJSON(json['solana_message_type_details']),
        'expectedResult': SolanaMessageResultFromJSON(json['expected_result']),
        'messageToDisplay': json['message_to_display'],
    };
}
