/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateStarknetTransactionRequestDetails } from './CreateStarknetTransactionRequestDetails';
import {
    CreateStarknetTransactionRequestDetailsFromJSON,
    CreateStarknetTransactionRequestDetailsFromJSONTyped,
    CreateStarknetTransactionRequestDetailsToJSON,
    CreateStarknetTransactionRequestDetailsToJSONTyped,
} from './CreateStarknetTransactionRequestDetails';

/**
 * 
 * @export
 * @interface PredictStarknetTransactionRequest
 */
export interface PredictStarknetTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof PredictStarknetTransactionRequest
     */
    vaultId: string;
    /**
     * 
     * @type {string}
     * @memberof PredictStarknetTransactionRequest
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof PredictStarknetTransactionRequest
     */
    type: PredictStarknetTransactionRequestTypeEnum;
    /**
     * 
     * @type {CreateStarknetTransactionRequestDetails}
     * @memberof PredictStarknetTransactionRequest
     */
    details: CreateStarknetTransactionRequestDetails;
}


/**
 * @export
 */
export const PredictStarknetTransactionRequestTypeEnum = {
    starknetTransaction: 'starknet_transaction'
} as const;
export type PredictStarknetTransactionRequestTypeEnum = typeof PredictStarknetTransactionRequestTypeEnum[keyof typeof PredictStarknetTransactionRequestTypeEnum];


/**
 * Check if a given object implements the PredictStarknetTransactionRequest interface.
 */
export function instanceOfPredictStarknetTransactionRequest(value: object): value is PredictStarknetTransactionRequest {
    if (!('vaultId' in value) || value['vaultId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function PredictStarknetTransactionRequestFromJSON(json: any): PredictStarknetTransactionRequest {
    return PredictStarknetTransactionRequestFromJSONTyped(json, false);
}

export function PredictStarknetTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictStarknetTransactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'vaultId': json['vault_id'],
        'note': json['note'] == null ? undefined : json['note'],
        'type': json['type'],
        'details': CreateStarknetTransactionRequestDetailsFromJSON(json['details']),
    };
}

export function PredictStarknetTransactionRequestToJSON(json: any): PredictStarknetTransactionRequest {
    return PredictStarknetTransactionRequestToJSONTyped(json, false);
}

export function PredictStarknetTransactionRequestToJSONTyped(value?: PredictStarknetTransactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vault_id': value['vaultId'],
        'note': value['note'],
        'type': value['type'],
        'details': CreateStarknetTransactionRequestDetailsToJSON(value['details']),
    };
}

