/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AptosGasConfigRequest } from './AptosGasConfigRequest';
import {
    AptosGasConfigRequestFromJSON,
    AptosGasConfigRequestFromJSONTyped,
    AptosGasConfigRequestToJSON,
    AptosGasConfigRequestToJSONTyped,
} from './AptosGasConfigRequest';
import type { AptosChainUniqueId } from './AptosChainUniqueId';
import {
    AptosChainUniqueIdFromJSON,
    AptosChainUniqueIdFromJSONTyped,
    AptosChainUniqueIdToJSON,
    AptosChainUniqueIdToJSONTyped,
} from './AptosChainUniqueId';

/**
 * 
 * @export
 * @interface PredictAptosSerializedRawTransactionRequest
 */
export interface PredictAptosSerializedRawTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof PredictAptosSerializedRawTransactionRequest
     */
    type: PredictAptosSerializedRawTransactionRequestTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof PredictAptosSerializedRawTransactionRequest
     */
    failOnPredictionFailure?: boolean;
    /**
     * 
     * @type {AptosGasConfigRequest}
     * @memberof PredictAptosSerializedRawTransactionRequest
     */
    gasConfig?: AptosGasConfigRequest;
    /**
     * 
     * @type {AptosChainUniqueId}
     * @memberof PredictAptosSerializedRawTransactionRequest
     */
    chain: AptosChainUniqueId;
    /**
     * 
     * @type {string}
     * @memberof PredictAptosSerializedRawTransactionRequest
     */
    serializedTransactionPayload: string;
    /**
     * 
     * @type {boolean}
     * @memberof PredictAptosSerializedRawTransactionRequest
     */
    skipSimulation?: boolean;
}


/**
 * @export
 */
export const PredictAptosSerializedRawTransactionRequestTypeEnum = {
    aptosSerializedEntryPointPayload: 'aptos_serialized_entry_point_payload'
} as const;
export type PredictAptosSerializedRawTransactionRequestTypeEnum = typeof PredictAptosSerializedRawTransactionRequestTypeEnum[keyof typeof PredictAptosSerializedRawTransactionRequestTypeEnum];


/**
 * Check if a given object implements the PredictAptosSerializedRawTransactionRequest interface.
 */
export function instanceOfPredictAptosSerializedRawTransactionRequest(value: object): value is PredictAptosSerializedRawTransactionRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('serializedTransactionPayload' in value) || value['serializedTransactionPayload'] === undefined) return false;
    return true;
}

export function PredictAptosSerializedRawTransactionRequestFromJSON(json: any): PredictAptosSerializedRawTransactionRequest {
    return PredictAptosSerializedRawTransactionRequestFromJSONTyped(json, false);
}

export function PredictAptosSerializedRawTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictAptosSerializedRawTransactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'failOnPredictionFailure': json['fail_on_prediction_failure'] == null ? undefined : json['fail_on_prediction_failure'],
        'gasConfig': json['gas_config'] == null ? undefined : AptosGasConfigRequestFromJSON(json['gas_config']),
        'chain': AptosChainUniqueIdFromJSON(json['chain']),
        'serializedTransactionPayload': json['serialized_transaction_payload'],
        'skipSimulation': json['skip_simulation'] == null ? undefined : json['skip_simulation'],
    };
}

export function PredictAptosSerializedRawTransactionRequestToJSON(json: any): PredictAptosSerializedRawTransactionRequest {
    return PredictAptosSerializedRawTransactionRequestToJSONTyped(json, false);
}

export function PredictAptosSerializedRawTransactionRequestToJSONTyped(value?: PredictAptosSerializedRawTransactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'fail_on_prediction_failure': value['failOnPredictionFailure'],
        'gas_config': AptosGasConfigRequestToJSON(value['gasConfig']),
        'chain': AptosChainUniqueIdToJSON(value['chain']),
        'serialized_transaction_payload': value['serializedTransactionPayload'],
        'skip_simulation': value['skipSimulation'],
    };
}

