/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Price } from './Price';
import {
    PriceFromJSON,
    PriceFromJSONTyped,
    PriceToJSON,
    PriceToJSONTyped,
} from './Price';
import type { EnrichedAssetIdentifier } from './EnrichedAssetIdentifier';
import {
    EnrichedAssetIdentifierFromJSON,
    EnrichedAssetIdentifierFromJSONTyped,
    EnrichedAssetIdentifierToJSON,
    EnrichedAssetIdentifierToJSONTyped,
} from './EnrichedAssetIdentifier';
import type { AssetInfo } from './AssetInfo';
import {
    AssetInfoFromJSON,
    AssetInfoFromJSONTyped,
    AssetInfoToJSON,
    AssetInfoToJSONTyped,
} from './AssetInfo';

/**
 * 
 * @export
 * @interface PricedAsset
 */
export interface PricedAsset {
    /**
     * 
     * @type {string}
     * @memberof PricedAsset
     */
    type: PricedAssetTypeEnum;
    /**
     * 
     * @type {EnrichedAssetIdentifier}
     * @memberof PricedAsset
     */
    assetIdentifier?: EnrichedAssetIdentifier;
    /**
     * 
     * @type {AssetInfo}
     * @memberof PricedAsset
     */
    assetInfo: AssetInfo;
    /**
     * 
     * @type {Price}
     * @memberof PricedAsset
     */
    price?: Price;
}


/**
 * @export
 */
export const PricedAssetTypeEnum = {
    assetPrice: 'asset_price'
} as const;
export type PricedAssetTypeEnum = typeof PricedAssetTypeEnum[keyof typeof PricedAssetTypeEnum];


/**
 * Check if a given object implements the PricedAsset interface.
 */
export function instanceOfPricedAsset(value: object): value is PricedAsset {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('assetInfo' in value) || value['assetInfo'] === undefined) return false;
    return true;
}

export function PricedAssetFromJSON(json: any): PricedAsset {
    return PricedAssetFromJSONTyped(json, false);
}

export function PricedAssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricedAsset {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'assetIdentifier': json['asset_identifier'] == null ? undefined : EnrichedAssetIdentifierFromJSON(json['asset_identifier']),
        'assetInfo': AssetInfoFromJSON(json['asset_info']),
        'price': json['price'] == null ? undefined : PriceFromJSON(json['price']),
    };
}

export function PricedAssetToJSON(json: any): PricedAsset {
    return PricedAssetToJSONTyped(json, false);
}

export function PricedAssetToJSONTyped(value?: PricedAsset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'asset_identifier': EnrichedAssetIdentifierToJSON(value['assetIdentifier']),
        'asset_info': AssetInfoToJSON(value['assetInfo']),
        'price': PriceToJSON(value['price']),
    };
}

