/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicRpcEndpoint
 */
export interface PublicRpcEndpoint {
    /**
     * 
     * @type {string}
     * @memberof PublicRpcEndpoint
     */
    type: PublicRpcEndpointTypeEnum;
}


/**
 * @export
 */
export const PublicRpcEndpointTypeEnum = {
    public: 'public'
} as const;
export type PublicRpcEndpointTypeEnum = typeof PublicRpcEndpointTypeEnum[keyof typeof PublicRpcEndpointTypeEnum];


/**
 * Check if a given object implements the PublicRpcEndpoint interface.
 */
export function instanceOfPublicRpcEndpoint(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function PublicRpcEndpointFromJSON(json: any): PublicRpcEndpoint {
    return PublicRpcEndpointFromJSONTyped(json, false);
}

export function PublicRpcEndpointFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicRpcEndpoint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function PublicRpcEndpointToJSON(value?: PublicRpcEndpoint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
    };
}

