/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VaultsConditionRequest } from './VaultsConditionRequest';
import {
    VaultsConditionRequestFromJSON,
    VaultsConditionRequestFromJSONTyped,
    VaultsConditionRequestToJSON,
    VaultsConditionRequestToJSONTyped,
} from './VaultsConditionRequest';
import type { AddressBookConditionRequest } from './AddressBookConditionRequest';
import {
    AddressBookConditionRequestFromJSON,
    AddressBookConditionRequestFromJSONTyped,
    AddressBookConditionRequestToJSON,
    AddressBookConditionRequestToJSONTyped,
} from './AddressBookConditionRequest';
import type { MultiChainAccount } from './MultiChainAccount';
import {
    MultiChainAccountFromJSON,
    MultiChainAccountFromJSONTyped,
    MultiChainAccountToJSON,
    MultiChainAccountToJSONTyped,
} from './MultiChainAccount';

/**
 * 
 * @export
 * @interface RecipientsConditionRequest
 */
export interface RecipientsConditionRequest {
    /**
     * 
     * @type {Array<MultiChainAccount>}
     * @memberof RecipientsConditionRequest
     */
    addresses?: Array<MultiChainAccount>;
    /**
     * 
     * @type {VaultsConditionRequest}
     * @memberof RecipientsConditionRequest
     */
    vaults?: VaultsConditionRequest;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipientsConditionRequest
     */
    dappIds?: Array<string>;
    /**
     * 
     * @type {AddressBookConditionRequest}
     * @memberof RecipientsConditionRequest
     */
    addressbookContacts?: AddressBookConditionRequest;
}

/**
 * Check if a given object implements the RecipientsConditionRequest interface.
 */
export function instanceOfRecipientsConditionRequest(value: object): value is RecipientsConditionRequest {
    return true;
}

export function RecipientsConditionRequestFromJSON(json: any): RecipientsConditionRequest {
    return RecipientsConditionRequestFromJSONTyped(json, false);
}

export function RecipientsConditionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipientsConditionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'addresses': json['addresses'] == null ? undefined : ((json['addresses'] as Array<any>).map(MultiChainAccountFromJSON)),
        'vaults': json['vaults'] == null ? undefined : VaultsConditionRequestFromJSON(json['vaults']),
        'dappIds': json['dapp_ids'] == null ? undefined : json['dapp_ids'],
        'addressbookContacts': json['addressbook_contacts'] == null ? undefined : AddressBookConditionRequestFromJSON(json['addressbook_contacts']),
    };
}

export function RecipientsConditionRequestToJSON(json: any): RecipientsConditionRequest {
    return RecipientsConditionRequestToJSONTyped(json, false);
}

export function RecipientsConditionRequestToJSONTyped(value?: RecipientsConditionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addresses': value['addresses'] == null ? undefined : ((value['addresses'] as Array<any>).map(MultiChainAccountToJSON)),
        'vaults': VaultsConditionRequestToJSON(value['vaults']),
        'dapp_ids': value['dappIds'],
        'addressbook_contacts': AddressBookConditionRequestToJSON(value['addressbookContacts']),
    };
}

