/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EnrichedSolanaChain } from './EnrichedSolanaChain';
import {
    EnrichedSolanaChainFromJSON,
    EnrichedSolanaChainFromJSONTyped,
    EnrichedSolanaChainToJSON,
} from './EnrichedSolanaChain';

/**
 * 
 * @export
 * @interface SolanaSplTokenAsset
 */
export interface SolanaSplTokenAsset {
    /**
     * 
     * @type {EnrichedSolanaChain}
     * @memberof SolanaSplTokenAsset
     */
    chain: EnrichedSolanaChain;
    /**
     * 
     * @type {string}
     * @memberof SolanaSplTokenAsset
     */
    type: SolanaSplTokenAssetTypeEnum;
}


/**
 * @export
 */
export const SolanaSplTokenAssetTypeEnum = {
    solanaSplTokenAsset: 'solana_spl_token_asset'
} as const;
export type SolanaSplTokenAssetTypeEnum = typeof SolanaSplTokenAssetTypeEnum[keyof typeof SolanaSplTokenAssetTypeEnum];


/**
 * Check if a given object implements the SolanaSplTokenAsset interface.
 */
export function instanceOfSolanaSplTokenAsset(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chain" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function SolanaSplTokenAssetFromJSON(json: any): SolanaSplTokenAsset {
    return SolanaSplTokenAssetFromJSONTyped(json, false);
}

export function SolanaSplTokenAssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolanaSplTokenAsset {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chain': EnrichedSolanaChainFromJSON(json['chain']),
        'type': json['type'],
    };
}

export function SolanaSplTokenAssetToJSON(value?: SolanaSplTokenAsset | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chain': EnrichedSolanaChainToJSON(value.chain),
        'type': value.type,
    };
}

