/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnrichedSolanaChain } from './EnrichedSolanaChain';
import {
    EnrichedSolanaChainFromJSON,
    EnrichedSolanaChainFromJSONTyped,
    EnrichedSolanaChainToJSON,
    EnrichedSolanaChainToJSONTyped,
} from './EnrichedSolanaChain';

/**
 * 
 * @export
 * @interface SolanaNativeAsset
 */
export interface SolanaNativeAsset {
    /**
     * 
     * @type {EnrichedSolanaChain}
     * @memberof SolanaNativeAsset
     */
    chain: EnrichedSolanaChain;
    /**
     * 
     * @type {string}
     * @memberof SolanaNativeAsset
     */
    type: SolanaNativeAssetTypeEnum;
}


/**
 * @export
 */
export const SolanaNativeAssetTypeEnum = {
    solanaNativeAsset: 'solana_native_asset'
} as const;
export type SolanaNativeAssetTypeEnum = typeof SolanaNativeAssetTypeEnum[keyof typeof SolanaNativeAssetTypeEnum];


/**
 * Check if a given object implements the SolanaNativeAsset interface.
 */
export function instanceOfSolanaNativeAsset(value: object): value is SolanaNativeAsset {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function SolanaNativeAssetFromJSON(json: any): SolanaNativeAsset {
    return SolanaNativeAssetFromJSONTyped(json, false);
}

export function SolanaNativeAssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolanaNativeAsset {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': EnrichedSolanaChainFromJSON(json['chain']),
        'type': json['type'],
    };
}

export function SolanaNativeAssetToJSON(json: any): SolanaNativeAsset {
    return SolanaNativeAssetToJSONTyped(json, false);
}

export function SolanaNativeAssetToJSONTyped(value?: SolanaNativeAsset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': EnrichedSolanaChainToJSON(value['chain']),
        'type': value['type'],
    };
}

