/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SolanaMessageAddressTableLookupRequest
 */
export interface SolanaMessageAddressTableLookupRequest {
    /**
     * 
     * @type {string}
     * @memberof SolanaMessageAddressTableLookupRequest
     */
    accountKey: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof SolanaMessageAddressTableLookupRequest
     */
    writableIndexes: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof SolanaMessageAddressTableLookupRequest
     */
    readonlyIndexes: Array<number>;
}

/**
 * Check if a given object implements the SolanaMessageAddressTableLookupRequest interface.
 */
export function instanceOfSolanaMessageAddressTableLookupRequest(value: object): value is SolanaMessageAddressTableLookupRequest {
    if (!('accountKey' in value) || value['accountKey'] === undefined) return false;
    if (!('writableIndexes' in value) || value['writableIndexes'] === undefined) return false;
    if (!('readonlyIndexes' in value) || value['readonlyIndexes'] === undefined) return false;
    return true;
}

export function SolanaMessageAddressTableLookupRequestFromJSON(json: any): SolanaMessageAddressTableLookupRequest {
    return SolanaMessageAddressTableLookupRequestFromJSONTyped(json, false);
}

export function SolanaMessageAddressTableLookupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolanaMessageAddressTableLookupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountKey': json['account_key'],
        'writableIndexes': json['writable_indexes'],
        'readonlyIndexes': json['readonly_indexes'],
    };
}

export function SolanaMessageAddressTableLookupRequestToJSON(json: any): SolanaMessageAddressTableLookupRequest {
    return SolanaMessageAddressTableLookupRequestToJSONTyped(json, false);
}

export function SolanaMessageAddressTableLookupRequestToJSONTyped(value?: SolanaMessageAddressTableLookupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_key': value['accountKey'],
        'writable_indexes': value['writableIndexes'],
        'readonly_indexes': value['readonlyIndexes'],
    };
}

