/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EnrichedSolanaAddress } from './EnrichedSolanaAddress';
import {
    EnrichedSolanaAddressFromJSON,
    EnrichedSolanaAddressFromJSONTyped,
    EnrichedSolanaAddressToJSON,
} from './EnrichedSolanaAddress';
import type { TransferDirection } from './TransferDirection';
import {
    TransferDirectionFromJSON,
    TransferDirectionFromJSONTyped,
    TransferDirectionToJSON,
} from './TransferDirection';

/**
 * 
 * @export
 * @interface SolanaNativeTransferDetails
 */
export interface SolanaNativeTransferDetails {
    /**
     * 
     * @type {string}
     * @memberof SolanaNativeTransferDetails
     */
    type: SolanaNativeTransferDetailsTypeEnum;
    /**
     * 
     * @type {TransferDirection}
     * @memberof SolanaNativeTransferDetails
     */
    direction: TransferDirection;
    /**
     * 
     * @type {EnrichedSolanaAddress}
     * @memberof SolanaNativeTransferDetails
     */
    sender: EnrichedSolanaAddress;
    /**
     * 
     * @type {EnrichedSolanaAddress}
     * @memberof SolanaNativeTransferDetails
     */
    recipient: EnrichedSolanaAddress;
    /**
     * 
     * @type {boolean}
     * @memberof SolanaNativeTransferDetails
     */
    isInternal?: boolean;
}


/**
 * @export
 */
export const SolanaNativeTransferDetailsTypeEnum = {
    nativeTransfer: 'native_transfer'
} as const;
export type SolanaNativeTransferDetailsTypeEnum = typeof SolanaNativeTransferDetailsTypeEnum[keyof typeof SolanaNativeTransferDetailsTypeEnum];


/**
 * Check if a given object implements the SolanaNativeTransferDetails interface.
 */
export function instanceOfSolanaNativeTransferDetails(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "direction" in value;
    isInstance = isInstance && "sender" in value;
    isInstance = isInstance && "recipient" in value;

    return isInstance;
}

export function SolanaNativeTransferDetailsFromJSON(json: any): SolanaNativeTransferDetails {
    return SolanaNativeTransferDetailsFromJSONTyped(json, false);
}

export function SolanaNativeTransferDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolanaNativeTransferDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'direction': TransferDirectionFromJSON(json['direction']),
        'sender': EnrichedSolanaAddressFromJSON(json['sender']),
        'recipient': EnrichedSolanaAddressFromJSON(json['recipient']),
        'isInternal': !exists(json, 'is_internal') ? undefined : json['is_internal'],
    };
}

export function SolanaNativeTransferDetailsToJSON(value?: SolanaNativeTransferDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'direction': TransferDirectionToJSON(value.direction),
        'sender': EnrichedSolanaAddressToJSON(value.sender),
        'recipient': EnrichedSolanaAddressToJSON(value.recipient),
        'is_internal': value.isInternal,
    };
}

