/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StacksReversionState } from './StacksReversionState';
import {
    StacksReversionStateFromJSON,
    StacksReversionStateFromJSONTyped,
    StacksReversionStateToJSON,
    StacksReversionStateToJSONTyped,
} from './StacksReversionState';

/**
 * 
 * @export
 * @interface StacksReversion
 */
export interface StacksReversion {
    /**
     * 
     * @type {StacksReversionState}
     * @memberof StacksReversion
     */
    state: StacksReversionState;
    /**
     * 
     * @type {string}
     * @memberof StacksReversion
     */
    reason?: string;
}



/**
 * Check if a given object implements the StacksReversion interface.
 */
export function instanceOfStacksReversion(value: object): value is StacksReversion {
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function StacksReversionFromJSON(json: any): StacksReversion {
    return StacksReversionFromJSONTyped(json, false);
}

export function StacksReversionFromJSONTyped(json: any, ignoreDiscriminator: boolean): StacksReversion {
    if (json == null) {
        return json;
    }
    return {
        
        'state': StacksReversionStateFromJSON(json['state']),
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function StacksReversionToJSON(json: any): StacksReversion {
    return StacksReversionToJSONTyped(json, false);
}

export function StacksReversionToJSONTyped(value?: StacksReversion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': StacksReversionStateToJSON(value['state']),
        'reason': value['reason'],
    };
}

