/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StacksPostConditionComparator = {
    eq: 'eq',
    gt: 'gt',
    ge: 'ge',
    lt: 'lt',
    le: 'le'
} as const;
export type StacksPostConditionComparator = typeof StacksPostConditionComparator[keyof typeof StacksPostConditionComparator];


export function instanceOfStacksPostConditionComparator(value: any): boolean {
    for (const key in StacksPostConditionComparator) {
        if (Object.prototype.hasOwnProperty.call(StacksPostConditionComparator, key)) {
            if (StacksPostConditionComparator[key as keyof typeof StacksPostConditionComparator] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StacksPostConditionComparatorFromJSON(json: any): StacksPostConditionComparator {
    return StacksPostConditionComparatorFromJSONTyped(json, false);
}

export function StacksPostConditionComparatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): StacksPostConditionComparator {
    return json as StacksPostConditionComparator;
}

export function StacksPostConditionComparatorToJSON(value?: StacksPostConditionComparator | null): any {
    return value as any;
}

export function StacksPostConditionComparatorToJSONTyped(value: any, ignoreDiscriminator: boolean): StacksPostConditionComparator {
    return value as StacksPostConditionComparator;
}

