/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FeePriorityLevelRequest } from './FeePriorityLevelRequest';
import {
    FeePriorityLevelRequestToJSON,
} from './FeePriorityLevelRequest';

/**
 * 
 * @export
 * @interface StacksPriorityFeeRequest
 */
export interface StacksPriorityFeeRequest {
    /**
     * 
     * @type {StacksPriorityFeeRequestTypeEnum}
     * @memberof StacksPriorityFeeRequest
     */
    type: StacksPriorityFeeRequestTypeEnum;
    /**
     * Using the Fee Priority option, you allocate the range of fee you are willing to add: low, medium, or high. Fordefi then does its best to achieve success, based on these parameters.
     * @type {FeePriorityLevelRequest}
     * @memberof StacksPriorityFeeRequest
     */
    priorityLevel: FeePriorityLevelRequest;
}


/**
 * @export
 */
const StacksPriorityFeeRequestTypeEnum = {
    priority: 'priority'
} as const;
type StacksPriorityFeeRequestTypeEnum = typeof StacksPriorityFeeRequestTypeEnum[keyof typeof StacksPriorityFeeRequestTypeEnum];

export function StacksPriorityFeeRequestToJSON(json: any): StacksPriorityFeeRequest {
    return StacksPriorityFeeRequestToJSONTyped(json, false);
}

function StacksPriorityFeeRequestToJSONTyped(value?: StacksPriorityFeeRequest | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'priority_level': FeePriorityLevelRequestToJSON(value['priorityLevel']),
    };
}
