/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KnownAssetStacksPostCondition } from './KnownAssetStacksPostCondition';
import {
    KnownAssetStacksPostConditionFromJSONTyped,
} from './KnownAssetStacksPostCondition';
import type { UnknownAssetStacksPostCondition } from './UnknownAssetStacksPostCondition';
import {
    UnknownAssetStacksPostConditionFromJSONTyped,
} from './UnknownAssetStacksPostCondition';

/**
 * 
 * @export
 * @type StacksPostCondition
 */
export type StacksPostCondition = { type: 'known_asset' } & KnownAssetStacksPostCondition | { type: 'unknown_asset' } & UnknownAssetStacksPostCondition;

export function StacksPostConditionFromJSON(json: any): StacksPostCondition {
    return StacksPostConditionFromJSONTyped(json, false);
}

function StacksPostConditionFromJSONTyped(json: any, _ignoreDiscriminator: boolean): StacksPostCondition {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'known_asset':
            return Object.assign({}, KnownAssetStacksPostConditionFromJSONTyped(json, true), { type: 'known_asset' } as const);
        case 'unknown_asset':
            return Object.assign({}, UnknownAssetStacksPostConditionFromJSONTyped(json, true), { type: 'unknown_asset' } as const);
        default:
            throw new Error(`No variant of StacksPostCondition exists with 'type=${json['type']}'`);
    }
}

