/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { StacksChainUniqueId } from './StacksChainUniqueId';
import {
    StacksChainUniqueIdFromJSON,
    StacksChainUniqueIdToJSON,
} from './StacksChainUniqueId';

/**
 * 
 * @export
 * @interface StacksNativeAssetIdentifierRequest
 */
export interface StacksNativeAssetIdentifierRequest {
    /**
     * 
     * @type {string}
     * @memberof StacksNativeAssetIdentifierRequest
     */
    type: StacksNativeAssetIdentifierRequestTypeEnum;
    /**
     * 
     * @type {StacksChainUniqueId}
     * @memberof StacksNativeAssetIdentifierRequest
     */
    chain: StacksChainUniqueId;
}


/**
 * 
 */
const StacksNativeAssetIdentifierRequestTypeEnum = {
    native: 'native'
} as const;
type StacksNativeAssetIdentifierRequestTypeEnum = typeof StacksNativeAssetIdentifierRequestTypeEnum[keyof typeof StacksNativeAssetIdentifierRequestTypeEnum];

export function StacksNativeAssetIdentifierRequestFromJSONTyped(json: any, _ignoreDiscriminator: boolean): StacksNativeAssetIdentifierRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'chain': StacksChainUniqueIdFromJSON(json['chain']),
    };
}

export function StacksNativeAssetIdentifierRequestToJSON(json: any): StacksNativeAssetIdentifierRequest {
    return StacksNativeAssetIdentifierRequestToJSONTyped(json, false);
}

function StacksNativeAssetIdentifierRequestToJSONTyped(value?: StacksNativeAssetIdentifierRequest | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'chain': StacksChainUniqueIdToJSON(value['chain']),
    };
}
