/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PricedAsset } from './PricedAsset';
import {
    PricedAssetFromJSON,
    PricedAssetFromJSONTyped,
    PricedAssetToJSON,
    PricedAssetToJSONTyped,
} from './PricedAsset';
import type { EnrichedStarknetAddress } from './EnrichedStarknetAddress';
import {
    EnrichedStarknetAddressFromJSON,
    EnrichedStarknetAddressFromJSONTyped,
    EnrichedStarknetAddressToJSON,
    EnrichedStarknetAddressToJSONTyped,
} from './EnrichedStarknetAddress';

/**
 * 
 * @export
 * @interface StarknetTransferEffect
 */
export interface StarknetTransferEffect {
    /**
     * 
     * @type {PricedAsset}
     * @memberof StarknetTransferEffect
     */
    pricedAsset: PricedAsset;
    /**
     * 
     * @type {string}
     * @memberof StarknetTransferEffect
     */
    amount: string;
    /**
     * 
     * @type {EnrichedStarknetAddress}
     * @memberof StarknetTransferEffect
     */
    from: EnrichedStarknetAddress;
    /**
     * 
     * @type {EnrichedStarknetAddress}
     * @memberof StarknetTransferEffect
     */
    to: EnrichedStarknetAddress;
}

/**
 * Check if a given object implements the StarknetTransferEffect interface.
 */
export function instanceOfStarknetTransferEffect(value: object): value is StarknetTransferEffect {
    if (!('pricedAsset' in value) || value['pricedAsset'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function StarknetTransferEffectFromJSON(json: any): StarknetTransferEffect {
    return StarknetTransferEffectFromJSONTyped(json, false);
}

export function StarknetTransferEffectFromJSONTyped(json: any, ignoreDiscriminator: boolean): StarknetTransferEffect {
    if (json == null) {
        return json;
    }
    return {
        
        'pricedAsset': PricedAssetFromJSON(json['priced_asset']),
        'amount': json['amount'],
        'from': EnrichedStarknetAddressFromJSON(json['from']),
        'to': EnrichedStarknetAddressFromJSON(json['to']),
    };
}

export function StarknetTransferEffectToJSON(json: any): StarknetTransferEffect {
    return StarknetTransferEffectToJSONTyped(json, false);
}

export function StarknetTransferEffectToJSONTyped(value?: StarknetTransferEffect | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'priced_asset': PricedAssetToJSON(value['pricedAsset']),
        'amount': value['amount'],
        'from': EnrichedStarknetAddressToJSON(value['from']),
        'to': EnrichedStarknetAddressToJSON(value['to']),
    };
}

