/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StarknetReversionState = {
    notReverted: 'not_reverted',
    unknownRevert: 'unknown_revert',
    contractAsserted: 'contract_asserted',
    insufficientFundsGasAndValue: 'insufficient_funds_gas_and_value'
} as const;
export type StarknetReversionState = typeof StarknetReversionState[keyof typeof StarknetReversionState];


export function instanceOfStarknetReversionState(value: any): boolean {
    for (const key in StarknetReversionState) {
        if (Object.prototype.hasOwnProperty.call(StarknetReversionState, key)) {
            if (StarknetReversionState[key as keyof typeof StarknetReversionState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StarknetReversionStateFromJSON(json: any): StarknetReversionState {
    return StarknetReversionStateFromJSONTyped(json, false);
}

export function StarknetReversionStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StarknetReversionState {
    return json as StarknetReversionState;
}

export function StarknetReversionStateToJSON(value?: StarknetReversionState | null): any {
    return value as any;
}

export function StarknetReversionStateToJSONTyped(value: any, ignoreDiscriminator: boolean): StarknetReversionState {
    return value as StarknetReversionState;
}

