/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { StarknetEffects } from './StarknetEffects';
import {
    StarknetEffectsFromJSON,
} from './StarknetEffects';
import type { StarknetReversion } from './StarknetReversion';
import {
    StarknetReversionFromJSON,
} from './StarknetReversion';
import type { StarknetFees } from './StarknetFees';
import {
    StarknetFeesFromJSON,
} from './StarknetFees';

/**
 * 
 * @export
 * @interface StarknetTransactionResult
 */
export interface StarknetTransactionResult {
    /**
     * Details whether the transaction was reverted or not.
     * @type {StarknetReversion}
     * @memberof StarknetTransactionResult
     */
    reversion: StarknetReversion;
    /**
     * The total fee of the first transaction on the trace.
     * @type {StarknetFees}
     * @memberof StarknetTransactionResult
     */
    fees: StarknetFees;
    /**
     * The effects of the transaction.
     * @type {StarknetEffects}
     * @memberof StarknetTransactionResult
     */
    effects: StarknetEffects;
}

export function StarknetTransactionResultFromJSON(json: any): StarknetTransactionResult {
    return StarknetTransactionResultFromJSONTyped(json, false);
}

function StarknetTransactionResultFromJSONTyped(json: any, _ignoreDiscriminator: boolean): StarknetTransactionResult {
    if (json == null) {
        return json;
    }
    return {
        
        'reversion': StarknetReversionFromJSON(json['reversion']),
        'fees': StarknetFeesFromJSON(json['fees']),
        'effects': StarknetEffectsFromJSON(json['effects']),
    };
}
