/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { StarknetAddressRequest } from './StarknetAddressRequest';
import {
    StarknetAddressRequestFromJSON,
    StarknetAddressRequestToJSON,
} from './StarknetAddressRequest';

/**
 * 
 * @export
 * @interface StarknetErc20AssetIdentifierRequest
 */
export interface StarknetErc20AssetIdentifierRequest {
    /**
     * 
     * @type {string}
     * @memberof StarknetErc20AssetIdentifierRequest
     */
    type: StarknetErc20AssetIdentifierRequestTypeEnum;
    /**
     * 
     * @type {StarknetAddressRequest}
     * @memberof StarknetErc20AssetIdentifierRequest
     */
    erc20: StarknetAddressRequest;
}


/**
 * 
 */
const StarknetErc20AssetIdentifierRequestTypeEnum = {
    erc20: 'erc20'
} as const;
type StarknetErc20AssetIdentifierRequestTypeEnum = typeof StarknetErc20AssetIdentifierRequestTypeEnum[keyof typeof StarknetErc20AssetIdentifierRequestTypeEnum];

export function StarknetErc20AssetIdentifierRequestFromJSONTyped(json: any, _ignoreDiscriminator: boolean): StarknetErc20AssetIdentifierRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'erc20': StarknetAddressRequestFromJSON(json['erc20']),
    };
}

export function StarknetErc20AssetIdentifierRequestToJSON(json: any): StarknetErc20AssetIdentifierRequest {
    return StarknetErc20AssetIdentifierRequestToJSONTyped(json, false);
}

function StarknetErc20AssetIdentifierRequestToJSONTyped(value?: StarknetErc20AssetIdentifierRequest | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'erc20': StarknetAddressRequestToJSON(value['erc20']),
    };
}
