/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StarknetTransactionState = {
    waitingForApproval: 'waiting_for_approval',
    waitingForSigningTrigger: 'waiting_for_signing_trigger',
    approved: 'approved',
    signed: 'signed',
    pushedToBlockchain: 'pushed_to_blockchain',
    mined: 'mined',
    completed: 'completed',
    aborted: 'aborted',
    errorPushingToBlockchain: 'error_pushing_to_blockchain',
    minedReverted: 'mined_reverted',
    completedReverted: 'completed_reverted',
    errorSigning: 'error_signing'
} as const;
export type StarknetTransactionState = typeof StarknetTransactionState[keyof typeof StarknetTransactionState];


export function StarknetTransactionStateFromJSON(json: any): StarknetTransactionState {
    return StarknetTransactionStateFromJSONTyped(json, false);
}

export function StarknetTransactionStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StarknetTransactionState {
    return json as StarknetTransactionState;
}

export function StarknetTransactionStateToJSON(value?: StarknetTransactionState | null): any {
    return value as any;
}

