/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SuiObjectRef } from './SuiObjectRef';
import {
    SuiObjectRefFromJSON,
    SuiObjectRefToJSON,
} from './SuiObjectRef';

/**
 * 
 * @export
 * @interface SuiGasConfig
 */
export interface SuiGasConfig {
    /**
     * The owner of the gas config. Used for sponsored transactions.
     * @type {string}
     * @memberof SuiGasConfig
     */
    owner?: string;
    /**
     * The budget of the gas in the transaction (in MIST).
     * @type {string}
     * @memberof SuiGasConfig
     */
    budget?: string;
    /**
     * The price per gas unit (in MIST).
     * @type {string}
     * @memberof SuiGasConfig
     */
    price?: string;
    /**
     * The list of SUI coins used to pay for the gas.
     * @type {Array<SuiObjectRef>}
     * @memberof SuiGasConfig
     */
    payment: Array<SuiObjectRef>;
}

export function SuiGasConfigFromJSON(json: any): SuiGasConfig {
    return SuiGasConfigFromJSONTyped(json, false);
}

function SuiGasConfigFromJSONTyped(json: any, _ignoreDiscriminator: boolean): SuiGasConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'owner': json['owner'] == null ? undefined : json['owner'],
        'budget': json['budget'] == null ? undefined : json['budget'],
        'price': json['price'] == null ? undefined : json['price'],
        'payment': ((json['payment'] as Array<any>).map(SuiObjectRefFromJSON)),
    };
}

export function SuiGasConfigToJSON(json: any): SuiGasConfig {
    return SuiGasConfigToJSONTyped(json, false);
}

function SuiGasConfigToJSONTyped(value?: SuiGasConfig | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'owner': value['owner'],
        'budget': value['budget'],
        'price': value['price'],
        'payment': ((value['payment'] as Array<any>).map(SuiObjectRefToJSON)),
    };
}
