/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuiRecipientVaultId
 */
export interface SuiRecipientVaultId {
    /**
     * 
     * @type {string}
     * @memberof SuiRecipientVaultId
     */
    type: SuiRecipientVaultIdTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SuiRecipientVaultId
     */
    vaultId: string;
}


/**
 * @export
 */
export const SuiRecipientVaultIdTypeEnum = {
    vaultId: 'vault_id'
} as const;
export type SuiRecipientVaultIdTypeEnum = typeof SuiRecipientVaultIdTypeEnum[keyof typeof SuiRecipientVaultIdTypeEnum];


/**
 * Check if a given object implements the SuiRecipientVaultId interface.
 */
export function instanceOfSuiRecipientVaultId(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "vaultId" in value;

    return isInstance;
}

export function SuiRecipientVaultIdFromJSON(json: any): SuiRecipientVaultId {
    return SuiRecipientVaultIdFromJSONTyped(json, false);
}

export function SuiRecipientVaultIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuiRecipientVaultId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'vaultId': json['vault_id'],
    };
}

export function SuiRecipientVaultIdToJSON(value?: SuiRecipientVaultId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'vault_id': value.vaultId,
    };
}

