/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SuiTransactionState = {
    waitingForApproval: 'waiting_for_approval',
    waitingForSigningTrigger: 'waiting_for_signing_trigger',
    approved: 'approved',
    signed: 'signed',
    pushedToBlockchain: 'pushed_to_blockchain',
    mined: 'mined',
    completed: 'completed',
    aborted: 'aborted',
    errorPushingToBlockchain: 'error_pushing_to_blockchain',
    minedReverted: 'mined_reverted',
    completedReverted: 'completed_reverted',
    errorSigning: 'error_signing'
} as const;
export type SuiTransactionState = typeof SuiTransactionState[keyof typeof SuiTransactionState];


export function SuiTransactionStateFromJSON(json: any): SuiTransactionState {
    return SuiTransactionStateFromJSONTyped(json, false);
}

export function SuiTransactionStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuiTransactionState {
    return json as SuiTransactionState;
}

export function SuiTransactionStateToJSON(value?: SuiTransactionState | null): any {
    return value as any;
}

