/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SuiCommandArgument } from './SuiCommandArgument';
import {
    SuiCommandArgumentFromJSON,
    SuiCommandArgumentToJSON,
} from './SuiCommandArgument';

/**
 * 
 * @export
 * @interface SuiUpgradeCommand
 */
export interface SuiUpgradeCommand {
    /**
     * 
     * @type {string}
     * @memberof SuiUpgradeCommand
     */
    type: SuiUpgradeCommandTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof SuiUpgradeCommand
     */
    modules: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SuiUpgradeCommand
     */
    dependencies: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SuiUpgradeCommand
     */
    packageId: string;
    /**
     * 
     * @type {SuiCommandArgument}
     * @memberof SuiUpgradeCommand
     */
    ticket: SuiCommandArgument;
}


/**
 * 
 */
const SuiUpgradeCommandTypeEnum = {
    upgrade: 'upgrade'
} as const;
type SuiUpgradeCommandTypeEnum = typeof SuiUpgradeCommandTypeEnum[keyof typeof SuiUpgradeCommandTypeEnum];

export function SuiUpgradeCommandFromJSONTyped(json: any, _ignoreDiscriminator: boolean): SuiUpgradeCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'modules': json['modules'],
        'dependencies': json['dependencies'],
        'packageId': json['package_id'],
        'ticket': SuiCommandArgumentFromJSON(json['ticket']),
    };
}

export function SuiUpgradeCommandToJSON(json: any): SuiUpgradeCommand {
    return SuiUpgradeCommandToJSONTyped(json, false);
}

function SuiUpgradeCommandToJSONTyped(value?: SuiUpgradeCommand | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'modules': value['modules'],
        'dependencies': value['dependencies'],
        'package_id': value['packageId'],
        'ticket': SuiCommandArgumentToJSON(value['ticket']),
    };
}
