/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TonBalanceChangeEffect } from './TonBalanceChangeEffect';
import {
    TonBalanceChangeEffectFromJSON,
    TonBalanceChangeEffectFromJSONTyped,
    TonBalanceChangeEffectToJSON,
    TonBalanceChangeEffectToJSONTyped,
} from './TonBalanceChangeEffect';
import type { TonTransferEffect } from './TonTransferEffect';
import {
    TonTransferEffectFromJSON,
    TonTransferEffectFromJSONTyped,
    TonTransferEffectToJSON,
    TonTransferEffectToJSONTyped,
} from './TonTransferEffect';

/**
 * 
 * @export
 * @interface TonEffects
 */
export interface TonEffects {
    /**
     * 
     * @type {Array<TonBalanceChangeEffect>}
     * @memberof TonEffects
     */
    balanceChanges: Array<TonBalanceChangeEffect>;
    /**
     * 
     * @type {Array<TonTransferEffect>}
     * @memberof TonEffects
     */
    transfers: Array<TonTransferEffect>;
}

/**
 * Check if a given object implements the TonEffects interface.
 */
export function instanceOfTonEffects(value: object): value is TonEffects {
    if (!('balanceChanges' in value) || value['balanceChanges'] === undefined) return false;
    if (!('transfers' in value) || value['transfers'] === undefined) return false;
    return true;
}

export function TonEffectsFromJSON(json: any): TonEffects {
    return TonEffectsFromJSONTyped(json, false);
}

export function TonEffectsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TonEffects {
    if (json == null) {
        return json;
    }
    return {
        
        'balanceChanges': ((json['balance_changes'] as Array<any>).map(TonBalanceChangeEffectFromJSON)),
        'transfers': ((json['transfers'] as Array<any>).map(TonTransferEffectFromJSON)),
    };
}

export function TonEffectsToJSON(json: any): TonEffects {
    return TonEffectsToJSONTyped(json, false);
}

export function TonEffectsToJSONTyped(value?: TonEffects | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'balance_changes': ((value['balanceChanges'] as Array<any>).map(TonBalanceChangeEffectToJSON)),
        'transfers': ((value['transfers'] as Array<any>).map(TonTransferEffectToJSON)),
    };
}

