/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { EnrichedTonAddress } from './EnrichedTonAddress';
import {
    EnrichedTonAddressFromJSON,
} from './EnrichedTonAddress';
import type { ManagedTransactionData } from './ManagedTransactionData';
import {
    ManagedTransactionDataFromJSON,
} from './ManagedTransactionData';
import type { EnrichedTonChain } from './EnrichedTonChain';
import {
    EnrichedTonChainFromJSON,
} from './EnrichedTonChain';
import type { PredictedTonTransactionTonTransactionTypeDetails } from './PredictedTonTransactionTonTransactionTypeDetails';
import {
    PredictedTonTransactionTonTransactionTypeDetailsFromJSON,
} from './PredictedTonTransactionTonTransactionTypeDetails';
import type { PushableTransactionStateChange } from './PushableTransactionStateChange';
import {
    PushableTransactionStateChangeFromJSON,
} from './PushableTransactionStateChange';
import type { PushableTransactionState } from './PushableTransactionState';
import {
    PushableTransactionStateFromJSON,
} from './PushableTransactionState';
import type { TonTransactionResult } from './TonTransactionResult';
import {
    TonTransactionResultFromJSON,
} from './TonTransactionResult';
import type { MinedResultStatus } from './MinedResultStatus';
import {
    MinedResultStatusFromJSON,
} from './MinedResultStatus';
import type { VaultRef } from './VaultRef';
import {
    VaultRefFromJSON,
} from './VaultRef';
import type { TransactionSpamState } from './TransactionSpamState';
import {
    TransactionSpamStateFromJSON,
} from './TransactionSpamState';
import type { TransactionDirection } from './TransactionDirection';
import {
    TransactionDirectionFromJSON,
} from './TransactionDirection';
import type { AmlCheck } from './AmlCheck';
import {
    AmlCheckFromJSON,
} from './AmlCheck';
import type { Signature } from './Signature';
import {
    SignatureFromJSON,
} from './Signature';
import type { RelatedTransaction } from './RelatedTransaction';
import {
    RelatedTransactionFromJSON,
} from './RelatedTransaction';
import type { SimulationStatusResult } from './SimulationStatusResult';
import {
    SimulationStatusResultFromJSON,
} from './SimulationStatusResult';
import type { Block } from './Block';
import {
    BlockFromJSON,
} from './Block';
import type { TonTransactionPayload } from './TonTransactionPayload';
import {
    TonTransactionPayloadFromJSON,
} from './TonTransactionPayload';

/**
 * 
 * @export
 * @interface TonTransaction
 */
export interface TonTransaction {
    /**
     * 
     * @type {string}
     * @memberof TonTransaction
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof TonTransaction
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TonTransaction
     */
    modifiedAt: Date;
    /**
     * 
     * @type {ManagedTransactionData}
     * @memberof TonTransaction
     */
    managedTransactionData?: ManagedTransactionData;
    /**
     * 
     * @type {Array<Signature>}
     * @memberof TonTransaction
     */
    signatures: Array<Signature>;
    /**
     * 
     * @type {string}
     * @memberof TonTransaction
     */
    note?: string;
    /**
     * 
     * @type {TransactionSpamState}
     * @memberof TonTransaction
     */
    spamState?: TransactionSpamState;
    /**
     * 
     * @type {TransactionDirection}
     * @memberof TonTransaction
     */
    direction: TransactionDirection;
    /**
     * 
     * @type {boolean}
     * @memberof TonTransaction
     */
    signedExternally?: boolean;
    /**
     * 
     * @type {Array<VaultRef>}
     * @memberof TonTransaction
     */
    interactedVaults: Array<VaultRef>;
    /**
     * 
     * @type {Array<RelatedTransaction>}
     * @memberof TonTransaction
     */
    relatedTransactions?: Array<RelatedTransaction>;
    /**
     * 
     * @type {string}
     * @memberof TonTransaction
     */
    organizationId: string;
    /**
     * 
     * @type {Block}
     * @memberof TonTransaction
     */
    block?: Block;
    /**
     * 
     * @type {PushableTransactionState}
     * @memberof TonTransaction
     */
    state: PushableTransactionState;
    /**
     * 
     * @type {Array<PushableTransactionStateChange>}
     * @memberof TonTransaction
     */
    stateChanges: Array<PushableTransactionStateChange>;
    /**
     * 
     * @type {AmlCheck}
     * @memberof TonTransaction
     */
    amlCheck?: AmlCheck;
    /**
     * 
     * @type {MinedResultStatus}
     * @memberof TonTransaction
     */
    minedResultStatus?: MinedResultStatus;
    /**
     * 
     * @type {SimulationStatusResult}
     * @memberof TonTransaction
     */
    simulationStatusResult?: SimulationStatusResult;
    /**
     * 
     * @type {string}
     * @memberof TonTransaction
     */
    type: TonTransactionTypeEnum;
    /**
     * 
     * @type {PredictedTonTransactionTonTransactionTypeDetails}
     * @memberof TonTransaction
     */
    tonTransactionTypeDetails: PredictedTonTransactionTonTransactionTypeDetails;
    /**
     * 
     * @type {EnrichedTonChain}
     * @memberof TonTransaction
     */
    chain: EnrichedTonChain;
    /**
     * 
     * @type {number}
     * @memberof TonTransaction
     */
    nonce?: number;
    /**
     * 
     * @type {EnrichedTonAddress}
     * @memberof TonTransaction
     */
    sender: EnrichedTonAddress;
    /**
     * 
     * @type {TonTransactionPayload}
     * @memberof TonTransaction
     */
    payload: TonTransactionPayload;
    /**
     * 
     * @type {string}
     * @memberof TonTransaction
     */
    hash?: string;
    /**
     * 
     * @type {string}
     * @memberof TonTransaction
     */
    serializedSignedTransaction?: string;
    /**
     * 
     * @type {TonTransactionResult}
     * @memberof TonTransaction
     */
    expectedResult?: TonTransactionResult;
    /**
     * 
     * @type {TonTransactionResult}
     * @memberof TonTransaction
     */
    minedResult?: TonTransactionResult;
    /**
     * 
     * @type {string}
     * @memberof TonTransaction
     */
    explorerUrl?: string;
}


/**
 * 
 */
const TonTransactionTypeEnum = {
    tonTransaction: 'ton_transaction'
} as const;
type TonTransactionTypeEnum = typeof TonTransactionTypeEnum[keyof typeof TonTransactionTypeEnum];

export function TonTransactionFromJSONTyped(json: any, _ignoreDiscriminator: boolean): TonTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'modifiedAt': (new Date(json['modified_at'])),
        'managedTransactionData': json['managed_transaction_data'] == null ? undefined : ManagedTransactionDataFromJSON(json['managed_transaction_data']),
        'signatures': ((json['signatures'] as Array<any>).map(SignatureFromJSON)),
        'note': json['note'] == null ? undefined : json['note'],
        'spamState': json['spam_state'] == null ? undefined : TransactionSpamStateFromJSON(json['spam_state']),
        'direction': TransactionDirectionFromJSON(json['direction']),
        'signedExternally': json['signed_externally'] == null ? undefined : json['signed_externally'],
        'interactedVaults': ((json['interacted_vaults'] as Array<any>).map(VaultRefFromJSON)),
        'relatedTransactions': json['related_transactions'] == null ? undefined : ((json['related_transactions'] as Array<any>).map(RelatedTransactionFromJSON)),
        'organizationId': json['organization_id'],
        'block': json['block'] == null ? undefined : BlockFromJSON(json['block']),
        'state': PushableTransactionStateFromJSON(json['state']),
        'stateChanges': ((json['state_changes'] as Array<any>).map(PushableTransactionStateChangeFromJSON)),
        'amlCheck': json['aml_check'] == null ? undefined : AmlCheckFromJSON(json['aml_check']),
        'minedResultStatus': json['mined_result_status'] == null ? undefined : MinedResultStatusFromJSON(json['mined_result_status']),
        'simulationStatusResult': json['simulation_status_result'] == null ? undefined : SimulationStatusResultFromJSON(json['simulation_status_result']),
        'type': json['type'],
        'tonTransactionTypeDetails': PredictedTonTransactionTonTransactionTypeDetailsFromJSON(json['ton_transaction_type_details']),
        'chain': EnrichedTonChainFromJSON(json['chain']),
        'nonce': json['nonce'] == null ? undefined : json['nonce'],
        'sender': EnrichedTonAddressFromJSON(json['sender']),
        'payload': TonTransactionPayloadFromJSON(json['payload']),
        'hash': json['hash'] == null ? undefined : json['hash'],
        'serializedSignedTransaction': json['serialized_signed_transaction'] == null ? undefined : json['serialized_signed_transaction'],
        'expectedResult': json['expected_result'] == null ? undefined : TonTransactionResultFromJSON(json['expected_result']),
        'minedResult': json['mined_result'] == null ? undefined : TonTransactionResultFromJSON(json['mined_result']),
        'explorerUrl': json['explorer_url'] == null ? undefined : json['explorer_url'],
    };
}
