/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PredictAptosSerializedRawTransactionRequest } from './PredictAptosSerializedRawTransactionRequest';
import {
    PredictAptosSerializedRawTransactionRequestToJSON,
} from './PredictAptosSerializedRawTransactionRequest';
import type { PredictAptosTransferRequest } from './PredictAptosTransferRequest';
import {
    PredictAptosTransferRequestToJSON,
} from './PredictAptosTransferRequest';

/**
 * @type TransactionPredictAptosTransactionRequestDetails
 * 
 * @export
 */
export type TransactionPredictAptosTransactionRequestDetails = { type: 'aptos_serialized_entry_point_payload' } & PredictAptosSerializedRawTransactionRequest | { type: 'aptos_transfer' } & PredictAptosTransferRequest;

export function TransactionPredictAptosTransactionRequestDetailsToJSON(json: any): any {
    return TransactionPredictAptosTransactionRequestDetailsToJSONTyped(json, false);
}

function TransactionPredictAptosTransactionRequestDetailsToJSONTyped(value?: TransactionPredictAptosTransactionRequestDetails | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'aptos_serialized_entry_point_payload':
            return Object.assign({}, PredictAptosSerializedRawTransactionRequestToJSON(value), { type: 'aptos_serialized_entry_point_payload' } as const);
        case 'aptos_transfer':
            return Object.assign({}, PredictAptosTransferRequestToJSON(value), { type: 'aptos_transfer' } as const);
        default:
            return value;
    }
}
