/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TransactionDetailsEvmPersonalMessageRequest } from './TransactionDetailsEvmPersonalMessageRequest';
import {
    TransactionDetailsEvmPersonalMessageRequestToJSON,
} from './TransactionDetailsEvmPersonalMessageRequest';
import type { TransactionDetailsEvmTypedMessageRequest } from './TransactionDetailsEvmTypedMessageRequest';
import {
    TransactionDetailsEvmTypedMessageRequestToJSON,
} from './TransactionDetailsEvmTypedMessageRequest';
import type { TransactionDetailsEvmTypedV1MessageRequest } from './TransactionDetailsEvmTypedV1MessageRequest';
import {
    TransactionDetailsEvmTypedV1MessageRequestToJSON,
} from './TransactionDetailsEvmTypedV1MessageRequest';

/**
 * @type TransactionPredictEvmMessageRequestDetails
 * 
 * @export
 */
export type TransactionPredictEvmMessageRequestDetails = { type: 'personal_message_type' } & TransactionDetailsEvmPersonalMessageRequest | { type: 'typed_message_type' } & TransactionDetailsEvmTypedMessageRequest | { type: 'typed_message_type_v1' } & TransactionDetailsEvmTypedV1MessageRequest;

export function TransactionPredictEvmMessageRequestDetailsToJSON(json: any): any {
    return TransactionPredictEvmMessageRequestDetailsToJSONTyped(json, false);
}

function TransactionPredictEvmMessageRequestDetailsToJSONTyped(value?: TransactionPredictEvmMessageRequestDetails | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'personal_message_type':
            return Object.assign({}, TransactionDetailsEvmPersonalMessageRequestToJSON(value), { type: 'personal_message_type' } as const);
        case 'typed_message_type':
            return Object.assign({}, TransactionDetailsEvmTypedMessageRequestToJSON(value), { type: 'typed_message_type' } as const);
        case 'typed_message_type_v1':
            return Object.assign({}, TransactionDetailsEvmTypedV1MessageRequestToJSON(value), { type: 'typed_message_type_v1' } as const);
        default:
            return value;
    }
}
