/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AptosPersonalMessageRequest } from './AptosPersonalMessageRequest';
import {
    AptosPersonalMessageRequestFromJSON,
    AptosPersonalMessageRequestFromJSONTyped,
    AptosPersonalMessageRequestToJSON,
    AptosPersonalMessageRequestToJSONTyped,
} from './AptosPersonalMessageRequest';

/**
 * 
 * @export
 * @interface TransactionPredictAptosMessageRequest
 */
export interface TransactionPredictAptosMessageRequest {
    /**
     * 
     * @type {string}
     * @memberof TransactionPredictAptosMessageRequest
     */
    vaultId: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionPredictAptosMessageRequest
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionPredictAptosMessageRequest
     */
    type: TransactionPredictAptosMessageRequestTypeEnum;
    /**
     * 
     * @type {AptosPersonalMessageRequest}
     * @memberof TransactionPredictAptosMessageRequest
     */
    details: AptosPersonalMessageRequest;
}


/**
 * @export
 */
export const TransactionPredictAptosMessageRequestTypeEnum = {
    aptosMessage: 'aptos_message'
} as const;
export type TransactionPredictAptosMessageRequestTypeEnum = typeof TransactionPredictAptosMessageRequestTypeEnum[keyof typeof TransactionPredictAptosMessageRequestTypeEnum];


/**
 * Check if a given object implements the TransactionPredictAptosMessageRequest interface.
 */
export function instanceOfTransactionPredictAptosMessageRequest(value: object): value is TransactionPredictAptosMessageRequest {
    if (!('vaultId' in value) || value['vaultId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    return true;
}

export function TransactionPredictAptosMessageRequestFromJSON(json: any): TransactionPredictAptosMessageRequest {
    return TransactionPredictAptosMessageRequestFromJSONTyped(json, false);
}

export function TransactionPredictAptosMessageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionPredictAptosMessageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'vaultId': json['vault_id'],
        'note': json['note'] == null ? undefined : json['note'],
        'type': json['type'],
        'details': AptosPersonalMessageRequestFromJSON(json['details']),
    };
}

export function TransactionPredictAptosMessageRequestToJSON(json: any): TransactionPredictAptosMessageRequest {
    return TransactionPredictAptosMessageRequestToJSONTyped(json, false);
}

export function TransactionPredictAptosMessageRequestToJSONTyped(value?: TransactionPredictAptosMessageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vault_id': value['vaultId'],
        'note': value['note'],
        'type': value['type'],
        'details': AptosPersonalMessageRequestToJSON(value['details']),
    };
}

