/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TransactionPredictSuiTransactionRequestDetails } from './TransactionPredictSuiTransactionRequestDetails';
import {
    TransactionPredictSuiTransactionRequestDetailsToJSON,
} from './TransactionPredictSuiTransactionRequestDetails';

/**
 * 
 * @export
 * @interface TransactionPredictSuiTransactionRequest
 */
export interface TransactionPredictSuiTransactionRequest {
    /**
     * Should run a policy check
     * @type {boolean}
     * @memberof TransactionPredictSuiTransactionRequest
     */
    shouldRunPolicyCheck?: boolean;
    /**
     * The unique identifier of the vault.
     * @type {string}
     * @memberof TransactionPredictSuiTransactionRequest
     */
    vaultId: string;
    /**
     * An optional transaction note.
     * @type {string}
     * @memberof TransactionPredictSuiTransactionRequest
     */
    note?: string;
    /**
     * Sui transaction type.
     * @type {TransactionPredictSuiTransactionRequestTypeEnum}
     * @memberof TransactionPredictSuiTransactionRequest
     */
    type: TransactionPredictSuiTransactionRequestTypeEnum;
    /**
     * 
     * @type {TransactionPredictSuiTransactionRequestDetails}
     * @memberof TransactionPredictSuiTransactionRequest
     */
    details: TransactionPredictSuiTransactionRequestDetails;
}


/**
 * @export
 */
const TransactionPredictSuiTransactionRequestTypeEnum = {
    suiTransaction: 'sui_transaction'
} as const;
type TransactionPredictSuiTransactionRequestTypeEnum = typeof TransactionPredictSuiTransactionRequestTypeEnum[keyof typeof TransactionPredictSuiTransactionRequestTypeEnum];

export function TransactionPredictSuiTransactionRequestToJSON(json: any): TransactionPredictSuiTransactionRequest {
    return TransactionPredictSuiTransactionRequestToJSONTyped(json, false);
}

function TransactionPredictSuiTransactionRequestToJSONTyped(value?: TransactionPredictSuiTransactionRequest | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'should_run_policy_check': value['shouldRunPolicyCheck'],
        'vault_id': value['vaultId'],
        'note': value['note'],
        'type': value['type'],
        'details': TransactionPredictSuiTransactionRequestDetailsToJSON(value['details']),
    };
}
