/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface TronTypedMessageV2Base64RawData
 */
export interface TronTypedMessageV2Base64RawData {
    /**
     * Base64 format for raw data.
     * @type {TronTypedMessageV2Base64RawDataFormatEnum}
     * @memberof TronTypedMessageV2Base64RawData
     */
    format: TronTypedMessageV2Base64RawDataFormatEnum;
    /**
     * The message to be signed, base64-encoded.
     * @type {string}
     * @memberof TronTypedMessageV2Base64RawData
     */
    rawDataBase64: string;
}


/**
 * @export
 */
const TronTypedMessageV2Base64RawDataFormatEnum = {
    base64: 'base64'
} as const;
type TronTypedMessageV2Base64RawDataFormatEnum = typeof TronTypedMessageV2Base64RawDataFormatEnum[keyof typeof TronTypedMessageV2Base64RawDataFormatEnum];

export function TronTypedMessageV2Base64RawDataToJSON(json: any): TronTypedMessageV2Base64RawData {
    return TronTypedMessageV2Base64RawDataToJSONTyped(json, false);
}

function TronTypedMessageV2Base64RawDataToJSONTyped(value?: TronTypedMessageV2Base64RawData | null, _ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'format': value['format'],
        'raw_data_base64': value['rawDataBase64'],
    };
}
