/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UnfreezeApprovalState = {
    pending: 'pending',
    approved: 'approved'
} as const;
export type UnfreezeApprovalState = typeof UnfreezeApprovalState[keyof typeof UnfreezeApprovalState];


export function instanceOfUnfreezeApprovalState(value: any): boolean {
    for (const key in UnfreezeApprovalState) {
        if (Object.prototype.hasOwnProperty.call(UnfreezeApprovalState, key)) {
            if (UnfreezeApprovalState[key as keyof typeof UnfreezeApprovalState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UnfreezeApprovalStateFromJSON(json: any): UnfreezeApprovalState {
    return UnfreezeApprovalStateFromJSONTyped(json, false);
}

export function UnfreezeApprovalStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnfreezeApprovalState {
    return json as UnfreezeApprovalState;
}

export function UnfreezeApprovalStateToJSON(value?: UnfreezeApprovalState | null): any {
    return value as any;
}

export function UnfreezeApprovalStateToJSONTyped(value: any, ignoreDiscriminator: boolean): UnfreezeApprovalState {
    return value as UnfreezeApprovalState;
}

