/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    AptosMessage,
    instanceOfAptosMessage,
    AptosMessageFromJSON,
    AptosMessageFromJSONTyped,
    AptosMessageToJSON,
} from './AptosMessage';
import {
    AptosTransaction,
    instanceOfAptosTransaction,
    AptosTransactionFromJSON,
    AptosTransactionFromJSONTyped,
    AptosTransactionToJSON,
} from './AptosTransaction';
import {
    BlackBoxSignature,
    instanceOfBlackBoxSignature,
    BlackBoxSignatureFromJSON,
    BlackBoxSignatureFromJSONTyped,
    BlackBoxSignatureToJSON,
} from './BlackBoxSignature';
import {
    CosmosMessage,
    instanceOfCosmosMessage,
    CosmosMessageFromJSON,
    CosmosMessageFromJSONTyped,
    CosmosMessageToJSON,
} from './CosmosMessage';
import {
    CosmosTransaction,
    instanceOfCosmosTransaction,
    CosmosTransactionFromJSON,
    CosmosTransactionFromJSONTyped,
    CosmosTransactionToJSON,
} from './CosmosTransaction';
import {
    EvmMessage,
    instanceOfEvmMessage,
    EvmMessageFromJSON,
    EvmMessageFromJSONTyped,
    EvmMessageToJSON,
} from './EvmMessage';
import {
    EvmTransaction,
    instanceOfEvmTransaction,
    EvmTransactionFromJSON,
    EvmTransactionFromJSONTyped,
    EvmTransactionToJSON,
} from './EvmTransaction';
import {
    SolanaMessage,
    instanceOfSolanaMessage,
    SolanaMessageFromJSON,
    SolanaMessageFromJSONTyped,
    SolanaMessageToJSON,
} from './SolanaMessage';
import {
    SolanaTransaction,
    instanceOfSolanaTransaction,
    SolanaTransactionFromJSON,
    SolanaTransactionFromJSONTyped,
    SolanaTransactionToJSON,
} from './SolanaTransaction';
import {
    SuiMessage,
    instanceOfSuiMessage,
    SuiMessageFromJSON,
    SuiMessageFromJSONTyped,
    SuiMessageToJSON,
} from './SuiMessage';
import {
    SuiTransaction,
    instanceOfSuiTransaction,
    SuiTransactionFromJSON,
    SuiTransactionFromJSONTyped,
    SuiTransactionToJSON,
} from './SuiTransaction';
import {
    UtxoMessage,
    instanceOfUtxoMessage,
    UtxoMessageFromJSON,
    UtxoMessageFromJSONTyped,
    UtxoMessageToJSON,
} from './UtxoMessage';
import {
    UtxoTransaction,
    instanceOfUtxoTransaction,
    UtxoTransactionFromJSON,
    UtxoTransactionFromJSONTyped,
    UtxoTransactionToJSON,
} from './UtxoTransaction';

/**
 * @type UpdateTransactionForSigningResponse
 * 
 * @export
 */
export type UpdateTransactionForSigningResponse = { type: 'aptos_message' } & AptosMessage | { type: 'aptos_transaction' } & AptosTransaction | { type: 'black_box_signature' } & BlackBoxSignature | { type: 'cosmos_message' } & CosmosMessage | { type: 'cosmos_transaction' } & CosmosTransaction | { type: 'evm_message' } & EvmMessage | { type: 'evm_transaction' } & EvmTransaction | { type: 'solana_message' } & SolanaMessage | { type: 'solana_transaction' } & SolanaTransaction | { type: 'sui_message' } & SuiMessage | { type: 'sui_transaction' } & SuiTransaction | { type: 'utxo_message' } & UtxoMessage | { type: 'utxo_transaction' } & UtxoTransaction;

export function UpdateTransactionForSigningResponseFromJSON(json: any): UpdateTransactionForSigningResponse {
    return UpdateTransactionForSigningResponseFromJSONTyped(json, false);
}

export function UpdateTransactionForSigningResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTransactionForSigningResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'aptos_message':
            return {...AptosMessageFromJSONTyped(json, true), type: 'aptos_message'};
        case 'aptos_transaction':
            return {...AptosTransactionFromJSONTyped(json, true), type: 'aptos_transaction'};
        case 'black_box_signature':
            return {...BlackBoxSignatureFromJSONTyped(json, true), type: 'black_box_signature'};
        case 'cosmos_message':
            return {...CosmosMessageFromJSONTyped(json, true), type: 'cosmos_message'};
        case 'cosmos_transaction':
            return {...CosmosTransactionFromJSONTyped(json, true), type: 'cosmos_transaction'};
        case 'evm_message':
            return {...EvmMessageFromJSONTyped(json, true), type: 'evm_message'};
        case 'evm_transaction':
            return {...EvmTransactionFromJSONTyped(json, true), type: 'evm_transaction'};
        case 'solana_message':
            return {...SolanaMessageFromJSONTyped(json, true), type: 'solana_message'};
        case 'solana_transaction':
            return {...SolanaTransactionFromJSONTyped(json, true), type: 'solana_transaction'};
        case 'sui_message':
            return {...SuiMessageFromJSONTyped(json, true), type: 'sui_message'};
        case 'sui_transaction':
            return {...SuiTransactionFromJSONTyped(json, true), type: 'sui_transaction'};
        case 'utxo_message':
            return {...UtxoMessageFromJSONTyped(json, true), type: 'utxo_message'};
        case 'utxo_transaction':
            return {...UtxoTransactionFromJSONTyped(json, true), type: 'utxo_transaction'};
        default:
            throw new Error(`No variant of UpdateTransactionForSigningResponse exists with 'type=${json['type']}'`);
    }
}

export function UpdateTransactionForSigningResponseToJSON(value?: UpdateTransactionForSigningResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'aptos_message':
            return AptosMessageToJSON(value);
        case 'aptos_transaction':
            return AptosTransactionToJSON(value);
        case 'black_box_signature':
            return BlackBoxSignatureToJSON(value);
        case 'cosmos_message':
            return CosmosMessageToJSON(value);
        case 'cosmos_transaction':
            return CosmosTransactionToJSON(value);
        case 'evm_message':
            return EvmMessageToJSON(value);
        case 'evm_transaction':
            return EvmTransactionToJSON(value);
        case 'solana_message':
            return SolanaMessageToJSON(value);
        case 'solana_transaction':
            return SolanaTransactionToJSON(value);
        case 'sui_message':
            return SuiMessageToJSON(value);
        case 'sui_transaction':
            return SuiTransactionToJSON(value);
        case 'utxo_message':
            return UtxoMessageToJSON(value);
        case 'utxo_transaction':
            return UtxoTransactionToJSON(value);
        default:
            throw new Error(`No variant of UpdateTransactionForSigningResponse exists with 'type=${value['type']}'`);
    }

}

