/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { UtxoChain } from './UtxoChain';
import {
    UtxoChainFromJSON,
} from './UtxoChain';

/**
 * 
 * @export
 * @interface UtxoAddressBookContactAddressRef
 */
export interface UtxoAddressBookContactAddressRef {
    /**
     * 
     * @type {string}
     * @memberof UtxoAddressBookContactAddressRef
     */
    chainType: UtxoAddressBookContactAddressRefChainTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UtxoAddressBookContactAddressRef
     */
    address: string;
    /**
     * 
     * @type {UtxoChain}
     * @memberof UtxoAddressBookContactAddressRef
     */
    chain: UtxoChain;
}


/**
 * 
 */
const UtxoAddressBookContactAddressRefChainTypeEnum = {
    utxo: 'utxo'
} as const;
type UtxoAddressBookContactAddressRefChainTypeEnum = typeof UtxoAddressBookContactAddressRefChainTypeEnum[keyof typeof UtxoAddressBookContactAddressRefChainTypeEnum];

export function UtxoAddressBookContactAddressRefFromJSONTyped(json: any, _ignoreDiscriminator: boolean): UtxoAddressBookContactAddressRef {
    if (json == null) {
        return json;
    }
    return {
        
        'chainType': json['chain_type'],
        'address': json['address'],
        'chain': UtxoChainFromJSON(json['chain']),
    };
}
