/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UtxoChainUniqueId } from './UtxoChainUniqueId';
import {
    UtxoChainUniqueIdFromJSON,
    UtxoChainUniqueIdFromJSONTyped,
    UtxoChainUniqueIdToJSON,
    UtxoChainUniqueIdToJSONTyped,
} from './UtxoChainUniqueId';

/**
 * 
 * @export
 * @interface UtxoSuggestedFees
 */
export interface UtxoSuggestedFees {
    /**
     * 
     * @type {string}
     * @memberof UtxoSuggestedFees
     */
    type: UtxoSuggestedFeesTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UtxoSuggestedFees
     */
    low: string;
    /**
     * 
     * @type {string}
     * @memberof UtxoSuggestedFees
     */
    medium: string;
    /**
     * 
     * @type {string}
     * @memberof UtxoSuggestedFees
     */
    high: string;
    /**
     * 
     * @type {UtxoChainUniqueId}
     * @memberof UtxoSuggestedFees
     */
    chainUniqueId: UtxoChainUniqueId;
}


/**
 * @export
 */
export const UtxoSuggestedFeesTypeEnum = {
    utxo: 'utxo'
} as const;
export type UtxoSuggestedFeesTypeEnum = typeof UtxoSuggestedFeesTypeEnum[keyof typeof UtxoSuggestedFeesTypeEnum];


/**
 * Check if a given object implements the UtxoSuggestedFees interface.
 */
export function instanceOfUtxoSuggestedFees(value: object): value is UtxoSuggestedFees {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('low' in value) || value['low'] === undefined) return false;
    if (!('medium' in value) || value['medium'] === undefined) return false;
    if (!('high' in value) || value['high'] === undefined) return false;
    if (!('chainUniqueId' in value) || value['chainUniqueId'] === undefined) return false;
    return true;
}

export function UtxoSuggestedFeesFromJSON(json: any): UtxoSuggestedFees {
    return UtxoSuggestedFeesFromJSONTyped(json, false);
}

export function UtxoSuggestedFeesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UtxoSuggestedFees {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'low': json['low'],
        'medium': json['medium'],
        'high': json['high'],
        'chainUniqueId': UtxoChainUniqueIdFromJSON(json['chain_unique_id']),
    };
}

export function UtxoSuggestedFeesToJSON(json: any): UtxoSuggestedFees {
    return UtxoSuggestedFeesToJSONTyped(json, false);
}

export function UtxoSuggestedFeesToJSONTyped(value?: UtxoSuggestedFees | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'low': value['low'],
        'medium': value['medium'],
        'high': value['high'],
        'chain_unique_id': UtxoChainUniqueIdToJSON(value['chainUniqueId']),
    };
}

