/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnrichedUtxoChain } from './EnrichedUtxoChain';
import {
    EnrichedUtxoChainFromJSON,
    EnrichedUtxoChainFromJSONTyped,
    EnrichedUtxoChainToJSON,
    EnrichedUtxoChainToJSONTyped,
} from './EnrichedUtxoChain';

/**
 * 
 * @export
 * @interface UtxoNativeAsset
 */
export interface UtxoNativeAsset {
    /**
     * 
     * @type {EnrichedUtxoChain}
     * @memberof UtxoNativeAsset
     */
    chain: EnrichedUtxoChain;
    /**
     * 
     * @type {string}
     * @memberof UtxoNativeAsset
     */
    type: UtxoNativeAssetTypeEnum;
}


/**
 * @export
 */
export const UtxoNativeAssetTypeEnum = {
    utxoNativeAsset: 'utxo_native_asset'
} as const;
export type UtxoNativeAssetTypeEnum = typeof UtxoNativeAssetTypeEnum[keyof typeof UtxoNativeAssetTypeEnum];


/**
 * Check if a given object implements the UtxoNativeAsset interface.
 */
export function instanceOfUtxoNativeAsset(value: object): value is UtxoNativeAsset {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function UtxoNativeAssetFromJSON(json: any): UtxoNativeAsset {
    return UtxoNativeAssetFromJSONTyped(json, false);
}

export function UtxoNativeAssetFromJSONTyped(json: any, ignoreDiscriminator: boolean): UtxoNativeAsset {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': EnrichedUtxoChainFromJSON(json['chain']),
        'type': json['type'],
    };
}

export function UtxoNativeAssetToJSON(json: any): UtxoNativeAsset {
    return UtxoNativeAssetToJSONTyped(json, false);
}

export function UtxoNativeAssetToJSONTyped(value?: UtxoNativeAsset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': EnrichedUtxoChainToJSON(value['chain']),
        'type': value['type'],
    };
}

