/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UtxoVaultSubType = {
    mainnet: 'bitcoin_mainnet',
    testnet: 'bitcoin_testnet'
} as const;
export type UtxoVaultSubType = typeof UtxoVaultSubType[keyof typeof UtxoVaultSubType];


export function UtxoVaultSubTypeFromJSON(json: any): UtxoVaultSubType {
    return UtxoVaultSubTypeFromJSONTyped(json, false);
}

export function UtxoVaultSubTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UtxoVaultSubType {
    return json as UtxoVaultSubType;
}

export function UtxoVaultSubTypeToJSON(value?: UtxoVaultSubType | null): any {
    return value as any;
}

