/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationErrorDetailLocInner
 */
export interface ValidationErrorDetailLocInner {
}

/**
 * Check if a given object implements the ValidationErrorDetailLocInner interface.
 */
export function instanceOfValidationErrorDetailLocInner(value: object): value is ValidationErrorDetailLocInner {
    return true;
}

export function ValidationErrorDetailLocInnerFromJSON(json: any): ValidationErrorDetailLocInner {
    return ValidationErrorDetailLocInnerFromJSONTyped(json, false);
}

export function ValidationErrorDetailLocInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorDetailLocInner {
    return json;
}

export function ValidationErrorDetailLocInnerToJSON(json: any): ValidationErrorDetailLocInner {
    return ValidationErrorDetailLocInnerToJSONTyped(json, false);
}

export function ValidationErrorDetailLocInnerToJSONTyped(value?: ValidationErrorDetailLocInner | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

