/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRef } from './UserRef';
import {
    UserRefFromJSON,
    UserRefFromJSONTyped,
    UserRefToJSON,
    UserRefToJSONTyped,
} from './UserRef';

/**
 * 
 * @export
 * @interface VaultGroupPendingChangeRequestInfo
 */
export interface VaultGroupPendingChangeRequestInfo {
    /**
     * 
     * @type {string}
     * @memberof VaultGroupPendingChangeRequestInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof VaultGroupPendingChangeRequestInfo
     */
    newName: string;
    /**
     * 
     * @type {UserRef}
     * @memberof VaultGroupPendingChangeRequestInfo
     */
    createdBy: UserRef;
    /**
     * 
     * @type {Date}
     * @memberof VaultGroupPendingChangeRequestInfo
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the VaultGroupPendingChangeRequestInfo interface.
 */
export function instanceOfVaultGroupPendingChangeRequestInfo(value: object): value is VaultGroupPendingChangeRequestInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('newName' in value) || value['newName'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function VaultGroupPendingChangeRequestInfoFromJSON(json: any): VaultGroupPendingChangeRequestInfo {
    return VaultGroupPendingChangeRequestInfoFromJSONTyped(json, false);
}

export function VaultGroupPendingChangeRequestInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VaultGroupPendingChangeRequestInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'newName': json['new_name'],
        'createdBy': UserRefFromJSON(json['created_by']),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function VaultGroupPendingChangeRequestInfoToJSON(json: any): VaultGroupPendingChangeRequestInfo {
    return VaultGroupPendingChangeRequestInfoToJSONTyped(json, false);
}

export function VaultGroupPendingChangeRequestInfoToJSONTyped(value?: VaultGroupPendingChangeRequestInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'new_name': value['newName'],
        'created_by': UserRefToJSON(value['createdBy']),
        'created_at': ((value['createdAt']).toISOString()),
    };
}

