/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserGroupRef } from './UserGroupRef';
import {
    UserGroupRefFromJSON,
    UserGroupRefFromJSONTyped,
    UserGroupRefToJSON,
} from './UserGroupRef';
import type { UserRef } from './UserRef';
import {
    UserRefFromJSON,
    UserRefFromJSONTyped,
    UserRefToJSON,
} from './UserRef';

/**
 * 
 * @export
 * @interface VaultGroupAccessPermissionsPermitted
 */
export interface VaultGroupAccessPermissionsPermitted {
    /**
     * 
     * @type {string}
     * @memberof VaultGroupAccessPermissionsPermitted
     */
    accessType: VaultGroupAccessPermissionsPermittedAccessTypeEnum;
    /**
     * 
     * @type {Array<UserGroupRef>}
     * @memberof VaultGroupAccessPermissionsPermitted
     */
    userGroups: Array<UserGroupRef>;
    /**
     * 
     * @type {Array<UserRef>}
     * @memberof VaultGroupAccessPermissionsPermitted
     */
    users: Array<UserRef>;
}


/**
 * @export
 */
export const VaultGroupAccessPermissionsPermittedAccessTypeEnum = {
    permitted: 'permitted'
} as const;
export type VaultGroupAccessPermissionsPermittedAccessTypeEnum = typeof VaultGroupAccessPermissionsPermittedAccessTypeEnum[keyof typeof VaultGroupAccessPermissionsPermittedAccessTypeEnum];


/**
 * Check if a given object implements the VaultGroupAccessPermissionsPermitted interface.
 */
export function instanceOfVaultGroupAccessPermissionsPermitted(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessType" in value;
    isInstance = isInstance && "userGroups" in value;
    isInstance = isInstance && "users" in value;

    return isInstance;
}

export function VaultGroupAccessPermissionsPermittedFromJSON(json: any): VaultGroupAccessPermissionsPermitted {
    return VaultGroupAccessPermissionsPermittedFromJSONTyped(json, false);
}

export function VaultGroupAccessPermissionsPermittedFromJSONTyped(json: any, ignoreDiscriminator: boolean): VaultGroupAccessPermissionsPermitted {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessType': json['access_type'],
        'userGroups': ((json['user_groups'] as Array<any>).map(UserGroupRefFromJSON)),
        'users': ((json['users'] as Array<any>).map(UserRefFromJSON)),
    };
}

export function VaultGroupAccessPermissionsPermittedToJSON(value?: VaultGroupAccessPermissionsPermitted | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_type': value.accessType,
        'user_groups': ((value.userGroups as Array<any>).map(UserGroupRefToJSON)),
        'users': ((value.users as Array<any>).map(UserRefToJSON)),
    };
}

