/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * @export
 */
export const VaultType = {
    Aptos: 'aptos',
    BlackBox: 'black_box',
    Cosmos: 'cosmos',
    Evm: 'evm',
    Safe: 'safe',
    Solana: 'solana',
    Stacks: 'stacks',
    Starknet: 'starknet',
    Sui: 'sui',
    Ton: 'ton',
    Tron: 'tron',
    Utxo: 'utxo',
    Exchange: 'exchange'
} as const;
export type VaultType = typeof VaultType[keyof typeof VaultType];

export function VaultTypeFromJSON(json: any): VaultType {
    return VaultTypeFromJSONTyped(json, false);
}

function VaultTypeFromJSONTyped(json: any, _ignoreDiscriminator: boolean): VaultType {
    return json as VaultType;
}

