/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionSpamState } from './TransactionSpamState';
import {
    TransactionSpamStateFromJSON,
    TransactionSpamStateFromJSONTyped,
    TransactionSpamStateToJSON,
    TransactionSpamStateToJSONTyped,
} from './TransactionSpamState';
import type { TransactionDirection } from './TransactionDirection';
import {
    TransactionDirectionFromJSON,
    TransactionDirectionFromJSONTyped,
    TransactionDirectionToJSON,
    TransactionDirectionToJSONTyped,
} from './TransactionDirection';
import type { StarknetMessageType } from './StarknetMessageType';
import {
    StarknetMessageTypeFromJSON,
    StarknetMessageTypeFromJSONTyped,
    StarknetMessageTypeToJSON,
    StarknetMessageTypeToJSONTyped,
} from './StarknetMessageType';
import type { StarknetChain } from './StarknetChain';
import {
    StarknetChainFromJSON,
    StarknetChainFromJSONTyped,
    StarknetChainToJSON,
    StarknetChainToJSONTyped,
} from './StarknetChain';
import type { NonPushableTransactionState } from './NonPushableTransactionState';
import {
    NonPushableTransactionStateFromJSON,
    NonPushableTransactionStateFromJSONTyped,
    NonPushableTransactionStateToJSON,
    NonPushableTransactionStateToJSONTyped,
} from './NonPushableTransactionState';

/**
 * 
 * @export
 * @interface WebhookStarknetMessageStatusChangeEvent
 */
export interface WebhookStarknetMessageStatusChangeEvent {
    /**
     * 
     * @type {string}
     * @memberof WebhookStarknetMessageStatusChangeEvent
     */
    transactionId: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookStarknetMessageStatusChangeEvent
     * @deprecated
     */
    isManagedTransaction: boolean;
    /**
     * 
     * @type {TransactionDirection}
     * @memberof WebhookStarknetMessageStatusChangeEvent
     */
    direction: TransactionDirection;
    /**
     * 
     * @type {string}
     * @memberof WebhookStarknetMessageStatusChangeEvent
     */
    note?: string;
    /**
     * 
     * @type {TransactionSpamState}
     * @memberof WebhookStarknetMessageStatusChangeEvent
     */
    spamState: TransactionSpamState;
    /**
     * 
     * @type {NonPushableTransactionState}
     * @memberof WebhookStarknetMessageStatusChangeEvent
     */
    state: NonPushableTransactionState;
    /**
     * 
     * @type {string}
     * @memberof WebhookStarknetMessageStatusChangeEvent
     */
    type: WebhookStarknetMessageStatusChangeEventTypeEnum;
    /**
     * 
     * @type {StarknetMessageType}
     * @memberof WebhookStarknetMessageStatusChangeEvent
     */
    starknetMessageType: StarknetMessageType;
    /**
     * 
     * @type {StarknetChain}
     * @memberof WebhookStarknetMessageStatusChangeEvent
     */
    chain: StarknetChain;
}


/**
 * @export
 */
export const WebhookStarknetMessageStatusChangeEventTypeEnum = {
    starknetMessage: 'starknet_message'
} as const;
export type WebhookStarknetMessageStatusChangeEventTypeEnum = typeof WebhookStarknetMessageStatusChangeEventTypeEnum[keyof typeof WebhookStarknetMessageStatusChangeEventTypeEnum];


/**
 * Check if a given object implements the WebhookStarknetMessageStatusChangeEvent interface.
 */
export function instanceOfWebhookStarknetMessageStatusChangeEvent(value: object): value is WebhookStarknetMessageStatusChangeEvent {
    if (!('transactionId' in value) || value['transactionId'] === undefined) return false;
    if (!('isManagedTransaction' in value) || value['isManagedTransaction'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('spamState' in value) || value['spamState'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('starknetMessageType' in value) || value['starknetMessageType'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    return true;
}

export function WebhookStarknetMessageStatusChangeEventFromJSON(json: any): WebhookStarknetMessageStatusChangeEvent {
    return WebhookStarknetMessageStatusChangeEventFromJSONTyped(json, false);
}

export function WebhookStarknetMessageStatusChangeEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookStarknetMessageStatusChangeEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionId': json['transaction_id'],
        'isManagedTransaction': json['is_managed_transaction'],
        'direction': TransactionDirectionFromJSON(json['direction']),
        'note': json['note'] == null ? undefined : json['note'],
        'spamState': TransactionSpamStateFromJSON(json['spam_state']),
        'state': NonPushableTransactionStateFromJSON(json['state']),
        'type': json['type'],
        'starknetMessageType': StarknetMessageTypeFromJSON(json['starknet_message_type']),
        'chain': StarknetChainFromJSON(json['chain']),
    };
}

export function WebhookStarknetMessageStatusChangeEventToJSON(json: any): WebhookStarknetMessageStatusChangeEvent {
    return WebhookStarknetMessageStatusChangeEventToJSONTyped(json, false);
}

export function WebhookStarknetMessageStatusChangeEventToJSONTyped(value?: WebhookStarknetMessageStatusChangeEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction_id': value['transactionId'],
        'is_managed_transaction': value['isManagedTransaction'],
        'direction': TransactionDirectionToJSON(value['direction']),
        'note': value['note'],
        'spam_state': TransactionSpamStateToJSON(value['spamState']),
        'state': NonPushableTransactionStateToJSON(value['state']),
        'type': value['type'],
        'starknet_message_type': StarknetMessageTypeToJSON(value['starknetMessageType']),
        'chain': StarknetChainToJSON(value['chain']),
    };
}

