/* tslint:disable */
/* eslint-disable */
/**
 * Fordefi API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AptosChain } from './AptosChain';
import {
    AptosChainFromJSON,
    AptosChainFromJSONTyped,
    AptosChainToJSON,
} from './AptosChain';
import type { AptosMessageState } from './AptosMessageState';
import {
    AptosMessageStateFromJSON,
    AptosMessageStateFromJSONTyped,
    AptosMessageStateToJSON,
} from './AptosMessageState';
import type { AptosMessageType } from './AptosMessageType';
import {
    AptosMessageTypeFromJSON,
    AptosMessageTypeFromJSONTyped,
    AptosMessageTypeToJSON,
} from './AptosMessageType';
import type { TransactionDirection } from './TransactionDirection';
import {
    TransactionDirectionFromJSON,
    TransactionDirectionFromJSONTyped,
    TransactionDirectionToJSON,
} from './TransactionDirection';
import type { TransactionSpamState } from './TransactionSpamState';
import {
    TransactionSpamStateFromJSON,
    TransactionSpamStateFromJSONTyped,
    TransactionSpamStateToJSON,
} from './TransactionSpamState';

/**
 * 
 * @export
 * @interface WebhookAptosMessageStatusChangeEvent
 */
export interface WebhookAptosMessageStatusChangeEvent {
    /**
     * 
     * @type {string}
     * @memberof WebhookAptosMessageStatusChangeEvent
     */
    transactionId: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookAptosMessageStatusChangeEvent
     * @deprecated
     */
    isManagedTransaction: boolean;
    /**
     * 
     * @type {TransactionDirection}
     * @memberof WebhookAptosMessageStatusChangeEvent
     */
    direction: TransactionDirection;
    /**
     * 
     * @type {string}
     * @memberof WebhookAptosMessageStatusChangeEvent
     */
    note?: string;
    /**
     * 
     * @type {TransactionSpamState}
     * @memberof WebhookAptosMessageStatusChangeEvent
     */
    spamState: TransactionSpamState;
    /**
     * 
     * @type {string}
     * @memberof WebhookAptosMessageStatusChangeEvent
     */
    type: WebhookAptosMessageStatusChangeEventTypeEnum;
    /**
     * 
     * @type {AptosMessageType}
     * @memberof WebhookAptosMessageStatusChangeEvent
     */
    aptosMessageType: AptosMessageType;
    /**
     * 
     * @type {AptosMessageState}
     * @memberof WebhookAptosMessageStatusChangeEvent
     */
    state: AptosMessageState;
    /**
     * 
     * @type {AptosChain}
     * @memberof WebhookAptosMessageStatusChangeEvent
     */
    chain: AptosChain;
}


/**
 * @export
 */
export const WebhookAptosMessageStatusChangeEventTypeEnum = {
    aptosMessage: 'aptos_message'
} as const;
export type WebhookAptosMessageStatusChangeEventTypeEnum = typeof WebhookAptosMessageStatusChangeEventTypeEnum[keyof typeof WebhookAptosMessageStatusChangeEventTypeEnum];


/**
 * Check if a given object implements the WebhookAptosMessageStatusChangeEvent interface.
 */
export function instanceOfWebhookAptosMessageStatusChangeEvent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "transactionId" in value;
    isInstance = isInstance && "isManagedTransaction" in value;
    isInstance = isInstance && "direction" in value;
    isInstance = isInstance && "spamState" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "aptosMessageType" in value;
    isInstance = isInstance && "state" in value;
    isInstance = isInstance && "chain" in value;

    return isInstance;
}

export function WebhookAptosMessageStatusChangeEventFromJSON(json: any): WebhookAptosMessageStatusChangeEvent {
    return WebhookAptosMessageStatusChangeEventFromJSONTyped(json, false);
}

export function WebhookAptosMessageStatusChangeEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookAptosMessageStatusChangeEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transactionId': json['transaction_id'],
        'isManagedTransaction': json['is_managed_transaction'],
        'direction': TransactionDirectionFromJSON(json['direction']),
        'note': !exists(json, 'note') ? undefined : json['note'],
        'spamState': TransactionSpamStateFromJSON(json['spam_state']),
        'type': json['type'],
        'aptosMessageType': AptosMessageTypeFromJSON(json['aptos_message_type']),
        'state': AptosMessageStateFromJSON(json['state']),
        'chain': AptosChainFromJSON(json['chain']),
    };
}

export function WebhookAptosMessageStatusChangeEventToJSON(value?: WebhookAptosMessageStatusChangeEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transaction_id': value.transactionId,
        'is_managed_transaction': value.isManagedTransaction,
        'direction': TransactionDirectionToJSON(value.direction),
        'note': value.note,
        'spam_state': TransactionSpamStateToJSON(value.spamState),
        'type': value.type,
        'aptos_message_type': AptosMessageTypeToJSON(value.aptosMessageType),
        'state': AptosMessageStateToJSON(value.state),
        'chain': AptosChainToJSON(value.chain),
    };
}

